"""
Batch 65 - Italian, French, Spanish, Portuguese cuisine x London postcodes/areas
Covers: Italian restaurants/cafes/trattorias/osterias, French brasseries/bistros/cafes,
Spanish tapas/restaurants, Portuguese restaurants across all London zones.
"""

SEARCH_QUERIES = [
    # Italian restaurants x inner East London
    "Italian restaurants E1 London",
    "Italian restaurants E2 London",
    "Italian restaurants E3 London",
    "Italian restaurants E8 London",
    "Italian restaurants E9 London",
    "Italian restaurants E14 London",
    "Italian restaurants E15 London",
    "Italian restaurants E17 London",
    # Italian x inner North London
    "Italian restaurants N1 London",
    "Italian restaurants N4 London",
    "Italian restaurants N5 London",
    "Italian restaurants N7 London",
    "Italian restaurants N8 London",
    "Italian restaurants N10 London",
    "Italian restaurants N16 London",
    "Italian restaurants N19 London",
    # Italian x inner South London
    "Italian restaurants SE1 London",
    "Italian restaurants SE5 London",
    "Italian restaurants SE8 London",
    "Italian restaurants SE10 London",
    "Italian restaurants SE15 London",
    "Italian restaurants SE22 London",
    "Italian restaurants SE24 London",
    "Italian restaurants SW2 London",
    "Italian restaurants SW4 London",
    "Italian restaurants SW9 London",
    "Italian restaurants SW11 London",
    "Italian restaurants SW12 London",
    # Italian x inner West/Central London
    "Italian restaurants W1 London",
    "Italian restaurants W4 London",
    "Italian restaurants W6 London",
    "Italian restaurants W11 London",
    "Italian restaurants W12 London",
    "Italian restaurants EC1 London",
    "Italian restaurants EC2 London",
    "Italian restaurants WC1 London",
    "Italian restaurants WC2 London",
    # Italian x inner Northwest London
    "Italian restaurants NW1 London",
    "Italian restaurants NW3 London",
    "Italian restaurants NW5 London",
    "Italian restaurants NW6 London",
    "Italian restaurants NW8 London",
    "Italian restaurants NW10 London",
    # Trattoria searches
    "trattoria London E1",
    "trattoria London N1",
    "trattoria London W1",
    "trattoria London SW3",
    "trattoria London SE1",
    "trattoria London NW1",
    "trattoria London WC2",
    "trattoria London EC1",
    "trattoria Soho London",
    "trattoria Islington London",
    "trattoria Notting Hill London",
    "trattoria Battersea London",
    "trattoria Clapham London",
    "trattoria Hackney London",
    "trattoria Brixton London",
    "trattoria Camden London",
    "trattoria Shoreditch London",
    "trattoria Hammersmith London",
    "trattoria Shepherd's Bush London",
    "trattoria Greenwich London",
    # Osteria searches
    "osteria London W1",
    "osteria London SW3",
    "osteria London N1",
    "osteria London EC1",
    "osteria London WC2",
    "osteria London SE1",
    "osteria London NW3",
    "osteria Shoreditch London",
    "osteria Islington London",
    "osteria Chelsea London",
    # French restaurants x London
    "French restaurants E1 London",
    "French restaurants N1 London",
    "French restaurants N4 London",
    "French restaurants N16 London",
    "French restaurants SE1 London",
    "French restaurants SE5 London",
    "French restaurants SE22 London",
    "French restaurants SW3 London",
    "French restaurants SW4 London",
    "French restaurants SW6 London",
    "French restaurants SW7 London",
    "French restaurants SW10 London",
    "French restaurants SW11 London",
    "French restaurants W1 London",
    "French restaurants W4 London",
    "French restaurants W6 London",
    "French restaurants W8 London",
    "French restaurants W11 London",
    "French restaurants WC2 London",
    "French restaurants EC1 London",
    "French restaurants NW1 London",
    "French restaurants NW3 London",
    # Brasserie searches
    "brasserie London E1",
    "brasserie London N1",
    "brasserie London SE1",
    "brasserie London SW1",
    "brasserie London SW3",
    "brasserie London SW6",
    "brasserie London SW7",
    "brasserie London SW11",
    "brasserie London W1",
    "brasserie London W4",
    "brasserie London W8",
    "brasserie London WC2",
    "brasserie London EC1",
    "brasserie London EC2",
    "brasserie London NW1",
    "brasserie London NW3",
    "brasserie Soho London",
    "brasserie Mayfair London",
    "brasserie Chelsea London",
    "brasserie Notting Hill London",
    "brasserie Brixton London",
    "brasserie Clapham London",
    "brasserie Battersea London",
    "brasserie Shoreditch London",
    "brasserie Islington London",
    "brasserie Hackney London",
    "brasserie Greenwich London",
    "brasserie Dulwich London",
    # Bistro searches
    "bistro London E1",
    "bistro London E8",
    "bistro London N1",
    "bistro London N4",
    "bistro London N16",
    "bistro London SE1",
    "bistro London SE5",
    "bistro London SE15",
    "bistro London SE22",
    "bistro London SW4",
    "bistro London SW9",
    "bistro London SW11",
    "bistro London W1",
    "bistro London W4",
    "bistro London W11",
    "bistro London WC2",
    "bistro London EC1",
    "bistro London NW1",
    "bistro London NW3",
    "bistro Soho London",
    "bistro Islington London",
    "bistro Notting Hill London",
    "bistro Clapham London",
    "bistro Brixton London",
    "bistro Peckham London",
    "bistro Shoreditch London",
    "bistro Dalston London",
    "bistro Hackney London",
    "bistro Wimbledon London",
    "bistro Richmond London",
    "bistro Greenwich London",
    "bistro Chiswick London",
    # Spanish restaurants x London
    "Spanish restaurants E1 London",
    "Spanish restaurants N1 London",
    "Spanish restaurants SE1 London",
    "Spanish restaurants SW1 London",
    "Spanish restaurants SW3 London",
    "Spanish restaurants SW7 London",
    "Spanish restaurants W1 London",
    "Spanish restaurants WC2 London",
    "Spanish restaurants EC1 London",
    "Spanish restaurants NW1 London",
    "Spanish tapas London E1",
    "Spanish tapas London N1",
    "Spanish tapas London SE1",
    "Spanish tapas London SW3",
    "Spanish tapas London W1",
    "Spanish tapas London WC2",
    "tapas bar London Soho",
    "tapas bar London Shoreditch",
    "tapas bar London Islington",
    "tapas bar London Brixton",
    "tapas bar London Clapham",
    "tapas bar London Chelsea",
    "tapas bar London Notting Hill",
    "tapas bar London Camden",
    "tapas bar London Hackney",
    "tapas bar London Dalston",
    "tapas bar London Bermondsey",
    "tapas bar London Borough",
    # Portuguese restaurants x London
    "Portuguese restaurants London E1",
    "Portuguese restaurants London N1",
    "Portuguese restaurants London SE1",
    "Portuguese restaurants London SW9",
    "Portuguese restaurants London W1",
    "Portuguese restaurants London WC2",
    "Portuguese restaurants London NW1",
    "Portuguese restaurants London EC1",
    "Portuguese cafe London",
    "Portuguese bakery London",
    "pastelaria London",
    "pastel de nata London E1",
    "pastel de nata London N1",
    "pastel de nata London SE1",
    "pastel de nata London W1",
    "pastel de nata London SW9",
    "pastel de nata London NW1",
    # French cafes x London
    "French cafe London W1",
    "French cafe London SW3",
    "French cafe London SW7",
    "French cafe London WC2",
    "French cafe London NW3",
    "French cafe London EC1",
    "French cafe London N1",
    "French cafe London SE1",
    "French patisserie E1 London",
    "French patisserie N1 London",
    "French patisserie SW3 London",
    "French patisserie W1 London",
    "French patisserie WC2 London",
    "French patisserie NW3 London",
    "French patisserie SE1 London",
    "French patisserie EC1 London",
    # Cafe de Paris / continental cafes
    "continental cafe London E1",
    "continental cafe London N1",
    "continental cafe London SE1",
    "continental cafe London SW1",
    "continental cafe London W1",
    "continental cafe London NW1",
    "European cafe London Soho",
    "European cafe London Islington",
    "European cafe London Shoreditch",
    "European cafe London Chelsea",
    "European restaurant London SW3",
    "European restaurant London W1",
    "European restaurant London WC2",
    "European restaurant London EC1",
    "European restaurant London SE1",
    "European restaurant London N1",
    "European restaurant London NW1",
    "European restaurant London SW11",
    # Italian-style cafes and delis
    "Italian cafe London E1",
    "Italian cafe London N1",
    "Italian cafe London SE1",
    "Italian cafe London SW3",
    "Italian cafe London W1",
    "Italian cafe London WC2",
    "Italian cafe London NW1",
    "Italian cafe London EC1",
    "Italian deli London W1",
    "Italian deli London SW3",
    "Italian deli London NW1",
    "Italian deli London N1",
    "Italian deli London EC1",
    "Italian deli London SE1",
    "Italian deli London E1",
    "Italian deli London Soho",
    "Italian deli London Islington",
    "espresso bar London E1",
    "espresso bar London EC1",
    "espresso bar London WC1",
    "espresso bar London N1",
    "espresso bar London SE1",
]
