"""
Batch 75 - North and Northwest London neighborhoods: Finchley, Barnet, Mill Hill,
Hendon, Golders Green, Temple Fortune, Edgware, Colindale, Brent Cross,
Kilburn, Queen's Park, Maida Vale, Little Venice, Paddington, Kensal Rise.
"""

SEARCH_QUERIES = [
    # Golders Green / Temple Fortune
    "restaurants Golders Green London NW11",
    "cafes Golders Green London NW11",
    "restaurants Golders Green Road London NW11",
    "cafes Golders Green Road London NW11",
    "restaurants Temple Fortune London NW11",
    "cafes Temple Fortune London NW11",
    "kosher restaurants Golders Green London",
    "kosher cafe Golders Green London NW11",
    "Israeli restaurant Golders Green London",
    "Middle Eastern restaurant Golders Green London",
    "Persian restaurant Golders Green London",
    "Japanese restaurant Golders Green London",
    "brunch Golders Green London",
    "pizza restaurant Golders Green London NW11",
    "vegan restaurant Golders Green London",
    "kosher bakery Golders Green London NW11",
    # Hendon / Brent Street
    "restaurants Hendon London NW4",
    "cafes Hendon London NW4",
    "restaurants Brent Street Hendon London NW4",
    "cafes Brent Street Hendon London NW4",
    "restaurants Central Hendon London NW4",
    "kosher restaurant Hendon London NW4",
    "kosher cafe Hendon London NW4",
    "Middle Eastern restaurant Hendon London",
    "brunch Hendon London",
    "pizza restaurant Hendon London NW4",
    # Edgware / Burnt Oak
    "restaurants Edgware London HA8",
    "cafes Edgware London HA8",
    "restaurants Edgware High Street London HA8",
    "cafes Edgware High Street London HA8",
    "restaurants Burnt Oak London HA8",
    "cafes Burnt Oak London HA8",
    "kosher restaurant Edgware London",
    "Indian restaurant Edgware London",
    "Middle Eastern restaurant Edgware London",
    "brunch Edgware London",
    "pizza restaurant Edgware London HA8",
    # Finchley / East Finchley / North Finchley
    "restaurants Finchley London N3",
    "cafes Finchley London N3",
    "restaurants North Finchley London N12",
    "cafes North Finchley London N12",
    "restaurants East Finchley London N2",
    "cafes East Finchley London N2",
    "restaurants Ballards Lane London N3",
    "cafes Ballards Lane London N3",
    "restaurants High Road North Finchley London N12",
    "cafes High Road North Finchley London N12",
    "restaurants Long Lane Finchley London N3",
    "restaurants Friern Barnet Road London N11",
    "brunch Finchley London",
    "brunch East Finchley London",
    "pizza restaurant Finchley London N3",
    "vegan restaurant East Finchley London",
    "gastropub Finchley London",
    "gastropub East Finchley London",
    "kosher restaurant Finchley London",
    # Barnet / High Barnet / New Barnet
    "restaurants Barnet London EN5",
    "cafes Barnet London EN5",
    "restaurants High Barnet London EN5",
    "cafes High Barnet London EN5",
    "restaurants New Barnet London EN5",
    "cafes New Barnet London EN5",
    "restaurants Chipping Barnet London EN5",
    "brunch Barnet London",
    "pizza restaurant Barnet London EN5",
    "gastropub Barnet London",
    # Mill Hill / Edgware Road NW7
    "restaurants Mill Hill London NW7",
    "cafes Mill Hill London NW7",
    "restaurants Mill Hill Broadway London NW7",
    "cafes Mill Hill Broadway London NW7",
    "restaurants Hale Lane Mill Hill London NW7",
    "brunch Mill Hill London",
    "pizza restaurant Mill Hill London NW7",
    "gastropub Mill Hill London",
    # Colindale / Kingsbury
    "restaurants Colindale London NW9",
    "cafes Colindale London NW9",
    "restaurants Kingsbury London NW9",
    "cafes Kingsbury London NW9",
    "restaurants Kingsbury Road London NW9",
    "Indian restaurants Kingsbury London",
    "halal restaurants Kingsbury London",
    "brunch Colindale London",
    "pizza restaurant Colindale London NW9",
    # Brent Cross / Cricklewood
    "restaurants Brent Cross London NW2",
    "cafes Brent Cross London NW2",
    "restaurants Cricklewood London NW2",
    "cafes Cricklewood London NW2",
    "restaurants Cricklewood Broadway London NW2",
    "cafes Cricklewood Broadway London NW2",
    "restaurants Brent Cross Shopping Centre London",
    "Indian restaurants Cricklewood London",
    "brunch Cricklewood London",
    "pizza restaurant Cricklewood London NW2",
    # Kilburn / West Kilburn
    "restaurants Kilburn London NW6",
    "cafes Kilburn London NW6",
    "restaurants Kilburn High Road London NW6",
    "cafes Kilburn High Road London NW6",
    "restaurants West Kilburn London W9",
    "cafes West Kilburn London W9",
    "restaurants Brondesbury London NW6",
    "cafes Brondesbury London NW6",
    "Irish restaurant Kilburn London",
    "brunch Kilburn London",
    "pizza restaurant Kilburn London NW6",
    "gastropub Kilburn London",
    "vegan restaurant Kilburn London",
    # Queen's Park / Kensal Green
    "restaurants Queens Park London NW6",
    "cafes Queens Park London NW6",
    "restaurants Salusbury Road London NW6",
    "cafes Salusbury Road London NW6",
    "restaurants Kensal Rise London NW10",
    "cafes Kensal Rise London NW10",
    "restaurants Chamberlayne Road London NW10",
    "cafes Chamberlayne Road London NW10",
    "restaurants Kensal Green London NW10",
    "cafes Kensal Green London NW10",
    "brunch Queens Park London",
    "brunch Kensal Rise London",
    "pizza restaurant Queens Park London NW6",
    "vegan restaurant Queens Park London",
    "gastropub Queens Park London",
    "wine bar Queens Park London",
    # Maida Vale / Little Venice
    "restaurants Maida Vale London W9",
    "cafes Maida Vale London W9",
    "restaurants Elgin Avenue London W9",
    "cafes Elgin Avenue London W9",
    "restaurants Little Venice London W9",
    "cafes Little Venice London W9",
    "restaurants Warwick Avenue London W9",
    "cafes Warwick Avenue London W9",
    "brunch Maida Vale London",
    "brunch Little Venice London",
    "pizza restaurant Maida Vale London W9",
    "Italian restaurant Maida Vale London",
    "gastropub Maida Vale London",
    # Paddington / Edgware Road W2
    "restaurants Paddington London W2",
    "cafes Paddington London W2",
    "restaurants Praed Street London W2",
    "cafes Praed Street London W2",
    "restaurants Edgware Road London W2",
    "cafes Edgware Road London W2",
    "restaurants Norfolk Square London W2",
    "restaurants Spring Street London W2",
    "Lebanese restaurants Edgware Road London W2",
    "Middle Eastern restaurants Edgware Road London",
    "Egyptian restaurant Edgware Road London",
    "Lebanese cafe Edgware Road London W2",
    "shisha cafe London W2",
    "shisha cafe London NW1",
    "brunch Paddington London",
    "gastropub Paddington London",
    # Bayswater / Westbourne Grove / Notting Hill Gate
    "restaurants Bayswater London W2",
    "cafes Bayswater London W2",
    "restaurants Westbourne Grove London W2",
    "cafes Westbourne Grove London W2",
    "restaurants Queensway London W2",
    "cafes Queensway London W2",
    "restaurants Notting Hill Gate London W11",
    "cafes Notting Hill Gate London W11",
    "Chinese restaurants Bayswater London W2",
    "Lebanese restaurant Westbourne Grove London",
    "brunch Bayswater London",
    "brunch Westbourne Grove London",
    "pizza restaurant Bayswater London W2",
    "Japanese restaurant Westbourne Grove London",
    # Kensal Town / Meanwhile Gardens
    "restaurants Kensal Town London W10",
    "cafes Kensal Town London W10",
    "restaurants Ladbroke Grove London W10",
    "cafes Ladbroke Grove London W10",
    "restaurants Portobello Road London W11",
    "cafes Portobello Road London W11",
    "restaurants Golborne Road London W10",
    "cafes Golborne Road London W10",
    "restaurants Westbourne Park Road London W11",
    "brunch Ladbroke Grove London",
    "brunch Portobello Road London",
    "pizza restaurant Ladbroke Grove London W10",
    "vegan restaurant Portobello Road London",
    "Moroccan restaurant Golborne Road London",
    "Portuguese cafe Golborne Road London",
    # Highgate / Crouch Hill
    "restaurants Highgate London N6",
    "cafes Highgate London N6",
    "restaurants Highgate High Street London N6",
    "cafes Highgate High Street London N6",
    "restaurants South Grove Highgate London N6",
    "restaurants Swain's Lane Highgate London N6",
    "brunch Highgate London",
    "gastropub Highgate London",
    "pizza restaurant Highgate London N6",
    "vegan restaurant Highgate London",
    "wine bar Highgate London",
    # East Barnet / New Southgate / Oakwood
    "restaurants East Barnet London EN4",
    "cafes East Barnet London EN4",
    "restaurants New Southgate London N11",
    "cafes New Southgate London N11",
    "restaurants Oakwood London N14",
    "cafes Oakwood London N14",
    "restaurants Cockfosters London EN4",
    "cafes Cockfosters London EN4",
    "gastropub Oakwood London",
    "pizza restaurant New Southgate London N11",
    # Enfield Town (London Borough)
    "restaurants Enfield Town London EN1",
    "cafes Enfield Town London EN1",
    "restaurants Church Street Enfield London EN1",
    "cafes Church Street Enfield London EN1",
    "restaurants Enfield Chase London EN2",
    "Indian restaurants Enfield London",
    "Turkish restaurants Enfield London",
    "brunch Enfield London",
    "pizza restaurant Enfield London EN1",
    "gastropub Enfield London",
]
