"""
Batch 60 – More food business types × London:
Breweries/tap rooms, distilleries, cider/mead/kombucha, smoothie/açaí/matcha bars,
bubble tea/boba/taro, Korean dessert cafes, Japanese cheesecake, crepe/waffle/pancake cafes,
donut/bagel/pretzel/cookie/brownie/cake/cupcake/macaron/churros shops,
gelato artisan, ice cream vans with sites, frozen yogurt
"""

SEARCH_QUERIES = [
    # Breweries with tap rooms
    ("brewery tap room London", "Bar", 50),
    ("craft brewery London", "Bar", 50),
    ("microbrewery London", "Bar", 50),
    ("brewery tap London EC1", "Bar", 35),
    ("brewery tap London SE1", "Bar", 35),
    ("craft brewery tap room London E1", "Bar", 30),
    ("craft brewery tap room London N1", "Bar", 30),
    ("craft brewery tap room London SW11", "Bar", 30),
    ("London brewery tours and taproom", "Bar", 40),
    ("taproom bar London", "Bar", 45),

    # Distilleries
    ("gin distillery London", "Bar", 45),
    ("whisky distillery London", "Bar", 35),
    ("rum distillery London", "Bar", 35),
    ("craft distillery London", "Bar", 40),
    ("distillery bar London", "Bar", 45),
    ("distillery tour London", "Bar", 40),
    ("spirits distillery London E1", "Bar", 30),
    ("spirits distillery London SE1", "Bar", 30),
    ("London gin distillery visit", "Bar", 40),

    # Cider producers / mead makers
    ("cider bar London", "Bar", 40),
    ("craft cider London", "Bar", 35),
    ("cidery London", "Bar", 30),
    ("mead bar London", "Bar", 30),
    ("mead maker London", "Bar", 25),
    ("meadery London", "Bar", 25),

    # Kombucha bars / kefir cafes
    ("kombucha bar London", "Cafe", 35),
    ("kombucha cafe London", "Cafe", 35),
    ("kefir cafe London", "Cafe", 25),
    ("fermented drinks cafe London", "Cafe", 25),
    ("kombucha bar London N1", "Cafe", 20),
    ("kombucha bar London E8", "Cafe", 20),

    # Smoothie bowls / açaí bars
    ("smoothie bowl London", "Cafe", 40),
    ("açaí bar London", "Cafe", 45),
    ("acai bowl London", "Cafe", 45),
    ("acai cafe London", "Cafe", 40),
    ("superfood bowl London", "Cafe", 35),
    ("açaí bowl London Shoreditch", "Cafe", 30),
    ("açaí bowl London Brixton", "Cafe", 25),
    ("acai bar London Notting Hill", "Cafe", 25),
    ("acai bar London Camden", "Cafe", 25),
    ("smoothie bar London", "Cafe", 45),
    ("smoothie bar London W1", "Cafe", 30),
    ("smoothie bar London EC1", "Cafe", 25),

    # Matcha cafes
    ("matcha cafe London", "Cafe", 50),
    ("matcha bar London", "Cafe", 45),
    ("matcha latte London", "Cafe", 40),
    ("matcha cafe London Soho", "Cafe", 30),
    ("matcha cafe London Shoreditch", "Cafe", 30),
    ("matcha cafe London Hackney", "Cafe", 25),
    ("matcha cafe London Notting Hill", "Cafe", 25),
    ("matcha cafe London Covent Garden", "Cafe", 30),

    # Bubble tea / boba / taro
    ("bubble tea London", "Cafe", 55),
    ("boba cafe London", "Cafe", 55),
    ("boba tea shop London", "Cafe", 50),
    ("taro milk tea London", "Cafe", 40),
    ("taro shop London", "Cafe", 35),
    ("bubble tea London Chinatown", "Cafe", 35),
    ("bubble tea London Soho", "Cafe", 30),
    ("bubble tea London Shoreditch", "Cafe", 30),
    ("bubble tea London Camden", "Cafe", 30),
    ("boba shop London Canary Wharf", "Cafe", 25),
    ("boba tea London Stratford", "Cafe", 25),
    ("bubble tea London Croydon", "Cafe", 30),
    ("bubble tea London Ilford", "Cafe", 30),
    ("bubble tea London Harrow", "Cafe", 25),
    ("boba cafe London Wembley", "Cafe", 25),

    # Korean dessert cafes
    ("Korean dessert cafe London", "Cafe", 45),
    ("bingsu London", "Cafe", 35),
    ("Korean shaved ice London", "Cafe", 30),
    ("Korean patbingsu London", "Cafe", 25),
    ("Korean cafe dessert London", "Cafe", 40),
    ("Korean sweet cafe London Soho", "Cafe", 25),
    ("Korean dessert London New Malden", "Cafe", 30),

    # Japanese cheesecake
    ("Japanese cheesecake London", "Cafe", 40),
    ("fluffy cheesecake London", "Cafe", 35),
    ("Japanese souffle cheesecake London", "Cafe", 30),
    ("Japanese bakery London", "Cafe", 45),
    ("Japanese patisserie London", "Cafe", 40),

    # Crepe cafes
    ("crepe cafe London", "Cafe", 50),
    ("creperie London", "Cafe", 50),
    ("French crepes London", "Cafe", 45),
    ("sweet crepes London", "Cafe", 40),
    ("creperie London W1", "Cafe", 30),
    ("creperie London SE1", "Cafe", 25),
    ("crepe restaurant London Covent Garden", "Cafe", 30),
    ("crepe cafe London Notting Hill", "Cafe", 25),
    ("Breton galette London", "Cafe", 35),

    # Waffle cafes
    ("waffle cafe London", "Cafe", 50),
    ("waffle house London", "Cafe", 45),
    ("Belgian waffle London", "Cafe", 40),
    ("waffle bar London", "Cafe", 45),
    ("waffle cafe London Shoreditch", "Cafe", 30),
    ("waffle cafe London Camden", "Cafe", 25),
    ("waffle cafe London Covent Garden", "Cafe", 30),

    # Pancake cafes
    ("pancake cafe London", "Cafe", 50),
    ("pancake restaurant London", "Restaurant", 45),
    ("pancake house London", "Cafe", 45),
    ("American pancakes London", "Cafe", 40),
    ("pancake stack London", "Cafe", 40),
    ("pancake cafe London Soho", "Cafe", 30),
    ("pancake cafe London Brixton", "Cafe", 25),

    # Donut shops
    ("donut shop London", "Cafe", 50),
    ("doughnut shop London", "Cafe", 50),
    ("artisan donuts London", "Cafe", 45),
    ("gourmet doughnuts London", "Cafe", 45),
    ("donut cafe London Soho", "Cafe", 30),
    ("donut shop London Shoreditch", "Cafe", 30),
    ("donut shop London Hackney", "Cafe", 25),
    ("doughnut bar London", "Cafe", 40),

    # Bagel shops
    ("bagel shop London", "Cafe", 50),
    ("bagel bakery London", "Cafe", 45),
    ("bagel cafe London", "Cafe", 40),
    ("London bagel restaurant", "Cafe", 40),
    ("bagel shop London E1", "Cafe", 30),
    ("bagel shop London N16", "Cafe", 25),

    # Pretzel shops
    ("pretzel shop London", "Cafe", 35),
    ("German pretzel London", "Cafe", 30),
    ("artisan pretzel London", "Cafe", 25),

    # Cookie shops
    ("cookie shop London", "Cafe", 50),
    ("gourmet cookies London", "Cafe", 45),
    ("cookie dough London", "Cafe", 45),
    ("fresh cookie shop London", "Cafe", 40),
    ("cookie shop London Covent Garden", "Cafe", 30),
    ("cookie shop London Soho", "Cafe", 30),

    # Brownie shops
    ("brownie shop London", "Cafe", 40),
    ("artisan brownies London", "Cafe", 35),
    ("brownie bakery London", "Cafe", 35),

    # Cake delivery / cake shops
    ("cake shop London", "Cafe", 50),
    ("artisan cake London", "Cafe", 45),
    ("cake delivery London", "Cafe", 50),
    ("bespoke cake London", "Cafe", 45),
    ("celebration cake London", "Cafe", 40),
    ("cake shop London W1", "Cafe", 30),
    ("cake shop London E8", "Cafe", 25),

    # Cupcake shops
    ("cupcake shop London", "Cafe", 50),
    ("cupcake bakery London", "Cafe", 45),
    ("cupcake cafe London", "Cafe", 40),
    ("cupcake shop London Notting Hill", "Cafe", 25),
    ("cupcake shop London Covent Garden", "Cafe", 30),

    # Macaron shops
    ("macaron shop London", "Cafe", 45),
    ("macarons London", "Cafe", 45),
    ("French macaron London", "Cafe", 40),
    ("patisserie macarons London", "Cafe", 40),
    ("macaron shop London W1", "Cafe", 30),

    # Churros
    ("churros London", "Cafe", 45),
    ("churros shop London", "Cafe", 40),
    ("Spanish churros London", "Cafe", 35),
    ("churros cafe London Soho", "Cafe", 25),
    ("churros cart London market", "Cafe", 30),

    # Gelato artisan
    ("artisan gelato London", "Cafe", 50),
    ("gelato shop London", "Cafe", 50),
    ("Italian gelato London", "Cafe", 50),
    ("gelato parlour London", "Cafe", 45),
    ("gelato London W1", "Cafe", 30),
    ("gelato London EC1", "Cafe", 25),
    ("gelato London SE1", "Cafe", 25),

    # Ice cream
    ("ice cream parlour London", "Cafe", 50),
    ("artisan ice cream London", "Cafe", 45),
    ("ice cream shop London", "Cafe", 45),
    ("scooped ice cream London", "Cafe", 40),

    # Frozen yogurt
    ("frozen yogurt London", "Cafe", 50),
    ("froyo London", "Cafe", 45),
    ("frozen yoghurt London", "Cafe", 45),
    ("frozen yogurt bar London W1", "Cafe", 25),
    ("frozen yogurt London Westfield", "Cafe", 30),

    # Additional food business types
    ("poke bowl London", "Restaurant", 50),
    ("poke bowl cafe London", "Cafe", 45),
    ("poke bowl London Shoreditch", "Cafe", 30),
    ("poke bowl London Soho", "Cafe", 30),
    ("poke bowl London EC2", "Cafe", 25),
    ("bao bun restaurant London", "Restaurant", 45),
    ("bao cafe London", "Cafe", 40),
    ("bao buns London Soho", "Restaurant", 30),
    ("bao restaurant London Shoreditch", "Restaurant", 30),
    ("ramen restaurant London", "Restaurant", 55),
    ("ramen bar London", "Restaurant", 55),
    ("ramen London Soho", "Restaurant", 35),
    ("ramen London Shoreditch", "Restaurant", 30),
    ("ramen London Camden", "Restaurant", 30),
    ("pho restaurant London", "Restaurant", 50),
    ("pho London Shoreditch", "Restaurant", 30),
    ("pho cafe London", "Cafe", 40),
    ("dim sum restaurant London", "Restaurant", 55),
    ("dim sum London Chinatown", "Restaurant", 40),
    ("gyoza bar London", "Restaurant", 45),
    ("sushi burrito London", "Restaurant", 40),
    ("sushi roll bar London", "Restaurant", 45),
    ("temaki sushi London", "Restaurant", 35),
    ("omakase London", "Restaurant", 40),
    ("taco restaurant London", "Restaurant", 50),
    ("tacos London", "Restaurant", 50),
    ("Mexican restaurant London E8", "Restaurant", 35),
    ("Mexican restaurant London N1", "Restaurant", 35),
    ("Mexican restaurant London SE15", "Restaurant", 35),
    ("burrito bar London", "Restaurant", 50),
    ("wrap bar London", "Restaurant", 40),
    ("falafel wrap London", "Restaurant", 45),
    ("falafel shop London", "Restaurant", 45),
    ("falafel bar London N1", "Restaurant", 30),
    ("falafel bar London E1", "Restaurant", 30),
    ("shawarma London", "Restaurant", 50),
    ("shawarma shop London E1", "Restaurant", 30),
    ("halal restaurant London E1", "Restaurant", 50),
    ("halal restaurant London Whitechapel", "Restaurant", 50),
    ("halal restaurant London E7", "Restaurant", 45),
    ("kosher restaurant London NW11", "Restaurant", 40),
    ("kosher cafe London NW4", "Restaurant", 35),
    ("vegan restaurant London", "Restaurant", 55),
    ("vegan cafe London", "Cafe", 55),
    ("vegan cafe London E8", "Cafe", 35),
    ("vegan cafe London N1", "Cafe", 35),
    ("vegan cafe London SE15", "Cafe", 30),
    ("plant based restaurant London", "Restaurant", 50),
    ("raw food cafe London", "Cafe", 35),
    ("health food cafe London", "Cafe", 45),
    ("organic cafe London", "Cafe", 45),
    ("organic restaurant London", "Restaurant", 45),
    ("farm to table London", "Restaurant", 45),
    ("nose to tail restaurant London", "Restaurant", 40),
    ("supper club London", "Restaurant", 40),
    ("pop up restaurant London", "Restaurant", 40),
    ("food truck London", "Street Food", 50),
    ("street food stall London", "Street Food", 50),
    ("street food market London", "Street Food", 55),
    ("food hall London", "Restaurant", 50),
    ("food court London", "Restaurant", 50),
    ("dark kitchen London", "Restaurant", 40),
    ("ghost kitchen London", "Restaurant", 35),
    ("cloud kitchen London", "Restaurant", 35),
    ("delivery only restaurant London", "Restaurant", 40),

    # More niche cafes and drink concepts
    ("coffee roaster cafe London", "Cafe", 50),
    ("specialty coffee roaster London", "Cafe", 50),
    ("coffee roastery London", "Cafe", 45),
    ("London coffee roaster", "Cafe", 50),
    ("espresso bar London", "Cafe", 50),
    ("flat white cafe London", "Cafe", 45),
    ("filter coffee bar London", "Cafe", 45),
    ("pourover coffee London", "Cafe", 40),
    ("cold brew coffee London", "Cafe", 40),
    ("nitro coffee bar London", "Cafe", 35),
    ("coffee tasting London", "Cafe", 35),
    ("coffee cupping London", "Cafe", 30),
    ("tea room London", "Cafe", 50),
    ("afternoon tea London", "Cafe", 60),
    ("afternoon tea London W1", "Cafe", 40),
    ("afternoon tea London SW1", "Cafe", 40),
    ("afternoon tea London WC2", "Cafe", 35),
    ("afternoon tea London SE1", "Cafe", 30),
    ("afternoon tea London NW1", "Cafe", 30),
    ("high tea London", "Cafe", 50),
    ("cream tea London", "Cafe", 40),
    ("champagne afternoon tea London", "Cafe", 40),
    ("vegan afternoon tea London", "Cafe", 35),
    ("gin afternoon tea London", "Cafe", 30),
    ("Japanese tea ceremony London", "Cafe", 25),
    ("chai tea cafe London", "Cafe", 35),
    ("herbal tea house London", "Cafe", 30),
    ("juice bar London", "Cafe", 45),
    ("cold pressed juice London", "Cafe", 40),
    ("wellness cafe London", "Cafe", 40),
    ("superfood cafe London", "Cafe", 40),
    ("wheatgrass bar London", "Cafe", 30),
    ("protein shake bar London", "Cafe", 35),
    ("sports nutrition cafe London", "Cafe", 30),
    ("breakfast restaurant London", "Restaurant", 55),
    ("all day breakfast London", "Restaurant", 50),
    ("full English breakfast London", "Restaurant", 50),
    ("brunch restaurant London", "Restaurant", 60),
    ("brunch London E8", "Restaurant", 35),
    ("brunch London SE15", "Restaurant", 35),
    ("brunch London SW9", "Restaurant", 35),
    ("brunch London N1", "Restaurant", 35),
    ("brunch London W1", "Restaurant", 40),
    ("bottomless brunch London", "Restaurant", 55),
    ("bottomless brunch London SW4", "Restaurant", 30),
    ("bottomless brunch London E1", "Restaurant", 30),
    ("bottomless brunch London SE1", "Restaurant", 30),
    ("late night food London", "Restaurant", 50),
    ("24 hour restaurant London", "Restaurant", 40),
    ("midnight snack London", "Restaurant", 35),
    ("late night kebab London", "Restaurant", 45),
    ("supper club London", "Restaurant", 40),
    ("set menu London restaurant", "Restaurant", 50),
    ("tasting menu London", "Restaurant", 50),
    ("prix fixe London restaurant", "Restaurant", 45),
]
