"""
Batch 68 - Middle Eastern, African, Caribbean, Latin American cuisine x London
Covers: Turkish, Lebanese, Persian/Iranian, Egyptian, Moroccan, Ethiopian/Eritrean,
West African, Caribbean/Jamaican, Mexican, Brazilian across London.
"""

SEARCH_QUERIES = [
    # Turkish restaurants x London postcodes
    "Turkish restaurants E1 London",
    "Turkish restaurants E2 London",
    "Turkish restaurants E5 London",
    "Turkish restaurants E8 London",
    "Turkish restaurants N1 London",
    "Turkish restaurants N4 London",
    "Turkish restaurants N16 London",
    "Turkish restaurants N8 London",
    "Turkish restaurants N15 London",
    "Turkish restaurants SE1 London",
    "Turkish restaurants SE5 London",
    "Turkish restaurants SE15 London",
    "Turkish restaurants SW9 London",
    "Turkish restaurants W1 London",
    "Turkish restaurants WC2 London",
    "Turkish restaurants EC1 London",
    "Turkish restaurants NW1 London",
    "Turkish restaurants NW6 London",
    "Turkish restaurants NW10 London",
    # Turkish x areas
    "Turkish restaurants Dalston London",
    "Turkish restaurants Stoke Newington London",
    "Turkish restaurants Hackney London",
    "Turkish restaurants Kingsland Road London",
    "Turkish restaurants Green Lanes London",
    "Turkish restaurants Haringey London",
    "Turkish restaurants Tottenham London",
    "Turkish restaurants Wood Green London",
    "Turkish restaurants Harringay London",
    "Turkish restaurants Brixton London",
    "Turkish restaurants Shoreditch London",
    "Turkish restaurants Islington London",
    # Turkish kebab / grill
    "Turkish grill London E8",
    "Turkish grill London N4",
    "Turkish grill London N16",
    "Turkish grill London N8",
    "Turkish grill London SE1",
    "Turkish grill London SW9",
    "Turkish grill London W1",
    "Turkish grill London NW1",
    "Turkish grill Dalston London",
    "Turkish grill Stoke Newington London",
    "Turkish grill Green Lanes London",
    "kebab restaurant London E1",
    "kebab restaurant London E8",
    "kebab restaurant London N4",
    "kebab restaurant London N16",
    "kebab restaurant London SE1",
    "kebab restaurant London SW9",
    "kebab restaurant London W1",
    "kebab restaurant London NW1",
    "mangal London",
    "ocakbasi London",
    "ocakbasi Dalston London",
    "ocakbasi Green Lanes London",
    "ocakbasi Stoke Newington London",
    # Lebanese restaurants x London
    "Lebanese restaurants E1 London",
    "Lebanese restaurants N1 London",
    "Lebanese restaurants N4 London",
    "Lebanese restaurants SE1 London",
    "Lebanese restaurants SW1 London",
    "Lebanese restaurants SW3 London",
    "Lebanese restaurants SW7 London",
    "Lebanese restaurants W1 London",
    "Lebanese restaurants W2 London",
    "Lebanese restaurants WC2 London",
    "Lebanese restaurants EC1 London",
    "Lebanese restaurants NW1 London",
    "Lebanese restaurants NW3 London",
    "Lebanese restaurants NW6 London",
    "Lebanese restaurant Kensington London",
    "Lebanese restaurant Mayfair London",
    "Lebanese restaurant Knightsbridge London",
    "Lebanese restaurant Hammersmith London",
    "Lebanese restaurant Edgware Road London",
    "Lebanese restaurant Westbourne Grove London",
    "Lebanese cafe London W2",
    "Lebanese cafe London NW6",
    "Lebanese cafe London NW3",
    # Persian / Iranian restaurants x London
    "Persian restaurants London W1",
    "Persian restaurants London W2",
    "Persian restaurants London W4",
    "Persian restaurants London W14",
    "Persian restaurants London SW7",
    "Persian restaurants London SW3",
    "Persian restaurants London NW1",
    "Persian restaurants London NW3",
    "Persian restaurants London NW6",
    "Persian restaurants London N1",
    "Persian restaurants London EC1",
    "Persian restaurant Kensington London",
    "Persian restaurant Hammersmith London",
    "Persian restaurant Edgware Road London",
    "Persian restaurant Golders Green London",
    "Iranian restaurant London W14",
    "Iranian restaurant London W4",
    "Iranian restaurant London W1",
    "Iranian restaurant London NW3",
    # Middle Eastern restaurants x London
    "Middle Eastern restaurants E1 London",
    "Middle Eastern restaurants N1 London",
    "Middle Eastern restaurants SE1 London",
    "Middle Eastern restaurants W1 London",
    "Middle Eastern restaurants W2 London",
    "Middle Eastern restaurants WC2 London",
    "Middle Eastern restaurants EC1 London",
    "Middle Eastern restaurants NW1 London",
    "Middle Eastern restaurants NW3 London",
    "Middle Eastern restaurants SW1 London",
    "Middle Eastern restaurants SW3 London",
    "Middle Eastern restaurants Shoreditch London",
    "Middle Eastern restaurants Brixton London",
    "Middle Eastern restaurants Camden London",
    "Middle Eastern restaurants Hackney London",
    # Moroccan / North African restaurants x London
    "Moroccan restaurants London E1",
    "Moroccan restaurants London N1",
    "Moroccan restaurants London SE1",
    "Moroccan restaurants London SW9",
    "Moroccan restaurants London W1",
    "Moroccan restaurants London WC2",
    "Moroccan restaurants London NW1",
    "Moroccan restaurants London NW3",
    "Moroccan restaurant Brixton London",
    "Moroccan restaurant Hackney London",
    "Moroccan restaurant Dalston London",
    "Moroccan restaurant Notting Hill London",
    "Moroccan restaurant Camden London",
    "Moroccan restaurant Shepherds Bush London",
    "North African restaurant London W1",
    "North African restaurant London SE1",
    "North African restaurant London N1",
    # Ethiopian / Eritrean restaurants x London
    "Ethiopian restaurants London E1",
    "Ethiopian restaurants London N1",
    "Ethiopian restaurants London SE1",
    "Ethiopian restaurants London SW9",
    "Ethiopian restaurants London W1",
    "Ethiopian restaurants London WC2",
    "Ethiopian restaurants London NW1",
    "Ethiopian restaurant Brixton London",
    "Ethiopian restaurant Streatham London",
    "Ethiopian restaurant Hackney London",
    "Ethiopian restaurant Dalston London",
    "Ethiopian restaurant Camden London",
    "Ethiopian restaurant Peckham London",
    "Eritrean restaurant London SE1",
    "Eritrean restaurant London SW9",
    "Eritrean restaurant London N1",
    "Eritrean restaurant London NW1",
    "East African restaurant London SE1",
    "East African restaurant London SW9",
    "East African restaurant London N1",
    # West African restaurants x London
    "West African restaurants London SE1",
    "West African restaurants London SE15",
    "West African restaurants London SE5",
    "West African restaurants London SW9",
    "West African restaurants London N1",
    "West African restaurants London NW10",
    "West African restaurants London E6",
    "West African restaurants London E13",
    "Nigerian restaurant London SE1",
    "Nigerian restaurant London SW9",
    "Nigerian restaurant London N1",
    "Nigerian restaurant London NW10",
    "Nigerian restaurant Peckham London",
    "Nigerian restaurant Brixton London",
    "Nigerian restaurant Hackney London",
    "Nigerian restaurant Tottenham London",
    "Ghanaian restaurant London SE1",
    "Ghanaian restaurant London SW9",
    "Ghanaian restaurant London N1",
    "Ghanaian restaurant Peckham London",
    "Ghanaian restaurant Brixton London",
    "African restaurant London SE15",
    "African restaurant London SW9",
    "African restaurant London N1",
    "African restaurant London NW10",
    "African restaurant Peckham London",
    "African restaurant Brixton London",
    # Caribbean restaurants x London
    "Caribbean restaurants London E1",
    "Caribbean restaurants London SE1",
    "Caribbean restaurants London SE15",
    "Caribbean restaurants London SW9",
    "Caribbean restaurants London W1",
    "Caribbean restaurants London WC2",
    "Caribbean restaurants London NW1",
    "Caribbean restaurants London NW10",
    "Caribbean restaurants London N1",
    "Caribbean restaurants Brixton London",
    "Caribbean restaurants Notting Hill London",
    "Caribbean restaurants Hackney London",
    "Caribbean restaurants Peckham London",
    "Caribbean restaurants Tottenham London",
    "Caribbean restaurants Dalston London",
    "Jamaican restaurant London SE1",
    "Jamaican restaurant London SW9",
    "Jamaican restaurant London N1",
    "Jamaican restaurant London NW1",
    "Jamaican restaurant Brixton London",
    "Jamaican restaurant Notting Hill London",
    "Jamaican restaurant Hackney London",
    "Jamaican restaurant Dalston London",
    "Jamaican restaurant Peckham London",
    "jerk chicken London SE1",
    "jerk chicken London SW9",
    "jerk chicken London N1",
    "jerk chicken London E1",
    "jerk chicken Brixton London",
    "jerk chicken Notting Hill London",
    "jerk chicken Hackney London",
    # Mexican restaurants x London
    "Mexican restaurants London E1",
    "Mexican restaurants London N1",
    "Mexican restaurants London SE1",
    "Mexican restaurants London SW4",
    "Mexican restaurants London SW9",
    "Mexican restaurants London SW11",
    "Mexican restaurants London W1",
    "Mexican restaurants London W11",
    "Mexican restaurants London WC2",
    "Mexican restaurants London EC1",
    "Mexican restaurants London NW1",
    "Mexican restaurants Brixton London",
    "Mexican restaurants Shoreditch London",
    "Mexican restaurants Dalston London",
    "Mexican restaurants Hackney London",
    "Mexican restaurants Notting Hill London",
    "Mexican restaurants Clapham London",
    "Mexican restaurants Camden London",
    "taqueria London W1",
    "taqueria London WC2",
    "taqueria London E1",
    "taqueria London SE1",
    "taqueria London N1",
    # Brazilian restaurants x London
    "Brazilian restaurants London E1",
    "Brazilian restaurants London N1",
    "Brazilian restaurants London SE1",
    "Brazilian restaurants London SW1",
    "Brazilian restaurants London SW9",
    "Brazilian restaurants London W1",
    "Brazilian restaurants London WC2",
    "Brazilian restaurants London EC1",
    "Brazilian restaurants London NW1",
    "Brazilian restaurants Shoreditch London",
    "Brazilian restaurants Brixton London",
    "Brazilian restaurants Hackney London",
    "churrascaria London W1",
    "churrascaria London SW1",
    "churrascaria London SE1",
    "churrascaria London NW1",
]
