"""
Batch 73 - South London neighborhoods: Peckham, Brixton, Bermondsey, New Cross,
Lewisham, Catford, Forest Hill, Sydenham, Crystal Palace, Streatham, Tooting,
Balham, Norbury, Mitcham, Croydon (London Borough).
"""

SEARCH_QUERIES = [
    # Peckham
    "restaurants Peckham London SE15",
    "cafes Peckham London SE15",
    "restaurants Peckham High Street London SE15",
    "cafes Peckham High Street London SE15",
    "restaurants Rye Lane Peckham London SE15",
    "cafes Rye Lane Peckham London SE15",
    "restaurants Peckham Rye London SE15",
    "cafes Peckham Rye London SE15",
    "restaurants Bellenden Road Peckham London SE15",
    "cafes Bellenden Road Peckham London SE15",
    "restaurants Nunhead London SE15",
    "cafes Nunhead London SE15",
    "vegan restaurants Peckham London",
    "brunch Peckham London",
    "wine bar Peckham London",
    "natural wine Peckham London",
    "West African restaurant Peckham London",
    "Nigerian restaurant Peckham London",
    "Ghanaian restaurant Peckham London",
    "pizza restaurant Peckham London SE15",
    "Korean restaurant Peckham London",
    # New Cross / New Cross Gate
    "restaurants New Cross London SE14",
    "cafes New Cross London SE14",
    "restaurants New Cross Road London SE14",
    "cafes New Cross Road London SE14",
    "restaurants Telegraph Hill London SE14",
    "brunch New Cross London",
    "vegan restaurant New Cross London",
    "pizza restaurant New Cross London SE14",
    "gastropub New Cross London",
    # Deptford
    "restaurants Deptford London SE8",
    "cafes Deptford London SE8",
    "restaurants Deptford High Street London SE8",
    "cafes Deptford High Street London SE8",
    "restaurants Deptford Market Yard London SE8",
    "brunch Deptford London",
    "vegan restaurant Deptford London",
    "pizza restaurant Deptford London SE8",
    "street food Deptford London",
    # Lewisham / Catford
    "restaurants Lewisham London SE13",
    "cafes Lewisham London SE13",
    "restaurants Lewisham High Street London SE13",
    "cafes Lewisham High Street London SE13",
    "restaurants Catford London SE6",
    "cafes Catford London SE6",
    "restaurants Catford Broadway London SE6",
    "cafes Catford Broadway London SE6",
    "Indian restaurant Lewisham London",
    "Chinese restaurant Lewisham London",
    "brunch Lewisham London",
    "pizza restaurant Lewisham London SE13",
    "pizza restaurant Catford London SE6",
    # Forest Hill / Sydenham
    "restaurants Forest Hill London SE23",
    "cafes Forest Hill London SE23",
    "restaurants Honor Oak London SE23",
    "cafes Honor Oak London SE23",
    "restaurants Sydenham London SE26",
    "cafes Sydenham London SE26",
    "brunch Forest Hill London",
    "gastropub Forest Hill London",
    "pizza restaurant Forest Hill London SE23",
    "vegan restaurant Forest Hill London",
    # Crystal Palace
    "restaurants Crystal Palace London SE19",
    "cafes Crystal Palace London SE19",
    "restaurants Crystal Palace Parade London SE19",
    "cafes Crystal Palace Parade London SE19",
    "restaurants Anerley Road London SE19",
    "brunch Crystal Palace London",
    "vegan restaurant Crystal Palace London",
    "gastropub Crystal Palace London",
    "pizza restaurant Crystal Palace London SE19",
    "wine bar Crystal Palace London",
    # Streatham / Streatham Hill
    "restaurants Streatham London SW16",
    "cafes Streatham London SW16",
    "restaurants Streatham High Road London SW16",
    "cafes Streatham High Road London SW16",
    "restaurants Streatham Hill London SW2",
    "cafes Streatham Hill London SW2",
    "restaurants Streatham Common London SW16",
    "Indian restaurant Streatham London",
    "Sri Lankan restaurant Streatham London",
    "brunch Streatham London",
    "pizza restaurant Streatham London SW16",
    "Ethiopian restaurant Streatham London",
    "Caribbean restaurant Streatham London",
    # Tooting / Tooting Broadway
    "restaurants Tooting London SW17",
    "cafes Tooting London SW17",
    "restaurants Tooting Broadway London SW17",
    "cafes Tooting Broadway London SW17",
    "restaurants Upper Tooting Road London SW17",
    "cafes Upper Tooting Road London SW17",
    "restaurants Tooting Market London SW17",
    "cafes Tooting Bec London SW17",
    "Indian restaurants Tooting London SW17",
    "Pakistani restaurants Tooting London",
    "Sri Lankan restaurants Tooting London",
    "halal restaurants Tooting London",
    "brunch Tooting London",
    "pizza restaurant Tooting London SW17",
    "vegan restaurant Tooting London",
    "street food Tooting London",
    "South Asian restaurant Tooting London",
    # Balham
    "restaurants Balham London SW12",
    "cafes Balham London SW12",
    "restaurants Balham High Road London SW12",
    "cafes Balham High Road London SW12",
    "restaurants Bedford Hill London SW12",
    "brunch Balham London",
    "gastropub Balham London",
    "pizza restaurant Balham London SW12",
    "vegan restaurant Balham London",
    "Italian restaurant Balham London",
    # Norbury / Thornton Heath
    "restaurants Norbury London SW16",
    "cafes Norbury London SW16",
    "restaurants Thornton Heath London CR7",
    "cafes Thornton Heath London CR7",
    "Indian restaurants Norbury London",
    "Indian restaurants Thornton Heath London",
    "Sri Lankan restaurants Norbury London",
    "halal restaurants Norbury London",
    # Croydon (London Borough)
    "restaurants Croydon London CR0",
    "cafes Croydon London CR0",
    "restaurants Croydon High Street London CR0",
    "cafes Croydon High Street London CR0",
    "restaurants South Croydon London CR2",
    "cafes South Croydon London CR2",
    "restaurants East Croydon London CR0",
    "cafes East Croydon London CR0",
    "restaurants West Croydon London CR0",
    "cafes West Croydon London CR0",
    "Indian restaurants Croydon London",
    "Sri Lankan restaurants Croydon London",
    "brunch Croydon London",
    "pizza restaurant Croydon London CR0",
    "vegan restaurant Croydon London",
    "Korean restaurant Croydon London",
    "gastropub Croydon London",
    # Mitcham
    "restaurants Mitcham London CR4",
    "cafes Mitcham London CR4",
    "Indian restaurants Mitcham London",
    "halal restaurants Mitcham London",
    # Sutton (London Borough)
    "restaurants Sutton London SM1",
    "cafes Sutton London SM1",
    "restaurants Sutton High Street London SM1",
    "Indian restaurant Sutton London",
    "pizza restaurant Sutton London SM1",
    "brunch Sutton London",
    "gastropub Sutton London",
    # Morden / Merton
    "restaurants Morden London SM4",
    "cafes Morden London SM4",
    "restaurants Wimbledon Chase London SW20",
    "cafes Merton Park London SW19",
    "gastropub Morden London",
    "pizza restaurant Morden London SM4",
    # Wallington / Carshalton (London Borough)
    "restaurants Wallington London SM6",
    "cafes Wallington London SM6",
    "restaurants Carshalton London SM5",
    "cafes Carshalton London SM5",
    "gastropub Wallington London",
    "pizza restaurant Carshalton London SM5",
    # Woolwich / Abbey Wood / Thamesmead
    "restaurants Woolwich London SE18",
    "cafes Woolwich London SE18",
    "restaurants Woolwich High Street London SE18",
    "cafes Woolwich High Street London SE18",
    "restaurants Woolwich Arsenal London SE18",
    "restaurants Abbey Wood London SE2",
    "cafes Abbey Wood London SE2",
    "restaurants Thamesmead London SE28",
    "Indian restaurants Woolwich London",
    "halal restaurants Woolwich London",
    "brunch Woolwich London",
    "pizza restaurant Woolwich London SE18",
    # Plumstead / Charlton / Kidbrooke
    "restaurants Plumstead London SE18",
    "cafes Plumstead London SE18",
    "restaurants Charlton London SE7",
    "cafes Charlton London SE7",
    "restaurants Kidbrooke London SE3",
    "cafes Kidbrooke London SE3",
    "gastropub Charlton London",
    "pizza restaurant Charlton London SE7",
    # Eltham / Mottingham
    "restaurants Eltham London SE9",
    "cafes Eltham London SE9",
    "restaurants Eltham High Street London SE9",
    "cafes Eltham High Street London SE9",
    "restaurants Mottingham London SE9",
    "brunch Eltham London",
    "pizza restaurant Eltham London SE9",
    "gastropub Eltham London",
    # Sidcup / Bexley (London Borough)
    "restaurants Sidcup London DA14",
    "cafes Sidcup London DA14",
    "restaurants Bexleyheath London DA7",
    "cafes Bexleyheath London DA7",
    "restaurants Welling London DA16",
    "cafes Erith London DA8",
    "gastropub Sidcup London",
    "pizza restaurant Bexleyheath London DA7",
    # Orpington / Bromley (London Borough)
    "restaurants Bromley London BR1",
    "cafes Bromley London BR1",
    "restaurants Bromley High Street London BR1",
    "cafes Bromley High Street London BR1",
    "restaurants Orpington London BR6",
    "cafes Orpington London BR6",
    "restaurants Beckenham London BR3",
    "cafes Beckenham London BR3",
    "restaurants Penge London SE20",
    "cafes Penge London SE20",
    "brunch Bromley London",
    "pizza restaurant Bromley London BR1",
    "gastropub Bromley London",
    "vegan restaurant Bromley London",
    # Norwood / West Norwood / Tulse Hill
    "restaurants West Norwood London SE27",
    "cafes West Norwood London SE27",
    "restaurants Tulse Hill London SE24",
    "cafes Tulse Hill London SE24",
    "restaurants Gipsy Hill London SE19",
    "cafes Gipsy Hill London SE19",
    "brunch West Norwood London",
    "vegan restaurant West Norwood London",
    "pizza restaurant Tulse Hill London SE24",
    # Herne Hill / Denmark Hill
    "restaurants Herne Hill London SE24",
    "cafes Herne Hill London SE24",
    "restaurants Denmark Hill London SE5",
    "cafes Denmark Hill London SE5",
    "restaurants Half Moon Lane London SE24",
    "brunch Herne Hill London",
    "gastropub Herne Hill London",
    "vegan restaurant Herne Hill London",
    "wine bar Herne Hill London",
]
