"""
Batch 57 – Systematic N/NW streets: N4 Finsbury Park, N5 Highbury, N6 Highgate, N7 Holloway,
N8 Hornsey/Crouch End, N10 Muswell Hill, N11 New Southgate/Bounds Green, N12 Finchley,
N13 Palmers Green, N15 Seven Sisters, N17 Tottenham, N19 Archway/Upper Holloway, N22 Wood Green,
NW2 Cricklewood, NW4 Hendon, NW6 Kilburn/West Hampstead, NW9 Colindale/Kingsbury,
NW10 Harlesden, NW11 Golders Green
"""

SEARCH_QUERIES = [
    # N4 – Finsbury Park more streets
    ("restaurants Stroud Green Road London N4", "Restaurant", 55),
    ("cafes Stroud Green Road London N4", "Cafe", 35),
    ("restaurants Blackstock Road London N4", "Restaurant", 55),
    ("cafes Blackstock Road London N4", "Cafe", 35),
    ("restaurants Seven Sisters Road London N4", "Restaurant", 55),
    ("cafes Seven Sisters Road London N4", "Cafe", 35),
    ("restaurants Fonthill Road London N4", "Restaurant", 45),
    ("cafes Fonthill Road London N4", "Cafe", 25),
    ("restaurants Finsbury Park Road London N4", "Restaurant", 50),
    ("cafes Finsbury Park Road London N4", "Cafe", 30),
    ("restaurants Brownswood Road London N4", "Restaurant", 40),
    ("cafes Brownswood Road London N4", "Cafe", 20),
    ("restaurants Woodstock Road London N4", "Restaurant", 40),
    ("cafes Woodstock Road London N4", "Cafe", 20),

    # N5 – Highbury more streets
    ("restaurants Highbury Park London N5", "Restaurant", 50),
    ("cafes Highbury Park London N5", "Cafe", 30),
    ("restaurants Highbury Barn London N5", "Restaurant", 50),
    ("cafes Highbury Barn London N5", "Cafe", 30),
    ("restaurants Fieldway Crescent London N5", "Restaurant", 35),
    ("cafes Fieldway Crescent London N5", "Cafe", 20),
    ("restaurants Aberdeen Park London N5", "Restaurant", 35),
    ("cafes Aberdeen Park London N5", "Cafe", 20),
    ("restaurants Highbury Corner London N5", "Restaurant", 50),
    ("cafes Highbury Corner London N5", "Cafe", 30),
    ("restaurants Ronalds Road London N5", "Restaurant", 35),
    ("cafes Ronalds Road London N5", "Cafe", 20),

    # N6 – Highgate more streets
    ("restaurants Highgate High Street London N6", "Restaurant", 55),
    ("cafes Highgate High Street London N6", "Cafe", 35),
    ("restaurants Highgate Village London N6", "Restaurant", 55),
    ("cafes Highgate Village London N6", "Cafe", 35),
    ("restaurants Archway Road London N6", "Restaurant", 50),
    ("cafes Archway Road London N6", "Cafe", 30),
    ("restaurants North Hill London N6", "Restaurant", 45),
    ("cafes North Hill London N6", "Cafe", 25),
    ("restaurants South Grove Highgate London N6", "Restaurant", 40),
    ("cafes South Grove Highgate London N6", "Cafe", 20),
    ("restaurants West Hill London N6", "Restaurant", 45),
    ("cafes West Hill London N6", "Cafe", 25),
    ("restaurants Swain's Lane London N6", "Restaurant", 40),
    ("cafes Swain's Lane London N6", "Cafe", 20),

    # N7 – Holloway more streets
    ("restaurants Holloway Road London N7", "Restaurant", 55),
    ("cafes Holloway Road London N7", "Cafe", 35),
    ("restaurants Junction Road London N7", "Restaurant", 50),
    ("cafes Junction Road London N7", "Cafe", 30),
    ("restaurants Parkhurst Road London N7", "Restaurant", 45),
    ("cafes Parkhurst Road London N7", "Cafe", 25),
    ("restaurants Caledonian Road London N7", "Restaurant", 55),
    ("cafes Caledonian Road London N7", "Cafe", 35),
    ("restaurants Camden Road London N7", "Restaurant", 55),
    ("cafes Camden Road London N7", "Cafe", 35),
    ("restaurants Hertslet Road London N7", "Restaurant", 35),
    ("cafes Hertslet Road London N7", "Cafe", 20),
    ("restaurants Tufnell Park Road London N7", "Restaurant", 45),
    ("cafes Tufnell Park Road London N7", "Cafe", 25),

    # N8 – Hornsey / Crouch End more streets
    ("restaurants Crouch End Broadway London N8", "Restaurant", 55),
    ("cafes Crouch End Broadway London N8", "Cafe", 35),
    ("restaurants The Broadway Crouch End London N8", "Restaurant", 55),
    ("cafes The Broadway Crouch End London N8", "Cafe", 35),
    ("restaurants Hornsey High Street London N8", "Restaurant", 50),
    ("cafes Hornsey High Street London N8", "Cafe", 30),
    ("restaurants Tottenham Lane London N8", "Restaurant", 45),
    ("cafes Tottenham Lane London N8", "Cafe", 25),
    ("restaurants Middle Lane London N8", "Restaurant", 45),
    ("cafes Middle Lane London N8", "Cafe", 25),
    ("restaurants Park Road Crouch End London N8", "Restaurant", 40),
    ("cafes Park Road Crouch End London N8", "Cafe", 20),
    ("restaurants Topsfield Parade London N8", "Restaurant", 45),
    ("cafes Topsfield Parade London N8", "Cafe", 25),

    # N10 – Muswell Hill more streets
    ("restaurants Muswell Hill Broadway London N10", "Restaurant", 55),
    ("cafes Muswell Hill Broadway London N10", "Cafe", 35),
    ("restaurants Muswell Hill Road London N10", "Restaurant", 50),
    ("cafes Muswell Hill Road London N10", "Cafe", 30),
    ("restaurants Colney Hatch Lane London N10", "Restaurant", 45),
    ("cafes Colney Hatch Lane London N10", "Cafe", 25),
    ("restaurants Alexandra Park Road London N10", "Restaurant", 40),
    ("cafes Alexandra Park Road London N10", "Cafe", 20),
    ("restaurants Pages Lane London N10", "Restaurant", 35),
    ("cafes Pages Lane London N10", "Cafe", 20),

    # N11 – New Southgate / Bounds Green more streets
    ("restaurants New Southgate High Road London N11", "Restaurant", 50),
    ("cafes New Southgate High Road London N11", "Cafe", 30),
    ("restaurants Bounds Green Road London N11", "Restaurant", 50),
    ("cafes Bounds Green Road London N11", "Cafe", 30),
    ("restaurants Friern Barnet Road London N11", "Restaurant", 45),
    ("cafes Friern Barnet Road London N11", "Cafe", 25),
    ("restaurants Colney Hatch Lane London N11", "Restaurant", 45),
    ("cafes Colney Hatch Lane London N11", "Cafe", 25),
    ("restaurants Station Road New Southgate London N11", "Restaurant", 40),
    ("cafes Station Road New Southgate London N11", "Cafe", 20),

    # N12 – Finchley more streets
    ("restaurants High Road Finchley London N12", "Restaurant", 55),
    ("cafes High Road Finchley London N12", "Cafe", 35),
    ("restaurants Ballards Lane London N12", "Restaurant", 50),
    ("cafes Ballards Lane London N12", "Cafe", 30),
    ("restaurants North Finchley London N12", "Restaurant", 50),
    ("cafes North Finchley London N12", "Cafe", 30),
    ("restaurants Woodhouse Road London N12", "Restaurant", 40),
    ("cafes Woodhouse Road London N12", "Cafe", 20),
    ("restaurants Nether Street London N12", "Restaurant", 35),
    ("cafes Nether Street London N12", "Cafe", 20),

    # N13 – Palmers Green more streets
    ("restaurants Green Lanes Palmers Green London N13", "Restaurant", 55),
    ("cafes Green Lanes Palmers Green London N13", "Cafe", 35),
    ("restaurants Aldermans Hill London N13", "Restaurant", 45),
    ("cafes Aldermans Hill London N13", "Cafe", 25),
    ("restaurants Hedge Lane London N13", "Restaurant", 35),
    ("cafes Hedge Lane London N13", "Cafe", 20),
    ("restaurants Fox Lane London N13", "Restaurant", 40),
    ("cafes Fox Lane London N13", "Cafe", 20),
    ("restaurants Broomfield Lane London N13", "Restaurant", 35),
    ("cafes Broomfield Lane London N13", "Cafe", 20),

    # N15 – Seven Sisters more streets
    ("restaurants West Green Road London N15", "Restaurant", 55),
    ("cafes West Green Road London N15", "Cafe", 35),
    ("restaurants Seven Sisters Road London N15", "Restaurant", 55),
    ("cafes Seven Sisters Road London N15", "Cafe", 35),
    ("restaurants Philip Lane London N15", "Restaurant", 45),
    ("cafes Philip Lane London N15", "Cafe", 25),
    ("restaurants Downhills Park Road London N15", "Restaurant", 35),
    ("cafes Downhills Park Road London N15", "Cafe", 20),
    ("restaurants Broad Lane London N15", "Restaurant", 40),
    ("cafes Broad Lane London N15", "Cafe", 20),
    ("restaurants High Road Tottenham London N15", "Restaurant", 50),
    ("cafes High Road Tottenham London N15", "Cafe", 30),

    # N17 – Tottenham more streets
    ("restaurants High Road Tottenham London N17", "Restaurant", 55),
    ("cafes High Road Tottenham London N17", "Cafe", 35),
    ("restaurants Tottenham High Road London N17", "Restaurant", 55),
    ("cafes Tottenham High Road London N17", "Cafe", 35),
    ("restaurants Bruce Grove London N17", "Restaurant", 50),
    ("cafes Bruce Grove London N17", "Cafe", 30),
    ("restaurants White Hart Lane London N17", "Restaurant", 50),
    ("cafes White Hart Lane London N17", "Cafe", 30),
    ("restaurants Lordship Lane Tottenham London N17", "Restaurant", 45),
    ("cafes Lordship Lane Tottenham London N17", "Cafe", 25),
    ("restaurants Fore Street London N17", "Restaurant", 45),
    ("cafes Fore Street London N17", "Cafe", 25),
    ("restaurants Marsh Lane London N17", "Restaurant", 35),
    ("cafes Marsh Lane London N17", "Cafe", 20),

    # N19 – Archway / Upper Holloway more streets
    ("restaurants Junction Road London N19", "Restaurant", 50),
    ("cafes Junction Road London N19", "Cafe", 30),
    ("restaurants Archway Road London N19", "Restaurant", 50),
    ("cafes Archway Road London N19", "Cafe", 30),
    ("restaurants Holloway Road London N19", "Restaurant", 55),
    ("cafes Holloway Road London N19", "Cafe", 35),
    ("restaurants Brecknock Road London N19", "Restaurant", 40),
    ("cafes Brecknock Road London N19", "Cafe", 20),
    ("restaurants Dartmouth Park Hill London N19", "Restaurant", 40),
    ("cafes Dartmouth Park Hill London N19", "Cafe", 20),
    ("restaurants Tufnell Park Road London N19", "Restaurant", 45),
    ("cafes Tufnell Park Road London N19", "Cafe", 25),

    # N22 – Wood Green more streets
    ("restaurants Wood Green High Road London N22", "Restaurant", 55),
    ("cafes Wood Green High Road London N22", "Cafe", 35),
    ("restaurants High Road Wood Green London N22", "Restaurant", 55),
    ("cafes High Road Wood Green London N22", "Cafe", 35),
    ("restaurants Station Road Wood Green London N22", "Restaurant", 50),
    ("cafes Station Road Wood Green London N22", "Cafe", 30),
    ("restaurants Lordship Lane Wood Green London N22", "Restaurant", 50),
    ("cafes Lordship Lane Wood Green London N22", "Cafe", 30),
    ("restaurants Westbury Avenue London N22", "Restaurant", 35),
    ("cafes Westbury Avenue London N22", "Cafe", 20),

    # NW2 – Cricklewood more streets
    ("restaurants Cricklewood Broadway London NW2", "Restaurant", 55),
    ("cafes Cricklewood Broadway London NW2", "Cafe", 35),
    ("restaurants Cricklewood Lane London NW2", "Restaurant", 50),
    ("cafes Cricklewood Lane London NW2", "Cafe", 30),
    ("restaurants Chichele Road London NW2", "Restaurant", 40),
    ("cafes Chichele Road London NW2", "Cafe", 20),
    ("restaurants Walm Lane London NW2", "Restaurant", 45),
    ("cafes Walm Lane London NW2", "Cafe", 25),
    ("restaurants Anson Road London NW2", "Restaurant", 35),
    ("cafes Anson Road London NW2", "Cafe", 20),

    # NW4 – Hendon more streets
    ("restaurants Hendon Central London NW4", "Restaurant", 50),
    ("cafes Hendon Central London NW4", "Cafe", 30),
    ("restaurants Brent Street London NW4", "Restaurant", 50),
    ("cafes Brent Street London NW4", "Cafe", 30),
    ("restaurants Church Road Hendon London NW4", "Restaurant", 45),
    ("cafes Church Road Hendon London NW4", "Cafe", 25),
    ("restaurants Sentinel Square London NW4", "Restaurant", 40),
    ("cafes Sentinel Square London NW4", "Cafe", 20),
    ("restaurants Station Road Hendon London NW4", "Restaurant", 40),
    ("cafes Station Road Hendon London NW4", "Cafe", 20),

    # NW6 – Kilburn / West Hampstead more streets
    ("restaurants Kilburn High Road London NW6", "Restaurant", 55),
    ("cafes Kilburn High Road London NW6", "Cafe", 35),
    ("restaurants West End Lane London NW6", "Restaurant", 55),
    ("cafes West End Lane London NW6", "Cafe", 35),
    ("restaurants Salusbury Road London NW6", "Restaurant", 50),
    ("cafes Salusbury Road London NW6", "Cafe", 30),
    ("restaurants Priory Road London NW6", "Restaurant", 40),
    ("cafes Priory Road London NW6", "Cafe", 20),
    ("restaurants Palmerston Road London NW6", "Restaurant", 40),
    ("cafes Palmerston Road London NW6", "Cafe", 20),
    ("restaurants Quex Road London NW6", "Restaurant", 35),
    ("cafes Quex Road London NW6", "Cafe", 20),

    # NW9 – Colindale / Kingsbury more streets
    ("restaurants Colindale Avenue London NW9", "Restaurant", 50),
    ("cafes Colindale Avenue London NW9", "Cafe", 30),
    ("restaurants Kingsbury Road London NW9", "Restaurant", 50),
    ("cafes Kingsbury Road London NW9", "Cafe", 30),
    ("restaurants The Hyde London NW9", "Restaurant", 45),
    ("cafes The Hyde London NW9", "Cafe", 25),
    ("restaurants Edgware Road Colindale London NW9", "Restaurant", 50),
    ("cafes Edgware Road Colindale London NW9", "Cafe", 30),
    ("restaurants Fryent Way London NW9", "Restaurant", 35),
    ("cafes Fryent Way London NW9", "Cafe", 20),

    # NW10 – Harlesden more streets
    ("restaurants High Street Harlesden London NW10", "Restaurant", 55),
    ("cafes High Street Harlesden London NW10", "Cafe", 35),
    ("restaurants Harlesden High Street London NW10", "Restaurant", 55),
    ("cafes Harlesden High Street London NW10", "Cafe", 35),
    ("restaurants Scrubs Lane London NW10", "Restaurant", 45),
    ("cafes Scrubs Lane London NW10", "Cafe", 25),
    ("restaurants Station Road Harlesden London NW10", "Restaurant", 45),
    ("cafes Station Road Harlesden London NW10", "Cafe", 25),
    ("restaurants Craven Park Road London NW10", "Restaurant", 40),
    ("cafes Craven Park Road London NW10", "Cafe", 20),
    ("restaurants Acton Lane London NW10", "Restaurant", 45),
    ("cafes Acton Lane London NW10", "Cafe", 25),

    # NW11 – Golders Green more streets
    ("restaurants Golders Green Road London NW11", "Restaurant", 55),
    ("cafes Golders Green Road London NW11", "Cafe", 35),
    ("restaurants Temple Fortune London NW11", "Restaurant", 50),
    ("cafes Temple Fortune London NW11", "Cafe", 30),
    ("restaurants Finchley Road Golders Green London NW11", "Restaurant", 55),
    ("cafes Finchley Road Golders Green London NW11", "Cafe", 35),
    ("restaurants North End Road Golders Green London NW11", "Restaurant", 45),
    ("cafes North End Road Golders Green London NW11", "Cafe", 25),
    ("restaurants Henlys Corner London NW11", "Restaurant", 40),
    ("cafes Henlys Corner London NW11", "Cafe", 20),

    # NW1 – Camden Town / Kentish Town extra streets
    ("restaurants Camden High Street London NW1", "Restaurant", 60),
    ("cafes Camden High Street London NW1", "Cafe", 40),
    ("restaurants Kentish Town Road London NW1", "Restaurant", 55),
    ("cafes Kentish Town Road London NW1", "Cafe", 35),
    ("restaurants Chalk Farm Road London NW1", "Restaurant", 55),
    ("cafes Chalk Farm Road London NW1", "Cafe", 35),
    ("restaurants Parkway London NW1", "Restaurant", 50),
    ("cafes Parkway London NW1", "Cafe", 30),
    ("restaurants Eversholt Street London NW1", "Restaurant", 45),
    ("cafes Eversholt Street London NW1", "Cafe", 25),

    # NW3 – Hampstead / Swiss Cottage extra streets
    ("restaurants Heath Street Hampstead London NW3", "Restaurant", 55),
    ("cafes Heath Street Hampstead London NW3", "Cafe", 35),
    ("restaurants Flask Walk London NW3", "Restaurant", 45),
    ("cafes Flask Walk London NW3", "Cafe", 25),
    ("restaurants Finchley Road Swiss Cottage London NW3", "Restaurant", 55),
    ("cafes Finchley Road Swiss Cottage London NW3", "Cafe", 35),
    ("restaurants South End Road Hampstead London NW3", "Restaurant", 50),
    ("cafes South End Road Hampstead London NW3", "Cafe", 30),

    # NW5 – Kentish Town extra streets
    ("restaurants Kentish Town High Street London NW5", "Restaurant", 50),
    ("cafes Kentish Town High Street London NW5", "Cafe", 30),
    ("restaurants Fortess Road London NW5", "Restaurant", 45),
    ("cafes Fortess Road London NW5", "Cafe", 25),
    ("restaurants Malden Road London NW5", "Restaurant", 40),
    ("cafes Malden Road London NW5", "Cafe", 20),

    # NW8 – St John's Wood extra streets
    ("restaurants St John's Wood High Street London NW8", "Restaurant", 55),
    ("cafes St John's Wood High Street London NW8", "Cafe", 35),
    ("restaurants Lisson Grove London NW8", "Restaurant", 50),
    ("cafes Lisson Grove London NW8", "Cafe", 30),
    ("restaurants Wellington Road London NW8", "Restaurant", 40),
    ("cafes Wellington Road London NW8", "Cafe", 20),
]
