"""
Batch 61 – London market streets and areas not yet covered:
Petticoat Lane/Spitalfields E1, Bell Lane/Commercial St E1, Brick Lane surroundings E1,
Columbia Rd E2, Chatsworth Rd E5, Ridley Rd E8, Well Street E9, Chrisp St E14,
Queen's Market E13, Green Street E13, Barking, Walthamstow market, Leytonstone market,
North Cross Road SE22, Rye Lane SE15, Deptford market SE8, Surrey Quays SE16,
East Street Market SE17, Chapel Market N1, Nag's Head N7, Seven Sisters Rd market N15,
Whitechapel market E1, Romford market RM1, Ilford market IG1, Kingston market KT1,
Croydon market CR0
"""

SEARCH_QUERIES = [
    # Petticoat Lane / Spitalfields / Wentworth St E1
    ("restaurants Petticoat Lane London E1", "Restaurant", 55),
    ("cafes Petticoat Lane London E1", "Cafe", 35),
    ("restaurants Wentworth Street London E1", "Restaurant", 50),
    ("cafes Wentworth Street London E1", "Cafe", 30),
    ("restaurants Middlesex Street London E1", "Restaurant", 50),
    ("cafes Middlesex Street London E1", "Cafe", 30),
    ("restaurants Bell Lane London E1", "Restaurant", 45),
    ("cafes Bell Lane London E1", "Cafe", 25),
    ("restaurants Commercial Street London E1", "Restaurant", 55),
    ("cafes Commercial Street London E1", "Cafe", 35),
    ("restaurants Brushfield Street London E1", "Restaurant", 50),
    ("cafes Brushfield Street London E1", "Cafe", 30),
    ("restaurants Lamb Street Spitalfields London E1", "Restaurant", 45),
    ("cafes Lamb Street Spitalfields London E1", "Cafe", 25),
    ("restaurants Crispin Street London E1", "Restaurant", 40),
    ("cafes Crispin Street London E1", "Cafe", 25),
    ("restaurants Folgate Street London E1", "Restaurant", 40),
    ("cafes Folgate Street London E1", "Cafe", 20),

    # Brick Lane surroundings E1
    ("restaurants Brick Lane London E1", "Restaurant", 60),
    ("cafes Brick Lane London E1", "Cafe", 40),
    ("restaurants Hanbury Street London E1", "Restaurant", 50),
    ("cafes Hanbury Street London E1", "Cafe", 30),
    ("restaurants Buxton Street London E1", "Restaurant", 40),
    ("cafes Buxton Street London E1", "Cafe", 25),
    ("restaurants Fournier Street London E1", "Restaurant", 40),
    ("cafes Fournier Street London E1", "Cafe", 25),
    ("restaurants Fashion Street London E1", "Restaurant", 40),
    ("cafes Fashion Street London E1", "Cafe", 20),
    ("restaurants Princelet Street London E1", "Restaurant", 40),
    ("cafes Princelet Street London E1", "Cafe", 20),

    # Columbia Road E2
    ("restaurants Columbia Road London E2", "Restaurant", 55),
    ("cafes Columbia Road London E2", "Cafe", 35),
    ("restaurants Ravenscroft Street London E2", "Restaurant", 35),
    ("cafes Ravenscroft Street London E2", "Cafe", 20),
    ("restaurants Ezra Street London E2", "Restaurant", 35),
    ("cafes Ezra Street London E2", "Cafe", 20),

    # Chatsworth Road E5 market area
    ("restaurants Chatsworth Road market London E5", "Restaurant", 50),
    ("cafes Chatsworth Road market London E5", "Cafe", 30),
    ("restaurants Chatsworth Road Clapton London E5", "Restaurant", 50),
    ("cafes Chatsworth Road Clapton London E5", "Cafe", 30),

    # Ridley Road E8
    ("restaurants Ridley Road Market London E8", "Restaurant", 55),
    ("cafes Ridley Road Market London E8", "Cafe", 35),
    ("restaurants Ridley Road Dalston London E8", "Restaurant", 55),
    ("cafes Ridley Road Dalston London E8", "Cafe", 35),
    ("restaurants Kingsland Road London E8", "Restaurant", 55),
    ("cafes Kingsland Road London E8", "Cafe", 35),

    # Well Street Market E9
    ("restaurants Well Street Market London E9", "Restaurant", 45),
    ("cafes Well Street Market London E9", "Cafe", 25),
    ("restaurants Well Street Hackney London E9", "Restaurant", 45),
    ("cafes Well Street Hackney London E9", "Cafe", 25),
    ("restaurants Morning Lane London E9", "Restaurant", 45),
    ("cafes Morning Lane London E9", "Cafe", 25),

    # Chrisp Street E14
    ("restaurants Chrisp Street Market London E14", "Restaurant", 50),
    ("cafes Chrisp Street Market London E14", "Cafe", 30),
    ("restaurants Poplar market London E14", "Restaurant", 45),
    ("cafes Poplar market London E14", "Cafe", 25),

    # Queen's Market E13 / Green Street E13
    ("restaurants Queens Market London E13", "Restaurant", 55),
    ("cafes Queens Market London E13", "Cafe", 35),
    ("restaurants Green Street London E13", "Restaurant", 55),
    ("cafes Green Street London E13", "Cafe", 35),
    ("restaurants Upton Park London E13", "Restaurant", 50),
    ("cafes Upton Park London E13", "Cafe", 30),
    ("restaurants Plashet Road London E13", "Restaurant", 40),
    ("cafes Plashet Road London E13", "Cafe", 20),

    # Barking market area
    ("restaurants Barking Town Centre London IG11", "Restaurant", 55),
    ("cafes Barking Town Centre London IG11", "Cafe", 35),
    ("restaurants East Street Barking London IG11", "Restaurant", 50),
    ("cafes East Street Barking London IG11", "Cafe", 30),
    ("restaurants Vicarage Drive Barking London IG11", "Restaurant", 40),
    ("cafes Vicarage Drive Barking London IG11", "Cafe", 20),

    # Walthamstow market streets
    ("restaurants Walthamstow Market London E17", "Restaurant", 55),
    ("cafes Walthamstow Market London E17", "Cafe", 35),
    ("restaurants Selborne Road London E17", "Restaurant", 40),
    ("cafes Selborne Road London E17", "Cafe", 20),
    ("restaurants St James Street Walthamstow London E17", "Restaurant", 45),
    ("cafes St James Street Walthamstow London E17", "Cafe", 25),

    # Leytonstone market area
    ("restaurants Leytonstone market London E11", "Restaurant", 45),
    ("cafes Leytonstone market London E11", "Cafe", 25),
    ("restaurants Francis Road Leyton London E10", "Restaurant", 45),
    ("cafes Francis Road Leyton London E10", "Cafe", 25),

    # North Cross Road SE22 (East Dulwich market area)
    ("restaurants North Cross Road London SE22", "Restaurant", 50),
    ("cafes North Cross Road London SE22", "Cafe", 30),
    ("restaurants Lordship Lane East Dulwich London SE22", "Restaurant", 55),
    ("cafes Lordship Lane East Dulwich London SE22", "Cafe", 35),
    ("restaurants Melbourne Grove London SE22", "Restaurant", 35),
    ("cafes Melbourne Grove London SE22", "Cafe", 20),

    # Rye Lane SE15
    ("restaurants Rye Lane Peckham London SE15", "Restaurant", 55),
    ("cafes Rye Lane Peckham London SE15", "Cafe", 35),
    ("restaurants Peckham High Street London SE15", "Restaurant", 55),
    ("cafes Peckham High Street London SE15", "Cafe", 35),
    ("restaurants Bellenden Road London SE15", "Restaurant", 50),
    ("cafes Bellenden Road London SE15", "Cafe", 30),
    ("restaurants Choumert Road London SE15", "Restaurant", 45),
    ("cafes Choumert Road London SE15", "Cafe", 25),

    # Deptford market SE8
    ("restaurants Deptford Market London SE8", "Restaurant", 50),
    ("cafes Deptford Market London SE8", "Cafe", 30),
    ("restaurants Douglas Way Deptford London SE8", "Restaurant", 40),
    ("cafes Douglas Way Deptford London SE8", "Cafe", 20),

    # Surrey Quays / Rotherhithe area SE16
    ("restaurants Surrey Quays London SE16", "Restaurant", 50),
    ("cafes Surrey Quays London SE16", "Cafe", 30),
    ("restaurants Surrey Docks Farm London SE16", "Restaurant", 35),
    ("cafes Surrey Docks London SE16", "Cafe", 20),

    # East Street Market SE17
    ("restaurants East Street Market London SE17", "Restaurant", 50),
    ("cafes East Street Market London SE17", "Cafe", 30),
    ("restaurants East Street Walworth London SE17", "Restaurant", 50),
    ("cafes East Street Walworth London SE17", "Cafe", 30),

    # Chapel Market N1
    ("restaurants Chapel Market London N1", "Restaurant", 55),
    ("cafes Chapel Market London N1", "Cafe", 35),
    ("restaurants Liverpool Road London N1", "Restaurant", 55),
    ("cafes Liverpool Road London N1", "Cafe", 35),
    ("restaurants White Lion Street London N1", "Restaurant", 45),
    ("cafes White Lion Street London N1", "Cafe", 25),

    # Nag's Head Market N7
    ("restaurants Nag's Head Market London N7", "Restaurant", 50),
    ("cafes Nag's Head Market London N7", "Cafe", 30),
    ("restaurants Seven Sisters Road Holloway London N7", "Restaurant", 50),
    ("cafes Seven Sisters Road Holloway London N7", "Cafe", 30),

    # Seven Sisters Road market N15
    ("restaurants Seven Sisters market London N15", "Restaurant", 50),
    ("cafes Seven Sisters market London N15", "Cafe", 30),
    ("restaurants West Green Road market London N15", "Restaurant", 45),
    ("cafes West Green Road market London N15", "Cafe", 25),

    # Whitechapel Market E1
    ("restaurants Whitechapel Market London E1", "Restaurant", 55),
    ("cafes Whitechapel Market London E1", "Cafe", 35),
    ("restaurants Whitechapel Road London E1", "Restaurant", 55),
    ("cafes Whitechapel Road London E1", "Cafe", 35),
    ("restaurants Fieldgate Street London E1", "Restaurant", 40),
    ("cafes Fieldgate Street London E1", "Cafe", 20),

    # Romford market RM1
    ("restaurants Romford Market London RM1", "Restaurant", 55),
    ("cafes Romford Market London RM1", "Cafe", 35),
    ("restaurants South Street Romford London RM1", "Restaurant", 50),
    ("cafes South Street Romford London RM1", "Cafe", 30),
    ("restaurants Market Place Romford London RM1", "Restaurant", 50),
    ("cafes Market Place Romford London RM1", "Cafe", 30),

    # Ilford market IG1
    ("restaurants Ilford Market London IG1", "Restaurant", 55),
    ("cafes Ilford Market London IG1", "Cafe", 35),
    ("restaurants High Road Ilford London IG1", "Restaurant", 55),
    ("cafes High Road Ilford London IG1", "Cafe", 35),
    ("restaurants Cranbrook Road Ilford London IG1", "Restaurant", 45),
    ("cafes Cranbrook Road Ilford London IG1", "Cafe", 25),

    # Kingston market KT1
    ("restaurants Kingston market London KT1", "Restaurant", 55),
    ("cafes Kingston market London KT1", "Cafe", 35),
    ("restaurants Market Place Kingston London KT1", "Restaurant", 55),
    ("cafes Market Place Kingston London KT1", "Cafe", 35),
    ("restaurants Clarence Street Kingston London KT1", "Restaurant", 50),
    ("cafes Clarence Street Kingston London KT1", "Cafe", 30),
    ("restaurants Eden Walk Kingston London KT1", "Restaurant", 45),
    ("cafes Eden Walk Kingston London KT1", "Cafe", 25),

    # Croydon market CR0
    ("restaurants Croydon Market London CR0", "Restaurant", 55),
    ("cafes Croydon Market London CR0", "Cafe", 35),
    ("restaurants Surrey Street Market London CR0", "Restaurant", 50),
    ("cafes Surrey Street Market London CR0", "Cafe", 30),
    ("restaurants North End Croydon London CR0", "Restaurant", 55),
    ("cafes North End Croydon London CR0", "Cafe", 35),
    ("restaurants George Street Croydon London CR0", "Restaurant", 50),
    ("cafes George Street Croydon London CR0", "Cafe", 30),

    # Additional inner London market / high street areas
    ("restaurants Broadway Market London E8", "Restaurant", 55),
    ("cafes Broadway Market London E8", "Cafe", 35),
    ("restaurants Netil Market London E8", "Restaurant", 40),
    ("cafes Netil Market London E8", "Cafe", 25),
    ("restaurants Victoria Park Market London E3", "Restaurant", 40),
    ("cafes Victoria Park Market London E3", "Cafe", 25),
    ("restaurants Columbia Road flower market London E2", "Restaurant", 45),
    ("cafes Columbia Road flower market London E2", "Cafe", 30),
    ("restaurants Maltby Street Market London SE1", "Restaurant", 50),
    ("cafes Maltby Street Market London SE1", "Cafe", 30),
    ("restaurants Bermondsey Square Market London SE1", "Restaurant", 45),
    ("cafes Bermondsey Square Market London SE1", "Cafe", 25),
    ("restaurants Borough Market area London SE1", "Restaurant", 60),
    ("cafes Borough Market area London SE1", "Cafe", 40),
    ("restaurants Leather Lane Market London EC1", "Restaurant", 50),
    ("cafes Leather Lane Market London EC1", "Cafe", 30),
    ("restaurants Exmouth Market London EC1", "Restaurant", 55),
    ("cafes Exmouth Market London EC1", "Cafe", 35),
    ("restaurants Berwick Street Market London W1", "Restaurant", 55),
    ("cafes Berwick Street Market London W1", "Cafe", 35),
    ("restaurants Portobello Road Market London W11", "Restaurant", 60),
    ("cafes Portobello Road Market London W11", "Cafe", 40),
    ("restaurants Golborne Road London W10", "Restaurant", 50),
    ("cafes Golborne Road London W10", "Cafe", 30),
    ("restaurants Shepherd's Bush Market London W12", "Restaurant", 50),
    ("cafes Shepherd's Bush Market London W12", "Cafe", 30),
    ("restaurants Chapel Street Islington London N1", "Restaurant", 50),
    ("cafes Chapel Street Islington London N1", "Cafe", 30),
    ("restaurants Stoke Newington High Street London N16", "Restaurant", 55),
    ("cafes Stoke Newington High Street London N16", "Cafe", 35),
    ("restaurants Newington Green London N16", "Restaurant", 50),
    ("cafes Newington Green London N16", "Cafe", 30),
    ("restaurants Brixton Village London SW9", "Restaurant", 55),
    ("cafes Brixton Village London SW9", "Cafe", 35),
    ("restaurants Granville Arcade London SW9", "Restaurant", 50),
    ("cafes Granville Arcade London SW9", "Cafe", 30),
    ("restaurants Streatham market London SW16", "Restaurant", 45),
    ("cafes Streatham market London SW16", "Cafe", 25),
    ("restaurants Mitcham market London CR4", "Restaurant", 40),
    ("cafes Mitcham market London CR4", "Cafe", 20),

    # More outer London shopping parade streets not yet covered
    ("restaurants Tooting Broadway London SW17", "Restaurant", 55),
    ("cafes Tooting Broadway London SW17", "Cafe", 35),
    ("restaurants Norwood Road London SE24", "Restaurant", 45),
    ("cafes Norwood Road London SE24", "Cafe", 25),
    ("restaurants Tulse Hill London SE24", "Restaurant", 40),
    ("cafes Tulse Hill London SE24", "Cafe", 20),
    ("restaurants Gipsy Hill London SE19", "Restaurant", 40),
    ("cafes Gipsy Hill London SE19", "Cafe", 20),
    ("restaurants Herne Hill London SE24", "Restaurant", 50),
    ("cafes Herne Hill London SE24", "Cafe", 30),
    ("restaurants Knight's Hill London SE27", "Restaurant", 40),
    ("cafes Knight's Hill London SE27", "Cafe", 20),
    ("restaurants Norwood High Street London SE27", "Restaurant", 45),
    ("cafes Norwood High Street London SE27", "Cafe", 25),
    ("restaurants Anerley London SE20", "Restaurant", 40),
    ("cafes Anerley London SE20", "Cafe", 20),
    ("restaurants Penge London SE20", "Restaurant", 40),
    ("cafes Penge London SE20", "Cafe", 20),
    ("restaurants Harold Road Penge London SE20", "Restaurant", 35),
    ("cafes Harold Road Penge London SE20", "Cafe", 20),
    ("restaurants Mottingham London SE9", "Restaurant", 35),
    ("cafes Mottingham London SE9", "Cafe", 20),
    ("restaurants Lee Green London SE12", "Restaurant", 40),
    ("cafes Lee Green London SE12", "Cafe", 20),
    ("restaurants Lee High Street London SE12", "Restaurant", 40),
    ("cafes Lee High Street London SE12", "Cafe", 20),
    ("restaurants Grove Park London SE12", "Restaurant", 35),
    ("cafes Grove Park London SE12", "Cafe", 20),
    ("restaurants Bellingham London SE6", "Restaurant", 35),
    ("cafes Bellingham London SE6", "Cafe", 20),
    ("restaurants Downham London BR1", "Restaurant", 35),
    ("cafes Downham London BR1", "Cafe", 20),
    ("restaurants Bromley High Street London BR1", "Restaurant", 55),
    ("cafes Bromley High Street London BR1", "Cafe", 35),
    ("restaurants Beckenham High Street London BR3", "Restaurant", 50),
    ("cafes Beckenham High Street London BR3", "Cafe", 30),
    ("restaurants West Norwood London SE27", "Restaurant", 45),
    ("cafes West Norwood London SE27", "Cafe", 25),
    ("restaurants Streatham High Road South London SW16", "Restaurant", 50),
    ("cafes Streatham High Road South London SW16", "Cafe", 30),
    ("restaurants Balham High Road London SW12", "Restaurant", 50),
    ("cafes Balham High Road London SW12", "Cafe", 30),
    ("restaurants Mitcham London CR4", "Restaurant", 45),
    ("cafes Mitcham London CR4", "Cafe", 25),
    ("restaurants Morden London SM4", "Restaurant", 45),
    ("cafes Morden London SM4", "Cafe", 25),
    ("restaurants Colliers Wood London SW19", "Restaurant", 40),
    ("cafes Colliers Wood London SW19", "Cafe", 20),
    ("restaurants Wimbledon South London SW19", "Restaurant", 45),
    ("cafes Wimbledon South London SW19", "Cafe", 25),
    ("restaurants Raynes Park London SW20", "Restaurant", 45),
    ("cafes Raynes Park London SW20", "Cafe", 25),
    ("restaurants New Malden High Street London KT3", "Restaurant", 55),
    ("cafes New Malden High Street London KT3", "Cafe", 35),
    ("restaurants Norbiton London KT1", "Restaurant", 40),
    ("cafes Norbiton London KT1", "Cafe", 20),
    ("restaurants Hook Road Chessington London KT9", "Restaurant", 35),
    ("cafes Chessington London KT9", "Cafe", 20),
    ("restaurants Long Ditton London KT6", "Restaurant", 35),
    ("cafes Long Ditton London KT6", "Cafe", 20),
    ("restaurants Tolworth Broadway London KT5", "Restaurant", 40),
    ("cafes Tolworth Broadway London KT5", "Cafe", 20),
    ("restaurants Berrylands London KT5", "Restaurant", 35),
    ("cafes Berrylands London KT5", "Cafe", 20),
    ("restaurants Hook London KT9", "Restaurant", 35),
    ("cafes Hook London KT9", "Cafe", 20),
    ("restaurants Malden Manor London KT3", "Restaurant", 35),
    ("cafes Malden Manor London KT3", "Cafe", 20),
    ("restaurants Worcester Park London KT4", "Restaurant", 40),
    ("cafes Worcester Park London KT4", "Cafe", 20),
    ("restaurants Hampton Wick London KT1", "Restaurant", 35),
    ("cafes Hampton Wick London KT1", "Cafe", 20),
]
