"""
Batch 76 - East London outer areas: Ilford, Barking, Dagenham, Romford, Harold Hill,
Hornchurch, Upminster, Chadwell Heath, Goodmayes, Seven Kings, Gants Hill,
plus Wanstead, Woodford, Chingford, Loughton (London Borough of Redbridge/Waltham Forest).
"""

SEARCH_QUERIES = [
    # Ilford / central
    "restaurants Ilford London IG1",
    "cafes Ilford London IG1",
    "restaurants Ilford High Road London IG1",
    "cafes Ilford High Road London IG1",
    "restaurants Cranbrook Road Ilford London IG1",
    "cafes Cranbrook Road Ilford London IG1",
    "restaurants Ilford Lane London IG1",
    "cafes Ilford Lane London IG1",
    "Indian restaurants Ilford London IG1",
    "Bangladeshi restaurants Ilford London",
    "Pakistani restaurants Ilford London",
    "halal restaurants Ilford London IG1",
    "brunch Ilford London",
    "pizza restaurant Ilford London IG1",
    "vegan restaurant Ilford London",
    # Seven Kings / Goodmayes
    "restaurants Seven Kings London IG3",
    "cafes Seven Kings London IG3",
    "restaurants Goodmayes London IG3",
    "cafes Goodmayes London IG3",
    "Indian restaurants Seven Kings London",
    "halal restaurants Seven Kings London",
    "brunch Seven Kings London",
    "pizza restaurant Seven Kings London IG3",
    # Gants Hill / Redbridge
    "restaurants Gants Hill London IG2",
    "cafes Gants Hill London IG2",
    "restaurants Redbridge London IG4",
    "cafes Redbridge London IG4",
    "Indian restaurants Gants Hill London",
    "kosher restaurant Gants Hill London",
    "pizza restaurant Gants Hill London IG2",
    "brunch Gants Hill London",
    # Wanstead / Aldersbrook
    "restaurants Wanstead London E11",
    "cafes Wanstead London E11",
    "restaurants High Street Wanstead London E11",
    "cafes High Street Wanstead London E11",
    "restaurants Cambridge Park Wanstead London E11",
    "brunch Wanstead London",
    "gastropub Wanstead London",
    "pizza restaurant Wanstead London E11",
    "Italian restaurant Wanstead London",
    "vegan restaurant Wanstead London",
    # South Woodford / Woodford
    "restaurants South Woodford London E18",
    "cafes South Woodford London E18",
    "restaurants George Lane South Woodford London E18",
    "cafes George Lane South Woodford London E18",
    "restaurants Woodford Green London IG8",
    "cafes Woodford Green London IG8",
    "brunch South Woodford London",
    "gastropub South Woodford London",
    "pizza restaurant South Woodford London E18",
    "Indian restaurant South Woodford London",
    # Chingford / Highams Park
    "restaurants Chingford London E4",
    "cafes Chingford London E4",
    "restaurants Chingford High Street London E4",
    "cafes Chingford High Street London E4",
    "restaurants Highams Park London E4",
    "cafes Highams Park London E4",
    "brunch Chingford London",
    "gastropub Chingford London",
    "pizza restaurant Chingford London E4",
    "Indian restaurant Chingford London",
    # Barking
    "restaurants Barking London IG11",
    "cafes Barking London IG11",
    "restaurants Barking Town Centre London IG11",
    "cafes Barking Town Centre London IG11",
    "restaurants East Street Barking London IG11",
    "restaurants Axe Street Barking London IG11",
    "Indian restaurants Barking London",
    "halal restaurants Barking London IG11",
    "Chinese restaurants Barking London",
    "brunch Barking London",
    "pizza restaurant Barking London IG11",
    "vegan restaurant Barking London",
    # Dagenham / Becontree
    "restaurants Dagenham London RM10",
    "cafes Dagenham London RM10",
    "restaurants Dagenham Heathway London RM10",
    "cafes Dagenham Heathway London RM10",
    "restaurants Becontree London RM9",
    "cafes Becontree London RM9",
    "restaurants Wood Lane Dagenham London RM10",
    "Indian restaurants Dagenham London",
    "halal restaurants Dagenham London",
    "pizza restaurant Dagenham London RM10",
    # Romford / Harold Hill / Harold Wood
    "restaurants Romford London RM1",
    "cafes Romford London RM1",
    "restaurants Romford Market London RM1",
    "cafes Romford Market London RM1",
    "restaurants South Street Romford London RM1",
    "cafes South Street Romford London RM1",
    "restaurants Harold Hill London RM3",
    "cafes Harold Hill London RM3",
    "restaurants Harold Wood London RM3",
    "cafes Harold Wood London RM3",
    "Indian restaurants Romford London RM1",
    "halal restaurants Romford London",
    "Chinese restaurants Romford London",
    "brunch Romford London",
    "pizza restaurant Romford London RM1",
    "gastropub Romford London",
    # Hornchurch / Upminster / Elm Park
    "restaurants Hornchurch London RM11",
    "cafes Hornchurch London RM11",
    "restaurants Hornchurch High Street London RM11",
    "cafes Hornchurch High Street London RM11",
    "restaurants Upminster London RM14",
    "cafes Upminster London RM14",
    "restaurants St Mary's Lane Upminster London RM14",
    "restaurants Elm Park London RM12",
    "cafes Elm Park London RM12",
    "Indian restaurants Hornchurch London",
    "brunch Hornchurch London",
    "pizza restaurant Hornchurch London RM11",
    "gastropub Hornchurch London",
    "gastropub Upminster London",
    # Chadwell Heath / Rush Green
    "restaurants Chadwell Heath London RM6",
    "cafes Chadwell Heath London RM6",
    "restaurants Rush Green London RM7",
    "cafes Rush Green London RM7",
    "Indian restaurants Chadwell Heath London",
    "pizza restaurant Chadwell Heath London RM6",
    # Rainham / Havering (London Borough)
    "restaurants Rainham London RM13",
    "cafes Rainham London RM13",
    "restaurants Wennington London RM13",
    "pizza restaurant Rainham London RM13",
    "gastropub Rainham London",
    # Walthamstow additional streets
    "restaurants Forest Road Walthamstow London E17",
    "cafes Forest Road Walthamstow London E17",
    "restaurants Blackhorse Road London E17",
    "cafes Blackhorse Road London E17",
    "restaurants Highams Park Walthamstow London E4",
    "vegan restaurant Blackhorse Road London E17",
    "pizza restaurant Blackhorse Road London E17",
    # Loughton (outer London borough edge)
    "restaurants Loughton Essex IG10",
    "cafes Loughton Essex IG10",
    "restaurants High Road Loughton London IG10",
    "cafes High Road Loughton London IG10",
    "brunch Loughton London",
    "gastropub Loughton London",
    "pizza restaurant Loughton London IG10",
    # Collier Row / Noak Hill (outer East)
    "restaurants Collier Row London RM5",
    "cafes Collier Row London RM5",
    "Indian restaurants Collier Row London",
    "pizza restaurant Collier Row London RM5",
    # Food delivery / takeaway outer East London
    "food delivery service Ilford London IG1",
    "food delivery service Romford London RM1",
    "food delivery service Barking London IG11",
    "food delivery service Dagenham London RM10",
    "takeaway Ilford London IG1",
    "takeaway Romford London RM1",
    "takeaway Barking London IG11",
    "takeaway Walthamstow London E17",
    "takeaway Seven Kings London IG3",
    "takeaway Gants Hill London IG2",
    "takeaway South Woodford London E18",
    "takeaway Hornchurch London RM11",
    "takeaway Chingford London E4",
    "takeaway Wanstead London E11",
    # Cuisine x outer East postcodes
    "Indian restaurant IG1 London",
    "Indian restaurant IG2 London",
    "Indian restaurant IG3 London",
    "Indian restaurant IG4 London",
    "Indian restaurant RM1 London",
    "Indian restaurant RM2 London",
    "Indian restaurant RM3 London",
    "Indian restaurant RM6 London",
    "Indian restaurant RM11 London",
    "Chinese restaurant IG1 London",
    "Chinese restaurant RM1 London",
    "halal restaurant IG1 London",
    "halal restaurant IG3 London",
    "halal restaurant RM1 London",
    "halal restaurant RM10 London",
    "pizza restaurant IG1 London",
    "pizza restaurant IG2 London",
    "pizza restaurant RM1 London",
    "pizza restaurant RM11 London",
    "Turkish restaurant IG1 London",
    "Turkish restaurant RM1 London",
    "Turkish restaurant E17 London",
    "fish and chips IG1 London",
    "fish and chips RM1 London",
    "fish and chips IG3 London",
    "fish and chips E17 London",
    "fish and chips E4 London",
    "fish and chips E11 London",
    "brunch IG1 London",
    "brunch IG2 London",
    "brunch E18 London",
    "brunch E11 London",
    "brunch E4 London",
    "gastropub IG1 London",
    "gastropub E11 London",
    "gastropub E18 London",
    "gastropub E4 London",
    "gastropub RM1 London",
    "gastropub RM11 London",
    "vegan restaurant E17 London",
    "vegan restaurant E4 London",
    "vegan restaurant E11 London",
    "vegan restaurant IG1 London",
    "vegan restaurant IG2 London",
    "Italian restaurant E17 London",
    "Italian restaurant E4 London",
    "Italian restaurant IG1 London",
    "Italian restaurant RM1 London",
    "wine bar E17 London",
    "wine bar E11 London",
    "wine bar IG1 London",
    "cafe IG4 London",
    "cafe IG5 London",
    "restaurants Hainault London IG6",
    "cafes Hainault London IG6",
    "restaurants Clayhall London IG5",
    "cafes Clayhall London IG5",
    "restaurants Fairlop London IG6",
]
