"""
Batch 62 – Professional/B2B food services London:
Food importers/wholesalers with retail, restaurant supply companies, catering equipment showrooms,
hotel catering departments, hospital restaurant/cafe franchises, airport terminal restaurants
(Heathrow T2/T3/T4/T5, Gatwick, London City, Stansted, Luton),
train station cafes (Paddington, Kings Cross, Waterloo, Victoria, Liverpool Street, London Bridge,
Cannon Street, Fenchurch Street, Moorgate, Charing Cross, Euston, St Pancras),
corporate dining / workplace restaurant searches
"""

SEARCH_QUERIES = [
    # Food importers / wholesalers with retail
    ("food importer London", "Wholesale", 40),
    ("food wholesaler London with shop", "Wholesale", 40),
    ("wholesale food supplier London", "Wholesale", 45),
    ("food cash and carry London", "Wholesale", 50),
    ("restaurant wholesale food London", "Wholesale", 45),
    ("food distributor London restaurant", "Wholesale", 40),
    ("Italian food importer London", "Wholesale", 35),
    ("Asian food wholesaler London", "Wholesale", 40),
    ("Middle Eastern food wholesaler London", "Wholesale", 35),
    ("African food wholesaler London", "Wholesale", 35),
    ("Caribbean food importer London", "Wholesale", 30),
    ("halal meat wholesaler London", "Wholesale", 40),
    ("kosher food supplier London", "Wholesale", 35),
    ("organic food wholesaler London", "Wholesale", 35),
    ("seafood wholesaler London restaurant", "Wholesale", 40),
    ("meat wholesaler London restaurant supply", "Wholesale", 40),
    ("cheese importer London restaurant", "Wholesale", 35),
    ("wine importer London restaurant trade", "Wholesale", 40),
    ("beer distributor London trade", "Wholesale", 35),
    ("speciality food importer London", "Wholesale", 35),

    # Restaurant supply companies / catering equipment
    ("restaurant supply company London", "Supply", 45),
    ("catering equipment London", "Supply", 45),
    ("catering supplies London", "Supply", 45),
    ("commercial kitchen equipment London", "Supply", 40),
    ("catering equipment showroom London", "Supply", 40),
    ("restaurant equipment supplier London", "Supply", 40),
    ("professional kitchen supplies London", "Supply", 35),
    ("catering equipment rental London", "Supply", 35),
    ("chef uniform supplier London", "Supply", 30),
    ("tableware supplier London restaurant", "Supply", 35),
    ("food packaging supplier London", "Supply", 30),
    ("catering supplies North London", "Supply", 35),
    ("catering supplies South London", "Supply", 35),
    ("catering supplies East London", "Supply", 35),
    ("catering supplies West London", "Supply", 35),

    # Hotel restaurants / hotel catering
    ("hotel restaurant London W1", "Restaurant", 50),
    ("hotel restaurant London SW1", "Restaurant", 50),
    ("hotel restaurant London WC2", "Restaurant", 50),
    ("hotel restaurant London EC1", "Restaurant", 45),
    ("hotel restaurant London SE1", "Restaurant", 45),
    ("hotel restaurant London NW1", "Restaurant", 45),
    ("boutique hotel restaurant London", "Restaurant", 50),
    ("hotel dining London", "Restaurant", 50),
    ("hotel bar and restaurant London", "Restaurant", 50),
    ("five star hotel restaurant London", "Restaurant", 45),
    ("hotel breakfast London W1", "Restaurant", 40),
    ("hotel afternoon tea London", "Restaurant", 50),

    # Hospital restaurants / NHS catering
    ("hospital cafe London", "Cafe", 40),
    ("hospital restaurant London", "Restaurant", 40),
    ("NHS canteen London", "Restaurant", 35),
    ("hospital canteen food London", "Restaurant", 35),
    ("cafe Royal London Hospital Whitechapel", "Cafe", 30),
    ("cafe St Thomas Hospital London", "Cafe", 30),
    ("cafe King's College Hospital London", "Cafe", 30),
    ("cafe Guy's Hospital London", "Cafe", 30),
    ("cafe University College Hospital London", "Cafe", 30),
    ("cafe Bart's Hospital London EC1", "Cafe", 25),
    ("cafe Hammersmith Hospital London", "Cafe", 25),
    ("cafe Charing Cross Hospital London", "Cafe", 25),
    ("cafe Chelsea and Westminster Hospital London", "Cafe", 25),
    ("cafe Northwick Park Hospital London", "Cafe", 25),

    # Heathrow Terminal restaurants
    ("restaurants Heathrow Terminal 2 London", "Restaurant", 50),
    ("cafes Heathrow Terminal 2 London", "Cafe", 40),
    ("restaurants Heathrow Terminal 3 London", "Restaurant", 50),
    ("cafes Heathrow Terminal 3 London", "Cafe", 40),
    ("restaurants Heathrow Terminal 4 London", "Restaurant", 45),
    ("cafes Heathrow Terminal 4 London", "Cafe", 35),
    ("restaurants Heathrow Terminal 5 London", "Restaurant", 55),
    ("cafes Heathrow Terminal 5 London", "Cafe", 40),
    ("food Heathrow Airport London", "Restaurant", 55),
    ("dining Heathrow Airport TW6", "Restaurant", 50),

    # Gatwick, London City, Stansted, Luton
    ("restaurants Gatwick Airport London", "Restaurant", 50),
    ("cafes Gatwick Airport London", "Cafe", 35),
    ("restaurants London City Airport E16", "Restaurant", 45),
    ("cafes London City Airport E16", "Cafe", 30),
    ("restaurants Stansted Airport London", "Restaurant", 45),
    ("cafes Stansted Airport London", "Cafe", 30),
    ("restaurants Luton Airport London", "Restaurant", 40),
    ("cafes Luton Airport London", "Cafe", 25),

    # Train station restaurants / cafes
    ("restaurants London Paddington station W2", "Restaurant", 55),
    ("cafes London Paddington station W2", "Cafe", 40),
    ("restaurants London Kings Cross station N1", "Restaurant", 55),
    ("cafes London Kings Cross station N1", "Cafe", 40),
    ("restaurants London Waterloo station SE1", "Restaurant", 55),
    ("cafes London Waterloo station SE1", "Cafe", 40),
    ("restaurants London Victoria station SW1", "Restaurant", 55),
    ("cafes London Victoria station SW1", "Cafe", 40),
    ("restaurants Liverpool Street station London EC2", "Restaurant", 55),
    ("cafes Liverpool Street station London EC2", "Cafe", 40),
    ("restaurants London Bridge station SE1", "Restaurant", 55),
    ("cafes London Bridge station SE1", "Cafe", 40),
    ("restaurants Cannon Street station London EC4", "Restaurant", 45),
    ("cafes Cannon Street station London EC4", "Cafe", 30),
    ("restaurants Fenchurch Street station London EC3", "Restaurant", 40),
    ("cafes Fenchurch Street station London EC3", "Cafe", 25),
    ("restaurants Moorgate station London EC2", "Restaurant", 45),
    ("cafes Moorgate station London EC2", "Cafe", 30),
    ("restaurants Charing Cross station London WC2", "Restaurant", 55),
    ("cafes Charing Cross station London WC2", "Cafe", 35),
    ("restaurants Euston station London NW1", "Restaurant", 55),
    ("cafes Euston station London NW1", "Cafe", 40),
    ("restaurants St Pancras International London N1C", "Restaurant", 55),
    ("cafes St Pancras International London N1C", "Cafe", 40),
    ("restaurants Marylebone station London NW1", "Restaurant", 45),
    ("cafes Marylebone station London NW1", "Cafe", 30),
    ("restaurants Blackfriars station London EC4", "Restaurant", 45),
    ("cafes Blackfriars station London EC4", "Cafe", 30),
    ("restaurants London Bridge railway food SE1", "Restaurant", 50),
    ("restaurants Stratford International station London E15", "Restaurant", 45),

    # Corporate dining / workplace restaurants
    ("corporate restaurant London", "Restaurant", 45),
    ("workplace canteen London", "Restaurant", 40),
    ("staff restaurant London", "Restaurant", 40),
    ("corporate catering London", "Catering", 45),
    ("office canteen London", "Restaurant", 40),
    ("corporate dining EC1", "Restaurant", 35),
    ("corporate dining EC2", "Restaurant", 35),
    ("corporate dining EC3", "Restaurant", 35),
    ("corporate dining EC4", "Restaurant", 35),
    ("corporate dining WC1", "Restaurant", 35),
    ("corporate dining WC2", "Restaurant", 35),
    ("corporate dining E14 Canary Wharf", "Restaurant", 40),
    ("corporate catering Canary Wharf London E14", "Catering", 40),
    ("workplace food service London City", "Restaurant", 40),
    ("business dining London W1", "Restaurant", 40),

    # University / student union cafes and restaurants
    ("university cafe London", "Cafe", 45),
    ("student union bar London", "Bar", 40),
    ("university canteen London", "Restaurant", 40),
    ("UCL canteen restaurant London WC1", "Restaurant", 35),
    ("King's College London cafe restaurant", "Cafe", 35),
    ("LSE cafe restaurant London WC2", "Cafe", 35),
    ("Imperial College restaurant London SW7", "Restaurant", 35),
    ("Queen Mary University cafe London E1", "Cafe", 30),
    ("University of East London cafe London E16", "Cafe", 25),
    ("Goldsmiths College cafe London SE14", "Cafe", 25),
    ("Brunel University cafe London UB8", "Cafe", 25),
    ("Middlesex University cafe London N14", "Cafe", 25),

    # Stadium / arena / entertainment venue food
    ("restaurants Wembley Stadium London HA9", "Restaurant", 45),
    ("cafes Wembley Arena London HA9", "Cafe", 30),
    ("restaurants O2 Arena London SE10", "Restaurant", 50),
    ("cafes O2 Arena London SE10", "Cafe", 30),
    ("restaurants Alexandra Palace London N22", "Restaurant", 45),
    ("cafes Alexandra Palace London N22", "Cafe", 30),
    ("restaurants Royal Albert Hall London SW7", "Restaurant", 45),
    ("restaurants Barbican Centre London EC2", "Restaurant", 50),
    ("cafes Barbican Centre London EC2", "Cafe", 35),
    ("restaurants South Bank Centre London SE1", "Restaurant", 55),
    ("cafes South Bank Centre London SE1", "Cafe", 40),
    ("restaurants National Theatre London SE1", "Restaurant", 45),
    ("cafes National Theatre London SE1", "Cafe", 30),
    ("restaurants Tate Modern London SE1", "Restaurant", 50),
    ("cafes Tate Modern London SE1", "Cafe", 35),
    ("restaurants British Museum London WC1", "Restaurant", 45),
    ("cafes British Museum London WC1", "Cafe", 30),
    ("restaurants Victoria and Albert Museum London SW7", "Restaurant", 45),
    ("cafes Victoria and Albert Museum London SW7", "Cafe", 30),
    ("restaurants Natural History Museum London SW7", "Restaurant", 40),
    ("restaurants Science Museum London SW7", "Restaurant", 40),
    ("restaurants National Gallery London WC2", "Restaurant", 45),
    ("restaurants Tate Britain London SW1", "Restaurant", 40),
    ("cafes Tate Britain London SW1", "Cafe", 25),
    ("restaurants Saatchi Gallery London SW3", "Restaurant", 35),
    ("restaurants Serpentine Gallery London W2", "Restaurant", 35),

    # Garden centres and farm shops with cafes
    ("garden centre cafe London", "Cafe", 40),
    ("farm shop cafe London", "Cafe", 40),
    ("plant nursery cafe London", "Cafe", 35),
    ("garden cafe London", "Cafe", 40),
    ("Kew Gardens cafe London TW9", "Cafe", 35),
    ("garden centre restaurant London", "Restaurant", 35),

    # Sports clubs with restaurants / clubhouses
    ("golf club restaurant London", "Restaurant", 45),
    ("sports club restaurant London", "Restaurant", 40),
    ("cricket club restaurant London", "Restaurant", 35),
    ("lawn tennis club restaurant London", "Restaurant", 35),
    ("rowing club bar London", "Bar", 30),
    ("yacht club bar London", "Bar", 25),

    # Pub dining / gastro pubs
    ("gastropub London", "Restaurant", 60),
    ("pub restaurant London", "Restaurant", 55),
    ("gastro pub London EC1", "Restaurant", 40),
    ("gastro pub London SE1", "Restaurant", 40),
    ("gastro pub London N1", "Restaurant", 40),
    ("gastro pub London E8", "Restaurant", 40),
    ("gastro pub London SW4", "Restaurant", 40),
    ("gastro pub London W4", "Restaurant", 35),
    ("gastro pub London NW1", "Restaurant", 40),
    ("Sunday roast pub London", "Restaurant", 55),
    ("Sunday roast London E8", "Restaurant", 35),
    ("Sunday roast London SE15", "Restaurant", 35),
    ("Sunday roast London SW9", "Restaurant", 35),
    ("Sunday roast London N1", "Restaurant", 35),
    ("pub food London", "Restaurant", 50),

    # Private dining / event catering
    ("private dining London", "Restaurant", 50),
    ("private dining room London", "Restaurant", 50),
    ("event catering London", "Catering", 50),
    ("wedding catering London", "Catering", 50),
    ("corporate event catering London", "Catering", 45),
    ("party catering London", "Catering", 45),
    ("mobile catering London", "Catering", 40),
    ("outdoor catering London", "Catering", 40),
    ("street food catering London events", "Catering", 40),
    ("bbq catering London", "Catering", 40),
    ("buffet catering London", "Catering", 45),
    ("canape catering London", "Catering", 40),
    ("finger food catering London", "Catering", 40),
    ("food truck hire London", "Catering", 40),

    # Meal prep / meal kit / food delivery businesses
    ("meal prep service London", "Restaurant", 40),
    ("meal kit delivery London", "Restaurant", 40),
    ("healthy meal delivery London", "Restaurant", 40),
    ("diet meal delivery London", "Restaurant", 35),
    ("vegan meal delivery London", "Restaurant", 40),
    ("office lunch delivery London", "Catering", 40),
    ("sandwich delivery London", "Catering", 40),
    ("lunch delivery service London EC1", "Catering", 35),
    ("lunch delivery service London EC2", "Catering", 35),
    ("lunch delivery service London WC1", "Catering", 35),
    ("lunch delivery service London E1", "Catering", 35),

    # Food halls and large dining destinations
    ("food hall London", "Restaurant", 50),
    ("dining hall London", "Restaurant", 45),
    ("Mercato Metropolitano London SE1", "Restaurant", 40),
    ("Boxpark London Shoreditch", "Restaurant", 45),
    ("Boxpark London Croydon", "Restaurant", 40),
    ("Boxpark London Wembley", "Restaurant", 40),
    ("Westfield food court London W12", "Restaurant", 45),
    ("Westfield Stratford food London E20", "Restaurant", 45),
    ("Canary Wharf food outlets London E14", "Restaurant", 50),
    ("Coal Drops Yard London N1C", "Restaurant", 50),
    ("Granary Square London N1C", "Restaurant", 50),
    ("Kings Cross food London N1", "Restaurant", 50),
    ("Old Spitalfields Market food London E1", "Restaurant", 50),
    ("Exmouth Market food London EC1", "Restaurant", 50),
    ("Kerb market food London", "Restaurant", 45),
    ("Flat Iron Square London SE1", "Restaurant", 45),
    ("Arcade Food Hall London WC2", "Restaurant", 40),
    ("Eataly London EC2", "Restaurant", 40),

    # More train station / transport hub cafes
    ("restaurants Clapham Junction station London SW11", "Restaurant", 50),
    ("cafes Clapham Junction station London SW11", "Cafe", 35),
    ("restaurants Wimbledon station London SW19", "Restaurant", 45),
    ("cafes Wimbledon station London SW19", "Cafe", 30),
    ("restaurants Croydon East Croydon station London", "Restaurant", 50),
    ("cafes East Croydon station London CR0", "Cafe", 35),
    ("restaurants Stratford station London E15", "Restaurant", 55),
    ("cafes Stratford station London E15", "Cafe", 35),
    ("restaurants Canary Wharf station London E14", "Restaurant", 55),
    ("cafes Canary Wharf station London E14", "Cafe", 35),
    ("restaurants Bromley South station London BR1", "Restaurant", 40),
    ("cafes Bromley South station London BR1", "Cafe", 25),
    ("restaurants Ealing Broadway station London W5", "Restaurant", 45),
    ("cafes Ealing Broadway station London W5", "Cafe", 30),
    ("restaurants Richmond station London TW9", "Restaurant", 45),
    ("cafes Richmond station London TW9", "Cafe", 30),
    ("restaurants Kingston station London KT1", "Restaurant", 45),
    ("cafes Kingston station London KT1", "Cafe", 30),
    ("restaurants Hammersmith station London W6", "Restaurant", 50),
    ("cafes Hammersmith station London W6", "Cafe", 30),
    ("restaurants Shepherd's Bush station London W12", "Restaurant", 50),
    ("cafes Shepherd's Bush station London W12", "Cafe", 30),
    ("restaurants Ilford station London IG1", "Restaurant", 40),
    ("cafes Ilford station London IG1", "Cafe", 25),
    ("restaurants Romford station London RM1", "Restaurant", 40),
    ("cafes Romford station London RM1", "Cafe", 25),
]
