"""
Batch 67 - Chinese, Japanese, Korean, Vietnamese, Thai, Pan-Asian cuisine x London
Covers: Chinese dim sum/restaurants, Japanese sushi/ramen/izakaya, Korean BBQ,
Vietnamese pho, Thai restaurants across London postcodes and areas.
"""

SEARCH_QUERIES = [
    # Chinese restaurants x London postcodes
    "Chinese restaurants E1 London",
    "Chinese restaurants E2 London",
    "Chinese restaurants E8 London",
    "Chinese restaurants E14 London",
    "Chinese restaurants N1 London",
    "Chinese restaurants N4 London",
    "Chinese restaurants N16 London",
    "Chinese restaurants SE1 London",
    "Chinese restaurants SE5 London",
    "Chinese restaurants SE10 London",
    "Chinese restaurants SE15 London",
    "Chinese restaurants SW4 London",
    "Chinese restaurants SW9 London",
    "Chinese restaurants SW12 London",
    "Chinese restaurants SW17 London",
    "Chinese restaurants W1 London",
    "Chinese restaurants W2 London",
    "Chinese restaurants W5 London",
    "Chinese restaurants W12 London",
    "Chinese restaurants WC2 London",
    "Chinese restaurants EC1 London",
    "Chinese restaurants NW1 London",
    "Chinese restaurants NW3 London",
    "Chinese restaurants NW6 London",
    "Chinese restaurants NW10 London",
    # Chinese x specific neighborhoods/areas
    "Chinese restaurants Chinatown London W1",
    "Chinese restaurants Soho London W1",
    "Chinese restaurants Bayswater London W2",
    "Chinese restaurants Hackney London",
    "Chinese restaurants Dalston London",
    "Chinese restaurants Peckham London",
    "Chinese restaurants Brixton London",
    "Chinese restaurants Golders Green London",
    "Chinese restaurants Wembley London",
    "Chinese restaurants Ilford London",
    "Chinese restaurants Barking London",
    # Dim sum x London
    "dim sum London W1",
    "dim sum London WC2",
    "dim sum London E1",
    "dim sum London EC1",
    "dim sum London N1",
    "dim sum London SE1",
    "dim sum London SW1",
    "dim sum London NW1",
    "dim sum Chinatown London",
    "dim sum Soho London",
    "dim sum Bayswater London",
    "dim sum Canary Wharf London",
    "dim sum Hackney London",
    # Japanese restaurants x London postcodes
    "Japanese restaurants E1 London",
    "Japanese restaurants E2 London",
    "Japanese restaurants E8 London",
    "Japanese restaurants N1 London",
    "Japanese restaurants N4 London",
    "Japanese restaurants SE1 London",
    "Japanese restaurants SE10 London",
    "Japanese restaurants SW3 London",
    "Japanese restaurants SW7 London",
    "Japanese restaurants W1 London",
    "Japanese restaurants W2 London",
    "Japanese restaurants W4 London",
    "Japanese restaurants W6 London",
    "Japanese restaurants W8 London",
    "Japanese restaurants WC2 London",
    "Japanese restaurants EC1 London",
    "Japanese restaurants EC2 London",
    "Japanese restaurants NW1 London",
    "Japanese restaurants NW3 London",
    # Japanese x specific areas
    "Japanese restaurants Soho London",
    "Japanese restaurants Mayfair London",
    "Japanese restaurants Shoreditch London",
    "Japanese restaurants Brixton London",
    "Japanese restaurants Hackney London",
    "Japanese restaurants Dalston London",
    "Japanese restaurants Notting Hill London",
    "Japanese restaurants Chelsea London",
    "Japanese restaurants Canary Wharf London",
    "Japanese restaurants Fitzrovia London",
    "Japanese restaurants Covent Garden London",
    # Sushi x London
    "sushi restaurant E1 London",
    "sushi restaurant N1 London",
    "sushi restaurant SE1 London",
    "sushi restaurant SW3 London",
    "sushi restaurant SW7 London",
    "sushi restaurant W1 London",
    "sushi restaurant W4 London",
    "sushi restaurant WC2 London",
    "sushi restaurant EC1 London",
    "sushi restaurant EC2 London",
    "sushi restaurant NW1 London",
    "sushi restaurant NW3 London",
    "sushi bar Soho London",
    "sushi bar Shoreditch London",
    "sushi bar Brixton London",
    "sushi bar Camden London",
    "sushi bar Hackney London",
    "sushi bar Mayfair London",
    "sushi bar Chelsea London",
    "sushi bar Notting Hill London",
    # Ramen x London
    "ramen restaurant London E1",
    "ramen restaurant London N1",
    "ramen restaurant London SE1",
    "ramen restaurant London SW9",
    "ramen restaurant London W1",
    "ramen restaurant London WC2",
    "ramen restaurant London EC1",
    "ramen restaurant London NW1",
    "ramen Soho London",
    "ramen Shoreditch London",
    "ramen Brixton London",
    "ramen Hackney London",
    "ramen Camden London",
    "ramen Dalston London",
    "ramen Covent Garden London",
    # Izakaya x London
    "izakaya London W1",
    "izakaya London WC2",
    "izakaya London EC1",
    "izakaya London E1",
    "izakaya London N1",
    "izakaya London SE1",
    "izakaya London NW1",
    "izakaya Soho London",
    "izakaya Shoreditch London",
    "Japanese bar London W1",
    # Korean restaurants x London postcodes
    "Korean restaurants E1 London",
    "Korean restaurants N1 London",
    "Korean restaurants N4 London",
    "Korean restaurants SE1 London",
    "Korean restaurants SE5 London",
    "Korean restaurants SW9 London",
    "Korean restaurants W1 London",
    "Korean restaurants W2 London",
    "Korean restaurants WC2 London",
    "Korean restaurants EC1 London",
    "Korean restaurants NW1 London",
    # Korean x specific areas
    "Korean restaurants Soho London",
    "Korean restaurants New Malden London KT3",
    "Korean restaurants New Malden London",
    "Korean BBQ London W1",
    "Korean BBQ London WC2",
    "Korean BBQ London E1",
    "Korean BBQ London N1",
    "Korean BBQ London SE1",
    "Korean BBQ Soho London",
    "Korean BBQ New Malden London",
    "Korean BBQ Covent Garden London",
    "Korean fried chicken London W1",
    "Korean fried chicken London E1",
    "Korean fried chicken London N1",
    "Korean fried chicken London SE1",
    "Korean fried chicken Soho London",
    # Vietnamese restaurants x London postcodes
    "Vietnamese restaurants E1 London",
    "Vietnamese restaurants E2 London",
    "Vietnamese restaurants E8 London",
    "Vietnamese restaurants N1 London",
    "Vietnamese restaurants N4 London",
    "Vietnamese restaurants N16 London",
    "Vietnamese restaurants SE1 London",
    "Vietnamese restaurants SE5 London",
    "Vietnamese restaurants SE15 London",
    "Vietnamese restaurants SW9 London",
    "Vietnamese restaurants W1 London",
    "Vietnamese restaurants WC2 London",
    "Vietnamese restaurants EC1 London",
    "Vietnamese restaurants NW1 London",
    # Vietnamese x areas
    "Vietnamese restaurants Shoreditch London",
    "Vietnamese restaurants Hackney London",
    "Vietnamese restaurants Dalston London",
    "Vietnamese restaurants Brixton London",
    "Vietnamese restaurants Camden London",
    "Vietnamese restaurants Peckham London",
    "Vietnamese restaurants Kingsland Road London",
    "pho restaurant London E1",
    "pho restaurant London E8",
    "pho restaurant London N1",
    "pho restaurant London SE1",
    "pho restaurant London SW9",
    "pho restaurant London W1",
    "pho restaurant London WC2",
    "pho restaurant Shoreditch London",
    "pho restaurant Hackney London",
    "pho restaurant Dalston London",
    "pho restaurant Brixton London",
    "pho restaurant Kingsland Road London",
    # Thai restaurants x London postcodes
    "Thai restaurants E1 London",
    "Thai restaurants E8 London",
    "Thai restaurants N1 London",
    "Thai restaurants N4 London",
    "Thai restaurants N16 London",
    "Thai restaurants SE1 London",
    "Thai restaurants SE5 London",
    "Thai restaurants SE15 London",
    "Thai restaurants SW9 London",
    "Thai restaurants SW11 London",
    "Thai restaurants W1 London",
    "Thai restaurants W4 London",
    "Thai restaurants W6 London",
    "Thai restaurants W11 London",
    "Thai restaurants WC2 London",
    "Thai restaurants EC1 London",
    "Thai restaurants NW1 London",
    "Thai restaurants NW3 London",
    # Thai x areas
    "Thai restaurants Shoreditch London",
    "Thai restaurants Hackney London",
    "Thai restaurants Brixton London",
    "Thai restaurants Clapham London",
    "Thai restaurants Notting Hill London",
    "Thai restaurants Chiswick London",
    "Thai restaurants Richmond London",
    "Thai restaurants Camden London",
    "Thai restaurants Islington London",
    "Thai restaurants Dalston London",
    "Thai restaurants Peckham London",
    # Pan-Asian and fusion
    "Pan-Asian restaurant London W1",
    "Pan-Asian restaurant London WC2",
    "Pan-Asian restaurant London EC1",
    "Pan-Asian restaurant London E1",
    "Pan-Asian restaurant London SE1",
    "Pan-Asian restaurant London SW1",
    "Pan-Asian restaurant London NW1",
    "Asian fusion restaurant London W1",
    "Asian fusion restaurant London WC2",
    "Asian fusion restaurant London EC1",
    "Asian fusion restaurant London E1",
    "Asian fusion restaurant London SE1",
    "Asian fusion restaurant London N1",
    "Asian fusion restaurant London NW1",
    "Asian fusion London Shoreditch",
    "Asian fusion London Brixton",
    "Asian fusion London Hackney",
    "noodle bar London E1",
    "noodle bar London N1",
    "noodle bar London SE1",
    "noodle bar London W1",
    "noodle bar London WC2",
    "noodle bar London EC1",
    "noodle bar London NW1",
    "noodle bar Soho London",
    "noodle bar Shoreditch London",
    "noodle bar Brixton London",
    # Taiwanese restaurants x London
    "Taiwanese restaurant London W1",
    "Taiwanese restaurant London WC2",
    "Taiwanese restaurant London E1",
    "Taiwanese restaurant London N1",
    "Taiwanese restaurant London SE1",
    "Taiwanese restaurant London NW1",
    # Filipino restaurants x London
    "Filipino restaurant London E1",
    "Filipino restaurant London N1",
    "Filipino restaurant London SE1",
    "Filipino restaurant London SW9",
    "Filipino restaurant London W1",
    "Filipino restaurant London NW1",
]
