"""
Batch 72 - Specific London neighborhoods not just postcodes: high-density food streets,
village-style areas, market streets, cultural corridors.
Dalston, Stoke Newington, Walthamstow, Leytonstone, Bethnal Green, Whitechapel, etc.
"""

SEARCH_QUERIES = [
    # Dalston / Kingsland Road corridor
    "restaurants Dalston London E8",
    "cafes Dalston London E8",
    "restaurants Kingsland Road London E8",
    "cafes Kingsland Road London E8",
    "restaurants Ridley Road London E8",
    "cafes Ridley Road Market London E8",
    "restaurants Stoke Newington Road London N16",
    "cafes Stoke Newington Road London N16",
    "restaurants Shacklewell Lane London E8",
    "restaurants Gillett Square London E8",
    "restaurants Dalston Junction London E8",
    "vegan restaurants Dalston London",
    "Turkish restaurants Dalston London",
    "Vietnamese restaurants Dalston London",
    "brunch Dalston London",
    "wine bar Dalston London",
    "cocktail bar Dalston London",
    "cafes Stoke Newington London N16",
    "restaurants Stoke Newington London N16",
    "restaurants Church Street Stoke Newington London N16",
    "cafes Church Street Stoke Newington London N16",
    "restaurants Stoke Newington High Street London N16",
    "vegan restaurant Stoke Newington London",
    "brunch Stoke Newington London",
    # Walthamstow
    "restaurants Walthamstow London E17",
    "cafes Walthamstow London E17",
    "restaurants Walthamstow Village London E17",
    "cafes Walthamstow Village London E17",
    "restaurants Hoe Street Walthamstow London E17",
    "cafes Hoe Street Walthamstow London E17",
    "restaurants Wood Street Walthamstow London E17",
    "cafes Wood Street Walthamstow London E17",
    "restaurants Walthamstow Market London E17",
    "brunch Walthamstow London E17",
    "vegan restaurant Walthamstow London",
    "pizza restaurant Walthamstow London E17",
    "Indian restaurant Walthamstow London E17",
    "Turkish restaurant Walthamstow London E17",
    # Leytonstone / Leyton
    "restaurants Leytonstone London E11",
    "cafes Leytonstone London E11",
    "restaurants High Road Leytonstone London E11",
    "cafes High Road Leytonstone London E11",
    "restaurants Leyton London E10",
    "cafes Leyton London E10",
    "restaurants Leyton High Road London E10",
    "restaurants Francis Road Leyton London E10",
    "brunch Leytonstone London E11",
    "brunch Leyton London E10",
    "pizza restaurant Leytonstone London",
    "Indian restaurant Leytonstone London",
    # Bethnal Green
    "restaurants Bethnal Green London E2",
    "cafes Bethnal Green London E2",
    "restaurants Bethnal Green Road London E2",
    "cafes Bethnal Green Road London E2",
    "restaurants Cambridge Heath London E2",
    "cafes Cambridge Heath London E2",
    "restaurants Museum of Childhood London E2",
    "brunch Bethnal Green London",
    "pizza restaurant Bethnal Green London E2",
    "vegan restaurant Bethnal Green London",
    "Turkish restaurant Bethnal Green London",
    "Vietnamese restaurant Bethnal Green London",
    "cocktail bar Bethnal Green London",
    "wine bar Bethnal Green London",
    # Whitechapel / Stepney
    "restaurants Whitechapel London E1",
    "cafes Whitechapel London E1",
    "restaurants Whitechapel Road London E1",
    "cafes Whitechapel Road London E1",
    "restaurants Commercial Road London E1",
    "cafes Commercial Road London E1",
    "restaurants Mile End London E1",
    "cafes Mile End London E1",
    "Indian restaurants Whitechapel London E1",
    "Bangladeshi restaurants Whitechapel London",
    "halal restaurants Whitechapel London",
    "Turkish restaurants Whitechapel London",
    # Bow / Stratford
    "restaurants Bow London E3",
    "cafes Bow London E3",
    "restaurants Bow Road London E3",
    "cafes Bow Road London E3",
    "restaurants Roman Road London E3",
    "cafes Roman Road Market London E3",
    "restaurants Stratford London E15",
    "cafes Stratford London E15",
    "restaurants Stratford High Street London E15",
    "brunch Stratford London",
    "brunch Bow London",
    "vegan restaurant Stratford London",
    "pizza restaurant Stratford London E15",
    # Forest Gate / Manor Park
    "restaurants Forest Gate London E7",
    "cafes Forest Gate London E7",
    "restaurants Woodgrange Road London E7",
    "cafes Woodgrange Road London E7",
    "restaurants Manor Park London E12",
    "cafes Manor Park London E12",
    "Indian restaurants Forest Gate London",
    "halal restaurants Forest Gate London",
    "halal restaurants Manor Park London",
    # Clapton / Lower Clapton
    "restaurants Clapton London E5",
    "cafes Clapton London E5",
    "restaurants Lower Clapton Road London E5",
    "cafes Lower Clapton Road London E5",
    "restaurants Upper Clapton Road London E5",
    "restaurants Chatsworth Road London E5",
    "cafes Chatsworth Road London E5",
    "brunch Clapton London",
    "vegan restaurant Clapton London",
    "pizza restaurant Clapton London",
    # Homerton / Hackney Wick
    "restaurants Homerton London E9",
    "cafes Homerton London E9",
    "restaurants Hackney Wick London E9",
    "cafes Hackney Wick London E9",
    "restaurants Wallis Road Hackney Wick London E9",
    "cafes Hackney Wick London E20",
    "restaurants Victoria Park London E9",
    "cafes Victoria Park London E3",
    "brunch Hackney Wick London",
    "brunch Victoria Park London",
    "vegan restaurant Hackney Wick London",
    "street food Hackney Wick London",
    # Seven Sisters / Bruce Grove / Tottenham
    "restaurants Seven Sisters London N15",
    "cafes Seven Sisters London N15",
    "restaurants Bruce Grove Tottenham London N17",
    "cafes Bruce Grove Tottenham London N17",
    "restaurants Tottenham High Road London N17",
    "restaurants Philip Lane London N15",
    "restaurants West Green Road London N15",
    "Indian restaurants Seven Sisters London",
    "Turkish restaurants Seven Sisters London",
    "halal restaurants Seven Sisters London",
    "halal restaurants Tottenham London",
    "Caribbean restaurant Tottenham London",
    # Wood Green / Alexandra Palace
    "restaurants Wood Green London N22",
    "cafes Wood Green London N22",
    "restaurants Green Lanes Wood Green London N22",
    "cafes Green Lanes Wood Green London N22",
    "restaurants Alexandra Palace London N22",
    "cafes Alexandra Palace London N22",
    "restaurants Ally Pally London N22",
    "Turkish restaurants Wood Green London",
    "Greek restaurants Wood Green London",
    "pizza restaurant Wood Green London N22",
    "brunch Wood Green London",
    # Finsbury Park / Stroud Green
    "restaurants Finsbury Park London N4",
    "cafes Finsbury Park London N4",
    "restaurants Stroud Green Road London N4",
    "cafes Stroud Green Road London N4",
    "restaurants Crouch Hill London N4",
    "cafes Crouch Hill London N4",
    "restaurants Blackstock Road London N4",
    "cafes Blackstock Road London N4",
    "brunch Finsbury Park London",
    "vegan restaurant Finsbury Park London",
    "Turkish restaurant Finsbury Park London",
    "pizza restaurant Finsbury Park London N4",
    # Hornsey / Crouch End
    "restaurants Crouch End London N8",
    "cafes Crouch End London N8",
    "restaurants The Broadway Crouch End London N8",
    "cafes The Broadway Crouch End London N8",
    "restaurants Hornsey London N8",
    "cafes Hornsey London N8",
    "restaurants Park Road Crouch End London N8",
    "brunch Crouch End London",
    "vegan restaurant Crouch End London",
    "pizza restaurant Crouch End London N8",
    "gastropub Crouch End London",
    # Muswell Hill
    "restaurants Muswell Hill London N10",
    "cafes Muswell Hill London N10",
    "restaurants Muswell Hill Broadway London N10",
    "cafes Muswell Hill Broadway London N10",
    "restaurants Alexandra Park Road London N10",
    "brunch Muswell Hill London",
    "vegan restaurant Muswell Hill London",
    "pizza restaurant Muswell Hill London N10",
    "gastropub Muswell Hill London",
    # Archway / Tufnell Park
    "restaurants Archway London N19",
    "cafes Archway London N19",
    "restaurants Tufnell Park London N19",
    "cafes Tufnell Park London N19",
    "restaurants Holloway Road Archway London N19",
    "brunch Archway London",
    "vegan restaurant Archway London",
    "pizza restaurant Archway London N19",
    # Gospel Oak / Kentish Town
    "restaurants Gospel Oak London NW5",
    "cafes Gospel Oak London NW5",
    "restaurants Kentish Town Road London NW5",
    "cafes Kentish Town Road London NW5",
    "restaurants Dartmouth Park London NW5",
    "brunch Kentish Town London",
    "gastropub Kentish Town London",
    "pizza restaurant Kentish Town London NW5",
    # Twickenham / Richmond outer
    "restaurants Twickenham London TW1",
    "cafes Twickenham London TW1",
    "restaurants Twickenham High Street London TW1",
    "restaurants Richmond Hill London TW10",
    "cafes Richmond Hill London TW10",
    "brunch Twickenham London",
    "gastropub Twickenham London",
    "pizza restaurant Twickenham London TW1",
    # Wimbledon / Raynes Park
    "restaurants Wimbledon London SW19",
    "cafes Wimbledon London SW19",
    "restaurants Wimbledon Village London SW19",
    "cafes Wimbledon Village London SW19",
    "restaurants Raynes Park London SW20",
    "cafes Raynes Park London SW20",
    "brunch Wimbledon London",
    "gastropub Wimbledon London",
    "Italian restaurant Wimbledon London",
    "pizza restaurant Wimbledon London SW19",
    # Kingston upon Thames (inner borough)
    "restaurants Kingston London KT1",
    "cafes Kingston London KT1",
    "restaurants Kingston High Street London KT1",
    "cafes Kingston High Street London KT1",
    "restaurants Kingston upon Thames London",
    "restaurants Eden Street Kingston London",
    "brunch Kingston London",
    "gastropub Kingston London",
    "pizza restaurant Kingston London KT1",
    "vegan restaurant Kingston London",
]
