"""
Batch 77 - Corporate catering, event catering, wedding catering, office catering,
food delivery services, meal prep, private dining, private chef services across London.
B2B food services focus.
"""

SEARCH_QUERIES = [
    # Corporate catering x London postcodes
    "corporate catering London E1",
    "corporate catering London E2",
    "corporate catering London E14",
    "corporate catering London EC1",
    "corporate catering London EC2",
    "corporate catering London EC3",
    "corporate catering London EC4",
    "corporate catering London WC1",
    "corporate catering London WC2",
    "corporate catering London W1",
    "corporate catering London SW1",
    "corporate catering London SE1",
    "corporate catering London N1",
    "corporate catering London NW1",
    # Corporate catering x business districts
    "corporate catering Canary Wharf London",
    "corporate catering City of London",
    "corporate catering Mayfair London",
    "corporate catering Soho London",
    "corporate catering Shoreditch London",
    "corporate catering Islington London",
    "corporate catering Paddington London",
    "corporate catering Victoria London",
    "corporate catering Westminster London",
    "corporate catering Holborn London",
    "corporate catering Clerkenwell London",
    "corporate catering Farringdon London",
    "corporate catering Moorgate London",
    "corporate catering London Bridge London",
    "corporate catering Southwark London",
    "corporate catering Bermondsey London",
    "corporate catering Vauxhall London",
    "corporate catering Battersea London",
    "corporate catering Hammersmith London",
    "corporate catering Chiswick London",
    "corporate catering Stratford London",
    # Office catering x London
    "office catering London EC1",
    "office catering London EC2",
    "office catering London EC3",
    "office catering London WC1",
    "office catering London WC2",
    "office catering London W1",
    "office catering London SW1",
    "office catering London SE1",
    "office catering London N1",
    "office catering London NW1",
    "office catering London E14",
    "office catering City of London",
    "office catering Canary Wharf London",
    "office catering Shoreditch London",
    "office catering Mayfair London",
    "office catering Victoria London",
    "office catering Paddington London",
    "office catering Holborn London",
    "office catering Clerkenwell London",
    "office catering Hammersmith London",
    "office lunch delivery London EC1",
    "office lunch delivery London EC2",
    "office lunch delivery London WC1",
    "office lunch delivery London WC2",
    "office lunch delivery London W1",
    "office lunch delivery London SW1",
    "office lunch delivery London SE1",
    "office lunch delivery London E14",
    "office lunch delivery London NW1",
    "office lunch delivery City of London",
    "office lunch delivery Canary Wharf London",
    "office lunch delivery Shoreditch London",
    "office sandwich delivery London",
    "office breakfast catering London",
    "office meeting catering London",
    # Event catering x London
    "event catering London E1",
    "event catering London EC1",
    "event catering London EC2",
    "event catering London WC2",
    "event catering London W1",
    "event catering London SW1",
    "event catering London SE1",
    "event catering London N1",
    "event catering London NW1",
    "event catering London E14",
    "event catering City of London",
    "event catering Canary Wharf London",
    "event catering Shoreditch London",
    "event catering Mayfair London",
    "event catering Kensington London",
    "event catering Chelsea London",
    "event catering Westminster London",
    "event catering Southwark London",
    "event catering Bermondsey London",
    "event catering Hackney London",
    "event catering Brixton London",
    "event catering Hammersmith London",
    "party catering London EC1",
    "party catering London W1",
    "party catering London WC2",
    "party catering London SE1",
    "party catering London NW1",
    "party catering London SW1",
    "party catering Shoreditch London",
    "party catering Mayfair London",
    "party catering Chelsea London",
    "party catering Hackney London",
    "party food delivery London",
    # Wedding catering x London
    "wedding catering London SW1",
    "wedding catering London W1",
    "wedding catering London WC2",
    "wedding catering London EC1",
    "wedding catering London SE1",
    "wedding catering London NW1",
    "wedding catering London SW3",
    "wedding catering London SW7",
    "wedding catering London W4",
    "wedding catering London W8",
    "wedding catering London W11",
    "wedding catering London SE10",
    "wedding catering London SE22",
    "wedding catering Kensington London",
    "wedding catering Chelsea London",
    "wedding catering Mayfair London",
    "wedding catering Richmond London",
    "wedding catering Greenwich London",
    "wedding catering Dulwich London",
    "wedding catering Notting Hill London",
    "wedding catering Shoreditch London",
    "wedding catering Hackney London",
    "wedding catering Brixton London",
    "wedding caterer London",
    "wedding breakfast catering London",
    "wedding food London",
    # Private dining x London
    "private dining London E1",
    "private dining London EC1",
    "private dining London EC2",
    "private dining London WC2",
    "private dining London W1",
    "private dining London SW1",
    "private dining London SW3",
    "private dining London SW7",
    "private dining London SE1",
    "private dining London NW1",
    "private dining London NW3",
    "private dining Mayfair London",
    "private dining Soho London",
    "private dining Chelsea London",
    "private dining Kensington London",
    "private dining Knightsbridge London",
    "private dining Covent Garden London",
    "private dining Belgravia London",
    "private dining City of London",
    "private dining Canary Wharf London",
    "private dining Shoreditch London",
    "private dining Brixton London",
    "private dining room London",
    "private dining club London",
    # Private chef x London
    "private chef London W1",
    "private chef London SW1",
    "private chef London SW3",
    "private chef London SW7",
    "private chef London NW3",
    "private chef London NW8",
    "private chef London N1",
    "private chef London SE1",
    "private chef London EC1",
    "private chef London E1",
    "private chef Mayfair London",
    "private chef Chelsea London",
    "private chef Kensington London",
    "private chef Hampstead London",
    "private chef Shoreditch London",
    "private chef Islington London",
    "personal chef London",
    "chef for hire London",
    # Food delivery service x London postcodes
    "food delivery service EC1 London",
    "food delivery service EC2 London",
    "food delivery service EC3 London",
    "food delivery service EC4 London",
    "food delivery service WC1 London",
    "food delivery service WC2 London",
    "food delivery service W1 London",
    "food delivery service W2 London",
    "food delivery service W4 London",
    "food delivery service W6 London",
    "food delivery service W11 London",
    "food delivery service SW1 London",
    "food delivery service SW3 London",
    "food delivery service SW4 London",
    "food delivery service SW6 London",
    "food delivery service SW9 London",
    "food delivery service SW11 London",
    "food delivery service SW12 London",
    "food delivery service SE1 London",
    "food delivery service SE5 London",
    "food delivery service SE10 London",
    "food delivery service SE15 London",
    "food delivery service SE22 London",
    "food delivery service N1 London",
    "food delivery service N4 London",
    "food delivery service N7 London",
    "food delivery service N16 London",
    "food delivery service E1 London",
    "food delivery service E8 London",
    "food delivery service E14 London",
    "food delivery service NW1 London",
    "food delivery service NW3 London",
    "food delivery service NW6 London",
    # Meal prep / meal kit
    "meal prep delivery London",
    "meal prep service London EC1",
    "meal prep service London WC1",
    "meal prep service London W1",
    "meal prep service London SW1",
    "meal prep service London SE1",
    "meal prep service London N1",
    "meal prep service London NW1",
    "meal prep service London E1",
    "healthy meal delivery London",
    "healthy meal prep London",
    "meal kit delivery London",
    # Catering company x London
    "catering company London EC1",
    "catering company London EC2",
    "catering company London WC1",
    "catering company London W1",
    "catering company London SW1",
    "catering company London SE1",
    "catering company London N1",
    "catering company London NW1",
    "catering company London E1",
    "catering company London E14",
    "catering company City of London",
    "catering company Canary Wharf London",
    "catering company Shoreditch London",
    "catering company Mayfair London",
    "catering company Chelsea London",
    "catering company Kensington London",
    "catering service London",
    "outside catering London",
    "drop-off catering London",
    "grazing table London",
    "grazing platter London",
    "food truck hire London",
    "food van hire London",
    "pop-up catering London",
    "buffet catering London",
]
