"""
Batch 69 - Gastropubs, wine bars, cocktail bars, rooftop venues, food halls x London
Covers: gastropubs across all London areas, wine bars, natural wine bars, cocktail bars,
rooftop restaurants/bars, food halls, street food markets, supper clubs.
"""

SEARCH_QUERIES = [
    # Gastropub x London postcodes
    "gastropub London E1",
    "gastropub London E2",
    "gastropub London E3",
    "gastropub London E5",
    "gastropub London E8",
    "gastropub London E9",
    "gastropub London E10",
    "gastropub London E11",
    "gastropub London E14",
    "gastropub London E15",
    "gastropub London E17",
    "gastropub London N1",
    "gastropub London N4",
    "gastropub London N5",
    "gastropub London N6",
    "gastropub London N7",
    "gastropub London N8",
    "gastropub London N10",
    "gastropub London N16",
    "gastropub London N19",
    "gastropub London SE1",
    "gastropub London SE5",
    "gastropub London SE8",
    "gastropub London SE10",
    "gastropub London SE15",
    "gastropub London SE22",
    "gastropub London SE24",
    "gastropub London SW1",
    "gastropub London SW4",
    "gastropub London SW6",
    "gastropub London SW9",
    "gastropub London SW11",
    "gastropub London SW12",
    "gastropub London SW15",
    "gastropub London SW18",
    "gastropub London W1",
    "gastropub London W4",
    "gastropub London W6",
    "gastropub London W8",
    "gastropub London W11",
    "gastropub London W12",
    "gastropub London WC1",
    "gastropub London WC2",
    "gastropub London EC1",
    "gastropub London EC2",
    "gastropub London EC4",
    "gastropub London NW1",
    "gastropub London NW3",
    "gastropub London NW5",
    "gastropub London NW6",
    "gastropub London NW8",
    # Gastropub x areas
    "gastropub Shoreditch London",
    "gastropub Hackney London",
    "gastropub Dalston London",
    "gastropub Islington London",
    "gastropub Brixton London",
    "gastropub Peckham London",
    "gastropub Bermondsey London",
    "gastropub Battersea London",
    "gastropub Clapham London",
    "gastropub Fulham London",
    "gastropub Chelsea London",
    "gastropub Notting Hill London",
    "gastropub Hammersmith London",
    "gastropub Chiswick London",
    "gastropub Wimbledon London",
    "gastropub Richmond London",
    "gastropub Greenwich London",
    "gastropub Dulwich London",
    "gastropub Lewisham London",
    "gastropub New Cross London",
    "gastropub Forest Hill London",
    "gastropub Stoke Newington London",
    "gastropub Muswell Hill London",
    "gastropub Crouch End London",
    "gastropub Highbury London",
    "gastropub Archway London",
    "gastropub Kentish Town London",
    "gastropub Primrose Hill London",
    "gastropub Mayfair London",
    "gastropub Soho London",
    "gastropub Fitzrovia London",
    "gastropub Bloomsbury London",
    "gastropub Clerkenwell London",
    "gastropub Farringdon London",
    "gastropub Borough London",
    "gastropub London Bridge London",
    "gastropub Bankside London",
    "gastropub Wapping London",
    "gastropub Bermondsey Street London",
    "gastropub Tooting London",
    "gastropub Streatham London",
    "gastropub Putney London",
    "gastropub Wandsworth London",
    "gastropub Barnes London",
    "gastropub Acton London",
    "gastropub Shepherd's Bush London",
    # Wine bar x London postcodes
    "wine bar London E1",
    "wine bar London E8",
    "wine bar London N1",
    "wine bar London N4",
    "wine bar London N16",
    "wine bar London SE1",
    "wine bar London SE5",
    "wine bar London SE15",
    "wine bar London SE22",
    "wine bar London SW1",
    "wine bar London SW3",
    "wine bar London SW4",
    "wine bar London SW6",
    "wine bar London SW11",
    "wine bar London W1",
    "wine bar London W4",
    "wine bar London W8",
    "wine bar London W11",
    "wine bar London WC2",
    "wine bar London EC1",
    "wine bar London EC2",
    "wine bar London EC4",
    "wine bar London NW1",
    "wine bar London NW3",
    # Wine bar x areas
    "wine bar Soho London",
    "wine bar Mayfair London",
    "wine bar Covent Garden London",
    "wine bar Chelsea London",
    "wine bar Shoreditch London",
    "wine bar Islington London",
    "wine bar Brixton London",
    "wine bar Hackney London",
    "wine bar Dalston London",
    "wine bar Bermondsey London",
    "wine bar Borough London",
    "wine bar Clapham London",
    "wine bar Battersea London",
    "wine bar Notting Hill London",
    "wine bar Chiswick London",
    "wine bar Fitzrovia London",
    "wine bar Clerkenwell London",
    "wine bar Farringdon London",
    "wine bar Peckham London",
    "wine bar Dulwich London",
    # Natural wine bar x London
    "natural wine bar London E1",
    "natural wine bar London E8",
    "natural wine bar London N1",
    "natural wine bar London N16",
    "natural wine bar London SE1",
    "natural wine bar London SE15",
    "natural wine bar London SW4",
    "natural wine bar London SW11",
    "natural wine bar London W1",
    "natural wine bar London WC2",
    "natural wine bar London EC1",
    "natural wine bar London NW1",
    "natural wine bar Shoreditch London",
    "natural wine bar Hackney London",
    "natural wine bar Brixton London",
    "natural wine bar Dalston London",
    "natural wine bar Peckham London",
    "natural wine bar Bermondsey London",
    "natural wine bar Islington London",
    # Cocktail bar x London postcodes
    "cocktail bar London E1",
    "cocktail bar London E8",
    "cocktail bar London N1",
    "cocktail bar London N4",
    "cocktail bar London SE1",
    "cocktail bar London SE5",
    "cocktail bar London SE15",
    "cocktail bar London SW4",
    "cocktail bar London SW9",
    "cocktail bar London SW11",
    "cocktail bar London W1",
    "cocktail bar London W4",
    "cocktail bar London W11",
    "cocktail bar London WC2",
    "cocktail bar London EC1",
    "cocktail bar London EC2",
    "cocktail bar London NW1",
    "cocktail bar London NW3",
    # Cocktail bar x areas
    "cocktail bar Soho London",
    "cocktail bar Shoreditch London",
    "cocktail bar Brixton London",
    "cocktail bar Hackney London",
    "cocktail bar Dalston London",
    "cocktail bar Mayfair London",
    "cocktail bar Chelsea London",
    "cocktail bar Notting Hill London",
    "cocktail bar Clapham London",
    "cocktail bar Camden London",
    "cocktail bar Islington London",
    "cocktail bar Bermondsey London",
    "cocktail bar Peckham London",
    "cocktail bar Fitzrovia London",
    # Rooftop restaurant/bar x London
    "rooftop restaurant London E1",
    "rooftop restaurant London SE1",
    "rooftop restaurant London SW1",
    "rooftop restaurant London W1",
    "rooftop restaurant London WC2",
    "rooftop restaurant London EC1",
    "rooftop restaurant London EC2",
    "rooftop restaurant London NW1",
    "rooftop bar London E1",
    "rooftop bar London SE1",
    "rooftop bar London SW1",
    "rooftop bar London W1",
    "rooftop bar London WC2",
    "rooftop bar London EC1",
    "rooftop bar London EC2",
    "rooftop bar Shoreditch London",
    "rooftop bar Brixton London",
    "rooftop bar Hackney London",
    "rooftop bar Peckham London",
    "rooftop bar Islington London",
    "rooftop bar Chelsea London",
    "rooftop bar Mayfair London",
    "rooftop dining London",
    "rooftop terrace restaurant London",
    # Food hall x London
    "food hall London E1",
    "food hall London SE1",
    "food hall London SW1",
    "food hall London W1",
    "food hall London WC2",
    "food hall London EC1",
    "food hall London EC2",
    "food hall London NW1",
    "food hall Shoreditch London",
    "food hall Brixton London",
    "food hall Hackney London",
    "food hall Dalston London",
    "food hall Peckham London",
    "food hall Bermondsey London",
    "food hall Borough London",
    "food hall Canary Wharf London",
    "food hall Battersea London",
    "food hall Stratford London",
    # Street food market x London
    "street food market London E1",
    "street food market London SE1",
    "street food market London N1",
    "street food market London SW9",
    "street food market London W1",
    "street food market London EC1",
    "street food market London NW1",
    "street food market Shoreditch London",
    "street food market Brixton London",
    "street food market Hackney London",
    "street food market Dalston London",
    "street food market Peckham London",
    "street food market Bermondsey London",
    "street food market Camden London",
    "street food market Notting Hill London",
    # Supper club / pop-up dining
    "supper club London E1",
    "supper club London N1",
    "supper club London SE1",
    "supper club London SW9",
    "supper club London W1",
    "supper club London WC2",
    "supper club London NW1",
    "pop-up restaurant London Shoreditch",
    "pop-up restaurant London Brixton",
    "pop-up restaurant London Hackney",
    "pop-up restaurant London Dalston",
    "pop-up restaurant London Peckham",
    "pop-up dining London E1",
    "pop-up dining London SE1",
    "pop-up dining London N1",
    "pop-up dining London W1",
    # Late night restaurants x London
    "late night restaurant London E1",
    "late night restaurant London N1",
    "late night restaurant London SE1",
    "late night restaurant London SW1",
    "late night restaurant London W1",
    "late night restaurant London WC2",
    "late night restaurant London EC1",
    "late night restaurant London NW1",
    "late night restaurant Soho London",
    "late night restaurant Shoreditch London",
    "late night restaurant Brixton London",
    "late night restaurant Camden London",
    "late night dining London",
    "late night cafe London E1",
    "late night cafe London N1",
    "late night cafe London SE1",
    "late night cafe London W1",
    "late night cafe London WC2",
]
