"""
Batch 66 - Indian, Pakistani, Bangladeshi, Sri Lankan cuisine x London postcodes/areas
Covers: Indian restaurants/curry houses, Pakistani, Bangladeshi, Sri Lankan,
plus halal, biryani, tandoori across inner and outer London zones.
"""

SEARCH_QUERIES = [
    # Indian restaurants x inner East London
    "Indian restaurants E1 London",
    "Indian restaurants E2 London",
    "Indian restaurants E3 London",
    "Indian restaurants E6 London",
    "Indian restaurants E7 London",
    "Indian restaurants E8 London",
    "Indian restaurants E10 London",
    "Indian restaurants E11 London",
    "Indian restaurants E12 London",
    "Indian restaurants E13 London",
    "Indian restaurants E14 London",
    "Indian restaurants E15 London",
    "Indian restaurants E16 London",
    "Indian restaurants E17 London",
    # Indian restaurants x inner North London
    "Indian restaurants N1 London",
    "Indian restaurants N4 London",
    "Indian restaurants N5 London",
    "Indian restaurants N7 London",
    "Indian restaurants N8 London",
    "Indian restaurants N15 London",
    "Indian restaurants N16 London",
    "Indian restaurants N17 London",
    "Indian restaurants N22 London",
    # Indian restaurants x inner South London
    "Indian restaurants SE1 London",
    "Indian restaurants SE5 London",
    "Indian restaurants SE15 London",
    "Indian restaurants SE16 London",
    "Indian restaurants SE17 London",
    "Indian restaurants SE18 London",
    "Indian restaurants SE25 London",
    "Indian restaurants SW2 London",
    "Indian restaurants SW9 London",
    "Indian restaurants SW12 London",
    "Indian restaurants SW16 London",
    "Indian restaurants SW17 London",
    # Indian restaurants x inner West London
    "Indian restaurants W1 London",
    "Indian restaurants W2 London",
    "Indian restaurants W3 London",
    "Indian restaurants W5 London",
    "Indian restaurants W7 London",
    "Indian restaurants W12 London",
    "Indian restaurants W13 London",
    "Indian restaurants NW1 London",
    "Indian restaurants NW2 London",
    "Indian restaurants NW4 London",
    "Indian restaurants NW6 London",
    "Indian restaurants NW10 London",
    # Indian restaurants x outer London
    "Indian restaurants Harrow London HA1",
    "Indian restaurants Harrow London HA2",
    "Indian restaurants Harrow London HA3",
    "Indian restaurants Southall London UB1",
    "Indian restaurants Southall London UB2",
    "Indian restaurants Wembley London HA9",
    "Indian restaurants Ilford London IG1",
    "Indian restaurants Ilford London IG2",
    "Indian restaurants Ilford London IG3",
    "Indian restaurants Romford London RM1",
    "Indian restaurants Romford London RM2",
    "Indian restaurants East Ham London E6",
    "Indian restaurants Seven Sisters London N15",
    "Indian restaurants Tooting London SW17",
    "Indian restaurants Tooting Broadway London SW17",
    # Curry house searches
    "curry house London E1",
    "curry house London E6",
    "curry house London N1",
    "curry house London SE1",
    "curry house London SE17",
    "curry house London SW9",
    "curry house London SW17",
    "curry house London W1",
    "curry house London WC2",
    "curry house London NW1",
    "curry house London NW6",
    "curry house Brick Lane London",
    "curry house Tooting London",
    "curry house Southall London",
    "curry house Wembley London",
    "curry house Harrow London",
    "curry house Ilford London",
    "curry house East Ham London",
    "curry house Whitechapel London",
    # Pakistani restaurants x London
    "Pakistani restaurants London E1",
    "Pakistani restaurants London E6",
    "Pakistani restaurants London E13",
    "Pakistani restaurants London N1",
    "Pakistani restaurants London N4",
    "Pakistani restaurants London NW1",
    "Pakistani restaurants London NW6",
    "Pakistani restaurants London W1",
    "Pakistani restaurants London W12",
    "Pakistani restaurants London SW17",
    "Pakistani restaurants Whitechapel London",
    "Pakistani restaurants Tooting London",
    "Pakistani restaurants Southall London",
    "Pakistani restaurants Wembley London",
    "Pakistani restaurants Harrow London",
    # Bangladeshi restaurants x London
    "Bangladeshi restaurants London E1",
    "Bangladeshi restaurants London E2",
    "Bangladeshi restaurants London E3",
    "Bangladeshi restaurants London E6",
    "Bangladeshi restaurants London N1",
    "Bangladeshi restaurants London SE1",
    "Bangladeshi restaurants London SW17",
    "Bangladeshi restaurants Brick Lane London",
    "Bangladeshi restaurants Whitechapel London",
    "Bangladeshi restaurants Tower Hamlets London",
    # Sri Lankan restaurants x London
    "Sri Lankan restaurants London E1",
    "Sri Lankan restaurants London SE1",
    "Sri Lankan restaurants London SW17",
    "Sri Lankan restaurants London NW1",
    "Sri Lankan restaurants London W1",
    "Sri Lankan restaurant Tooting London",
    "Sri Lankan restaurant Wembley London",
    "Sri Lankan restaurant Croydon London",
    "Sri Lankan cafe London SW17",
    "Sri Lankan cafe London SE1",
    # Halal restaurants x London postcodes
    "halal restaurants E1 London",
    "halal restaurants E2 London",
    "halal restaurants E6 London",
    "halal restaurants E7 London",
    "halal restaurants E13 London",
    "halal restaurants N1 London",
    "halal restaurants N4 London",
    "halal restaurants N15 London",
    "halal restaurants N17 London",
    "halal restaurants N22 London",
    "halal restaurants SE1 London",
    "halal restaurants SE17 London",
    "halal restaurants SW9 London",
    "halal restaurants SW17 London",
    "halal restaurants W1 London",
    "halal restaurants W12 London",
    "halal restaurants NW1 London",
    "halal restaurants NW6 London",
    "halal restaurants NW10 London",
    "halal restaurants Whitechapel London",
    "halal restaurants Brick Lane London",
    "halal restaurants Tooting London",
    "halal restaurants Southall London",
    "halal restaurants Wembley London",
    "halal restaurants Harrow London",
    "halal restaurants Ilford London",
    "halal restaurants Romford London",
    "halal restaurants East Ham London",
    "halal restaurants Stratford London",
    "halal restaurants Peckham London",
    "halal restaurants Lewisham London",
    "halal restaurants Edmonton London",
    "halal restaurants Wood Green London",
    "halal restaurants Tottenham London",
    "halal restaurants Shepherd's Bush London",
    # Biryani restaurants x London
    "biryani restaurant London E1",
    "biryani restaurant London E6",
    "biryani restaurant London N1",
    "biryani restaurant London SE1",
    "biryani restaurant London SW17",
    "biryani restaurant London W1",
    "biryani restaurant London NW1",
    "biryani restaurant Whitechapel London",
    "biryani restaurant Brick Lane London",
    "biryani restaurant Tooting London",
    "biryani restaurant Southall London",
    "biryani restaurant Wembley London",
    "biryani restaurant Harrow London",
    "biryani restaurant Ilford London",
    # Tandoori restaurants x London
    "tandoori restaurant London E1",
    "tandoori restaurant London N1",
    "tandoori restaurant London SE1",
    "tandoori restaurant London SW9",
    "tandoori restaurant London SW17",
    "tandoori restaurant London W1",
    "tandoori restaurant London NW1",
    "tandoori restaurant Brick Lane London",
    "tandoori restaurant Tooting London",
    "tandoori restaurant Wembley London",
    "tandoori restaurant Harrow London",
    # Dosa / South Indian restaurants
    "dosa restaurant London",
    "South Indian restaurant London SE1",
    "South Indian restaurant London SW17",
    "South Indian restaurant London W1",
    "South Indian restaurant London NW1",
    "South Indian restaurant London E1",
    "South Indian restaurant Tooting London",
    "South Indian restaurant Wembley London",
    "South Indian restaurant Southall London",
    "South Indian restaurant Harrow London",
    "South Indian restaurant Ilford London",
    # Nepalese restaurants x London
    "Nepalese restaurant London E1",
    "Nepalese restaurant London N1",
    "Nepalese restaurant London SE1",
    "Nepalese restaurant London SW17",
    "Nepalese restaurant London NW1",
    "Nepalese restaurant London W1",
    "Nepalese restaurant London EC1",
    "Nepalese restaurant Tooting London",
    "Nepalese restaurant Brixton London",
    "Nepalese restaurant Harrow London",
    "Gurkha restaurant London",
    "Gurkha restaurant London N1",
    "Gurkha restaurant London SE1",
    # Indian sweets / mithai shops
    "Indian sweets London",
    "mithai shop London Southall",
    "mithai shop London Wembley",
    "mithai shop London Harrow",
    "mithai shop London Ilford",
    "Indian sweet shop London E1",
    "Indian sweet shop London NW6",
    "Indian dessert cafe London",
    "falooda London",
    "chaat restaurant London",
    "chaat cafe London E1",
    "chaat cafe London SW17",
    "chaat cafe London Wembley",
    "chaat cafe London Southall",
    "Indian street food London E1",
    "Indian street food London SW17",
    "Indian street food London W1",
    "Indian street food London Wembley",
    "Indian street food London Tooting",
    "Indian vegetarian restaurant London SW17",
    "Indian vegetarian restaurant London Wembley",
    "Indian vegetarian restaurant London Southall",
    "Indian vegetarian restaurant London NW1",
    "Indian vegetarian restaurant London W1",
    # Takeaway searches
    "Indian takeaway E1 London",
    "Indian takeaway N1 London",
    "Indian takeaway SE1 London",
    "Indian takeaway SW9 London",
    "Indian takeaway SW17 London",
    "Indian takeaway W1 London",
    "Indian takeaway NW1 London",
    "Indian takeaway Tooting London",
    "Indian takeaway Brick Lane London",
    "halal takeaway E1 London",
    "halal takeaway N1 London",
    "halal takeaway SE1 London",
    "halal takeaway SW17 London",
    "halal takeaway W12 London",
    "halal takeaway NW10 London",
]
