"""
Batch 55 – Systematic E postcode streets: E1W Wapping, E2 Bethnal Green, E3 Bow, E4 Chingford,
E5 Clapton, E6 East Ham, E7 Forest Gate, E10 Leyton, E11 Leytonstone, E14 Poplar/Isle of Dogs,
E15 Stratford, E17 Walthamstow, E18 South Woodford
"""

SEARCH_QUERIES = [
    # E1W – Wapping
    ("restaurants Wapping High Street London E1W", "Restaurant", 50),
    ("cafes Wapping High Street London E1W", "Cafe", 30),
    ("restaurants Wapping Wall London E1W", "Restaurant", 40),
    ("cafes Wapping Wall London E1W", "Cafe", 25),
    ("restaurants Hermitage Street London E1W", "Restaurant", 40),
    ("cafes Hermitage Street London E1W", "Cafe", 20),
    ("restaurants Scandrett Street London E1W", "Restaurant", 35),
    ("cafes Garnet Street London E1W", "Cafe", 20),
    ("restaurants Thomas More Street London E1W", "Restaurant", 40),
    ("cafes Tench Street London E1W", "Cafe", 20),
    ("restaurants Wapping Lane London E1W", "Restaurant", 45),
    ("cafes Wapping Lane London E1W", "Cafe", 25),
    ("restaurants Raine Street London E1W", "Restaurant", 35),
    ("cafes Prusom Street London E1W", "Cafe", 20),

    # E2 – Bethnal Green more streets
    ("restaurants Cambridge Heath Road London E2", "Restaurant", 55),
    ("cafes Cambridge Heath Road London E2", "Cafe", 35),
    ("restaurants Old Ford Road London E2", "Restaurant", 50),
    ("cafes Old Ford Road London E2", "Cafe", 30),
    ("restaurants Globe Road London E2", "Restaurant", 45),
    ("cafes Globe Road London E2", "Cafe", 25),
    ("restaurants Roman Road London E2", "Restaurant", 55),
    ("cafes Roman Road London E2", "Cafe", 35),
    ("restaurants Hackney Road London E2", "Restaurant", 55),
    ("cafes Hackney Road London E2", "Cafe", 35),
    ("restaurants Bethnal Green Road London E2", "Restaurant", 55),
    ("cafes Bethnal Green Road London E2", "Cafe", 35),
    ("restaurants Vallance Road London E2", "Restaurant", 45),
    ("cafes Vallance Road London E2", "Cafe", 25),
    ("restaurants Gosset Street London E2", "Restaurant", 35),
    ("cafes Gosset Street London E2", "Cafe", 20),
    ("restaurants Cheshire Street London E2", "Restaurant", 45),
    ("cafes Cheshire Street London E2", "Cafe", 30),
    ("restaurants Sclater Street London E2", "Restaurant", 40),
    ("cafes Sclater Street London E2", "Cafe", 25),
    ("restaurants Warner Place London E2", "Restaurant", 35),
    ("cafes Weaver Street London E2", "Cafe", 20),
    ("restaurants Patriot Square London E2", "Restaurant", 35),
    ("cafes Mace Street London E2", "Cafe", 20),
    ("restaurants Arnold Circus London E2", "Restaurant", 40),
    ("cafes Arnold Circus London E2", "Cafe", 25),

    # E3 – Bow more streets
    ("restaurants Bow Road London E3", "Restaurant", 55),
    ("cafes Bow Road London E3", "Cafe", 35),
    ("restaurants Mile End Road London E3", "Restaurant", 55),
    ("cafes Mile End Road London E3", "Cafe", 35),
    ("restaurants Fairfield Road London E3", "Restaurant", 45),
    ("cafes Fairfield Road London E3", "Cafe", 25),
    ("restaurants Tredegar Road London E3", "Restaurant", 40),
    ("cafes Tredegar Road London E3", "Cafe", 20),
    ("restaurants Parnell Road London E3", "Restaurant", 35),
    ("cafes Parnell Road London E3", "Cafe", 20),
    ("restaurants Wick Lane London E3", "Restaurant", 40),
    ("cafes Wick Lane London E3", "Cafe", 20),
    ("restaurants St Stephen's Road London E3", "Restaurant", 35),
    ("cafes St Stephen's Road London E3", "Cafe", 20),
    ("restaurants Mornington Grove London E3", "Restaurant", 35),
    ("cafes Old Ford Road London E3", "Cafe", 25),
    ("restaurants Addington Road London E3", "Restaurant", 35),
    ("cafes Wellington Way London E3", "Cafe", 20),

    # E4 – Chingford more streets
    ("restaurants Chingford Mount Road London E4", "Restaurant", 45),
    ("cafes Chingford Mount Road London E4", "Cafe", 25),
    ("restaurants Hatch Lane London E4", "Restaurant", 40),
    ("cafes Hatch Lane London E4", "Cafe", 20),
    ("restaurants Old Church Road London E4", "Restaurant", 40),
    ("cafes Old Church Road London E4", "Cafe", 20),
    ("restaurants Station Road Chingford London E4", "Restaurant", 45),
    ("cafes Station Road Chingford London E4", "Cafe", 25),
    ("restaurants Friday Hill London E4", "Restaurant", 35),
    ("cafes Friday Hill London E4", "Cafe", 20),
    ("restaurants Highams Park London E4", "Restaurant", 40),
    ("cafes Highams Park London E4", "Cafe", 20),
    ("restaurants The Ridgeway London E4", "Restaurant", 40),
    ("cafes The Ridgeway London E4", "Cafe", 20),
    ("restaurants Lea Valley Road London E4", "Restaurant", 35),
    ("cafes Lea Valley Road London E4", "Cafe", 20),

    # E5 – Clapton more streets
    ("restaurants Upper Clapton Road London E5", "Restaurant", 50),
    ("cafes Upper Clapton Road London E5", "Cafe", 30),
    ("restaurants Lower Clapton Road London E5", "Restaurant", 55),
    ("cafes Lower Clapton Road London E5", "Cafe", 35),
    ("restaurants Clapton Common London E5", "Restaurant", 45),
    ("cafes Clapton Common London E5", "Cafe", 25),
    ("restaurants Kenninghall Road London E5", "Restaurant", 35),
    ("cafes Kenninghall Road London E5", "Cafe", 20),
    ("restaurants Springfield London E5", "Restaurant", 40),
    ("cafes Springfield London E5", "Cafe", 20),
    ("restaurants Powerscroft Road London E5", "Restaurant", 35),
    ("cafes Powerscroft Road London E5", "Cafe", 20),
    ("restaurants Millfields Road London E5", "Restaurant", 40),
    ("cafes Millfields Road London E5", "Cafe", 20),
    ("restaurants Rendlesham Road London E5", "Restaurant", 35),
    ("cafes Rendlesham Road London E5", "Cafe", 20),
    ("restaurants Theydon Road London E5", "Restaurant", 35),
    ("cafes Chatsworth Road London E5", "Cafe", 30),

    # E6 – East Ham more streets
    ("restaurants Barking Road London E6", "Restaurant", 55),
    ("cafes Barking Road London E6", "Cafe", 35),
    ("restaurants High Street North London E6", "Restaurant", 55),
    ("cafes High Street North London E6", "Cafe", 35),
    ("restaurants Green Street London E6", "Restaurant", 50),
    ("cafes Green Street London E6", "Cafe", 30),
    ("restaurants Katherine Road London E6", "Restaurant", 40),
    ("cafes Katherine Road London E6", "Cafe", 20),
    ("restaurants Plashet Grove London E6", "Restaurant", 45),
    ("cafes Plashet Grove London E6", "Cafe", 25),
    ("restaurants Wakefield Street London E6", "Restaurant", 35),
    ("cafes Wakefield Street London E6", "Cafe", 20),
    ("restaurants Frobisher Road London E6", "Restaurant", 35),
    ("cafes Central Park Road London E6", "Cafe", 20),
    ("restaurants Strone Road London E6", "Restaurant", 35),
    ("cafes Priory Road London E6", "Cafe", 20),
    ("restaurants Hartley Avenue London E6", "Restaurant", 35),
    ("cafes Plashet Road London E6", "Cafe", 25),

    # E7 – Forest Gate more streets
    ("restaurants Romford Road London E7", "Restaurant", 55),
    ("cafes Romford Road London E7", "Cafe", 35),
    ("restaurants Woodgrange Road London E7", "Restaurant", 50),
    ("cafes Woodgrange Road London E7", "Cafe", 30),
    ("restaurants Forest Lane London E7", "Restaurant", 40),
    ("cafes Forest Lane London E7", "Cafe", 20),
    ("restaurants Capel Road London E7", "Restaurant", 35),
    ("cafes Capel Road London E7", "Cafe", 20),
    ("restaurants Chestnut Avenue London E7", "Restaurant", 35),
    ("cafes Chestnut Avenue London E7", "Cafe", 20),
    ("restaurants Upton Lane London E7", "Restaurant", 45),
    ("cafes Upton Lane London E7", "Cafe", 25),
    ("restaurants Shrewsbury Road London E7", "Restaurant", 35),
    ("cafes Shrewsbury Road London E7", "Cafe", 20),
    ("restaurants Sebert Road London E7", "Restaurant", 35),
    ("cafes Disraeli Road London E7", "Cafe", 20),
    ("restaurants Hampton Road London E7", "Restaurant", 35),
    ("cafes Portway London E7", "Cafe", 20),

    # E10 – Leyton more streets
    ("restaurants High Road Leyton London E10", "Restaurant", 55),
    ("cafes High Road Leyton London E10", "Cafe", 35),
    ("restaurants Leyton High Road London E10", "Restaurant", 50),
    ("cafes Leyton High Road London E10", "Cafe", 30),
    ("restaurants Lea Bridge Road London E10", "Restaurant", 50),
    ("cafes Lea Bridge Road London E10", "Cafe", 30),
    ("restaurants Ruckholt Road London E10", "Restaurant", 40),
    ("cafes Ruckholt Road London E10", "Cafe", 20),
    ("restaurants Hainault Road London E10", "Restaurant", 35),
    ("cafes Hainault Road London E10", "Cafe", 20),
    ("restaurants Oliver Road London E10", "Restaurant", 35),
    ("cafes Oliver Road London E10", "Cafe", 20),
    ("restaurants Orient Way London E10", "Restaurant", 40),
    ("cafes Orient Way London E10", "Cafe", 20),
    ("restaurants Newport Road London E10", "Restaurant", 35),
    ("cafes Temple Mills Lane London E10", "Cafe", 20),

    # E11 – Leytonstone more streets
    ("restaurants Leytonstone High Road London E11", "Restaurant", 55),
    ("cafes Leytonstone High Road London E11", "Cafe", 35),
    ("restaurants High Road Leytonstone London E11", "Restaurant", 50),
    ("cafes High Road Leytonstone London E11", "Cafe", 30),
    ("restaurants Hollybush Hill London E11", "Restaurant", 40),
    ("cafes Hollybush Hill London E11", "Cafe", 20),
    ("restaurants Harrow Road London E11", "Restaurant", 35),
    ("cafes Harrow Road London E11", "Cafe", 20),
    ("restaurants Langthorne Road London E11", "Restaurant", 35),
    ("cafes Langthorne Road London E11", "Cafe", 20),
    ("restaurants Wanstead Flats London E11", "Restaurant", 35),
    ("cafes Forest Drive London E11", "Cafe", 20),
    ("restaurants Aldersbrook Road London E11", "Restaurant", 40),
    ("cafes Aldersbrook Road London E11", "Cafe", 20),
    ("restaurants Nightingale Lane London E11", "Restaurant", 35),
    ("cafes Grove Green Road London E11", "Cafe", 20),
    ("restaurants James Lane London E11", "Restaurant", 40),
    ("cafes James Lane London E11", "Cafe", 20),

    # E14 – Poplar / Isle of Dogs more streets
    ("restaurants East India Dock Road London E14", "Restaurant", 55),
    ("cafes East India Dock Road London E14", "Cafe", 35),
    ("restaurants Poplar High Street London E14", "Restaurant", 50),
    ("cafes Poplar High Street London E14", "Cafe", 30),
    ("restaurants Chrisp Street London E14", "Restaurant", 50),
    ("cafes Chrisp Street London E14", "Cafe", 30),
    ("restaurants Manchester Road London E14", "Restaurant", 45),
    ("cafes Manchester Road London E14", "Cafe", 25),
    ("restaurants Westferry Road London E14", "Restaurant", 50),
    ("cafes Westferry Road London E14", "Cafe", 30),
    ("restaurants Millwall London E14", "Restaurant", 45),
    ("cafes Millwall London E14", "Cafe", 25),
    ("restaurants Cubitt Town London E14", "Restaurant", 45),
    ("cafes Cubitt Town London E14", "Cafe", 25),
    ("restaurants Marsh Wall London E14", "Restaurant", 50),
    ("cafes Marsh Wall London E14", "Cafe", 30),
    ("restaurants Cotton Street London E14", "Restaurant", 35),
    ("cafes Cotton Street London E14", "Cafe", 20),
    ("restaurants Aberfeldy Street London E14", "Restaurant", 35),
    ("cafes Aberfeldy Street London E14", "Cafe", 20),
    ("restaurants Prestons Road London E14", "Restaurant", 40),
    ("cafes Prestons Road London E14", "Cafe", 20),

    # E15 – Stratford more streets
    ("restaurants Stratford High Street London E15", "Restaurant", 55),
    ("cafes Stratford High Street London E15", "Cafe", 35),
    ("restaurants Broadway Stratford London E15", "Restaurant", 55),
    ("cafes Broadway Stratford London E15", "Cafe", 35),
    ("restaurants Romford Road London E15", "Restaurant", 50),
    ("cafes Romford Road London E15", "Cafe", 30),
    ("restaurants Water Lane London E15", "Restaurant", 40),
    ("cafes Water Lane London E15", "Cafe", 20),
    ("restaurants Leyton Road London E15", "Restaurant", 45),
    ("cafes Leyton Road London E15", "Cafe", 25),
    ("restaurants Carpenter's Road London E15", "Restaurant", 40),
    ("cafes Carpenter's Road London E15", "Cafe", 20),
    ("restaurants West Ham Lane London E15", "Restaurant", 45),
    ("cafes West Ham Lane London E15", "Cafe", 25),
    ("restaurants Plaistow Road London E15", "Restaurant", 45),
    ("cafes Plaistow Road London E15", "Cafe", 25),
    ("restaurants Maryland Street London E15", "Restaurant", 40),
    ("cafes Maryland Street London E15", "Cafe", 20),
    ("restaurants Warton Road London E15", "Restaurant", 35),
    ("cafes Warton Road London E15", "Cafe", 20),

    # E17 – Walthamstow more streets
    ("restaurants Hoe Street London E17", "Restaurant", 55),
    ("cafes Hoe Street London E17", "Cafe", 35),
    ("restaurants High Street Walthamstow London E17", "Restaurant", 55),
    ("cafes High Street Walthamstow London E17", "Cafe", 35),
    ("restaurants Wood Street Walthamstow London E17", "Restaurant", 50),
    ("cafes Wood Street Walthamstow London E17", "Cafe", 30),
    ("restaurants Forest Road Walthamstow London E17", "Restaurant", 50),
    ("cafes Forest Road Walthamstow London E17", "Cafe", 30),
    ("restaurants Walthamstow Village London E17", "Restaurant", 50),
    ("cafes Walthamstow Village London E17", "Cafe", 30),
    ("restaurants Orford Road London E17", "Restaurant", 45),
    ("cafes Orford Road London E17", "Cafe", 25),
    ("restaurants Shernhall Street London E17", "Restaurant", 40),
    ("cafes Shernhall Street London E17", "Cafe", 20),
    ("restaurants Church Hill London E17", "Restaurant", 40),
    ("cafes Church Hill London E17", "Cafe", 20),
    ("restaurants Lea Bridge Road Walthamstow London E17", "Restaurant", 45),
    ("cafes Lea Bridge Road Walthamstow London E17", "Cafe", 25),
    ("restaurants Westbury Road London E17", "Restaurant", 35),
    ("cafes Westbury Road London E17", "Cafe", 20),
    ("restaurants Blackhorse Road London E17", "Restaurant", 45),
    ("cafes Blackhorse Road London E17", "Cafe", 25),

    # E18 – South Woodford more streets
    ("restaurants George Lane South Woodford London E18", "Restaurant", 50),
    ("cafes George Lane South Woodford London E18", "Cafe", 30),
    ("restaurants High Road South Woodford London E18", "Restaurant", 50),
    ("cafes High Road South Woodford London E18", "Cafe", 30),
    ("restaurants Hermon Hill London E18", "Restaurant", 40),
    ("cafes Hermon Hill London E18", "Cafe", 20),
    ("restaurants Woodford Road London E18", "Restaurant", 40),
    ("cafes Woodford Road London E18", "Cafe", 20),
    ("restaurants Station Road South Woodford London E18", "Restaurant", 45),
    ("cafes Station Road South Woodford London E18", "Cafe", 25),
    ("restaurants Churchfields London E18", "Restaurant", 35),
    ("cafes Churchfields London E18", "Cafe", 20),
    ("restaurants Oak Hill London E18", "Restaurant", 35),
    ("cafes Oak Hill London E18", "Cafe", 20),

    # E1 – Stepney / Shadwell / Whitechapel extra streets
    ("restaurants Stepney Green London E1", "Restaurant", 50),
    ("cafes Stepney Green London E1", "Cafe", 30),
    ("restaurants Mile End Road London E1", "Restaurant", 55),
    ("cafes Mile End Road London E1", "Cafe", 35),
    ("restaurants Shadwell London E1", "Restaurant", 45),
    ("cafes Shadwell London E1", "Cafe", 25),
    ("restaurants Cable Street London E1", "Restaurant", 50),
    ("cafes Cable Street London E1", "Cafe", 30),
    ("restaurants Commercial Road London E1", "Restaurant", 55),
    ("cafes Commercial Road London E1", "Cafe", 35),
    ("restaurants Whitechapel High Street London E1", "Restaurant", 55),
    ("cafes Whitechapel High Street London E1", "Cafe", 35),
    ("restaurants Leman Street London E1", "Restaurant", 45),
    ("cafes Leman Street London E1", "Cafe", 25),

    # E9 – Hackney / Homerton extra streets
    ("restaurants Homerton High Street London E9", "Restaurant", 50),
    ("cafes Homerton High Street London E9", "Cafe", 30),
    ("restaurants Victoria Park Road London E9", "Restaurant", 50),
    ("cafes Victoria Park Road London E9", "Cafe", 30),
    ("restaurants Wick Road London E9", "Restaurant", 45),
    ("cafes Wick Road London E9", "Cafe", 25),
    ("restaurants Mehetabel Road London E9", "Restaurant", 35),
    ("cafes Mehetabel Road London E9", "Cafe", 20),

    # E16 – Canning Town / Royal Docks
    ("restaurants Canning Town London E16", "Restaurant", 50),
    ("cafes Canning Town London E16", "Cafe", 30),
    ("restaurants Barking Road Canning Town London E16", "Restaurant", 50),
    ("cafes Barking Road Canning Town London E16", "Cafe", 30),
    ("restaurants Royal Docks London E16", "Restaurant", 50),
    ("cafes Royal Docks London E16", "Cafe", 30),
    ("restaurants Custom House London E16", "Restaurant", 40),
    ("cafes Custom House London E16", "Cafe", 20),
]
