"""
Batch 78 - Bakeries, pastry shops, dessert cafes, ice cream, afternoon tea,
coffee roasters, specialty coffee, juice bars, smoothie bars across London.
Sweet treats and beverages focus.
"""

SEARCH_QUERIES = [
    # Bakeries x London postcodes
    "bakery E1 London",
    "bakery E2 London",
    "bakery E5 London",
    "bakery E8 London",
    "bakery E9 London",
    "bakery E11 London",
    "bakery E14 London",
    "bakery E15 London",
    "bakery E17 London",
    "bakery N1 London",
    "bakery N4 London",
    "bakery N5 London",
    "bakery N6 London",
    "bakery N7 London",
    "bakery N8 London",
    "bakery N10 London",
    "bakery N16 London",
    "bakery N19 London",
    "bakery SE1 London",
    "bakery SE5 London",
    "bakery SE8 London",
    "bakery SE10 London",
    "bakery SE15 London",
    "bakery SE22 London",
    "bakery SE24 London",
    "bakery SW1 London",
    "bakery SW4 London",
    "bakery SW6 London",
    "bakery SW9 London",
    "bakery SW11 London",
    "bakery SW12 London",
    "bakery SW15 London",
    "bakery W1 London",
    "bakery W4 London",
    "bakery W6 London",
    "bakery W8 London",
    "bakery W11 London",
    "bakery W12 London",
    "bakery WC1 London",
    "bakery WC2 London",
    "bakery EC1 London",
    "bakery EC2 London",
    "bakery NW1 London",
    "bakery NW3 London",
    "bakery NW5 London",
    "bakery NW6 London",
    # Sourdough bakeries x London
    "sourdough bakery London E1",
    "sourdough bakery London E8",
    "sourdough bakery London N1",
    "sourdough bakery London N16",
    "sourdough bakery London SE1",
    "sourdough bakery London SE15",
    "sourdough bakery London SE22",
    "sourdough bakery London SW4",
    "sourdough bakery London SW11",
    "sourdough bakery London W1",
    "sourdough bakery London W4",
    "sourdough bakery London WC2",
    "sourdough bakery London EC1",
    "sourdough bakery London NW1",
    "sourdough bakery London NW5",
    "sourdough bakery Hackney London",
    "sourdough bakery Brixton London",
    "sourdough bakery Shoreditch London",
    "sourdough bakery Islington London",
    "sourdough bakery Peckham London",
    "sourdough bakery Dalston London",
    "sourdough bakery Stoke Newington London",
    "sourdough bakery Bermondsey London",
    "artisan bakery London E1",
    "artisan bakery London E8",
    "artisan bakery London N1",
    "artisan bakery London N16",
    "artisan bakery London SE1",
    "artisan bakery London SE15",
    "artisan bakery London SW4",
    "artisan bakery London SW11",
    "artisan bakery London W1",
    "artisan bakery London W4",
    "artisan bakery London WC2",
    "artisan bakery London EC1",
    "artisan bakery London NW1",
    "artisan bakery Hackney London",
    "artisan bakery Brixton London",
    "artisan bakery Peckham London",
    # Patisserie x London
    "patisserie London E1",
    "patisserie London E8",
    "patisserie London N1",
    "patisserie London SE1",
    "patisserie London SW3",
    "patisserie London SW7",
    "patisserie London W1",
    "patisserie London W4",
    "patisserie London W8",
    "patisserie London WC2",
    "patisserie London EC1",
    "patisserie London NW1",
    "patisserie London NW3",
    "patisserie Shoreditch London",
    "patisserie Hackney London",
    "patisserie Brixton London",
    "patisserie Notting Hill London",
    "patisserie Chelsea London",
    "patisserie Mayfair London",
    "patisserie Kensington London",
    # Afternoon tea x London
    "afternoon tea London W1",
    "afternoon tea London SW1",
    "afternoon tea London SW3",
    "afternoon tea London SW7",
    "afternoon tea London WC2",
    "afternoon tea London EC1",
    "afternoon tea London NW1",
    "afternoon tea London NW3",
    "afternoon tea London SE1",
    "afternoon tea London E1",
    "afternoon tea London N1",
    "afternoon tea Mayfair London",
    "afternoon tea Chelsea London",
    "afternoon tea Kensington London",
    "afternoon tea Knightsbridge London",
    "afternoon tea Covent Garden London",
    "afternoon tea Soho London",
    "afternoon tea Shoreditch London",
    "afternoon tea Hackney London",
    "afternoon tea Camden London",
    "afternoon tea Notting Hill London",
    "afternoon tea Richmond London",
    "afternoon tea Greenwich London",
    "afternoon tea Wimbledon London",
    "cream tea London",
    "high tea London W1",
    "high tea London SW1",
    "high tea London WC2",
    "high tea London SE1",
    "tea room London E1",
    "tea room London N1",
    "tea room London SE1",
    "tea room London SW3",
    "tea room London W1",
    "tea room London WC2",
    "tea room London NW1",
    "tea room London NW3",
    # Specialty coffee / coffee roasters x London
    "specialty coffee London E1",
    "specialty coffee London E8",
    "specialty coffee London N1",
    "specialty coffee London N16",
    "specialty coffee London SE1",
    "specialty coffee London SE15",
    "specialty coffee London SE22",
    "specialty coffee London SW4",
    "specialty coffee London SW11",
    "specialty coffee London W1",
    "specialty coffee London WC2",
    "specialty coffee London EC1",
    "specialty coffee London EC2",
    "specialty coffee London NW1",
    "specialty coffee London NW5",
    "specialty coffee Shoreditch London",
    "specialty coffee Hackney London",
    "specialty coffee Brixton London",
    "specialty coffee Dalston London",
    "specialty coffee Islington London",
    "specialty coffee Bermondsey London",
    "specialty coffee Peckham London",
    "specialty coffee Stoke Newington London",
    "specialty coffee Camden London",
    "specialty coffee Notting Hill London",
    "coffee roaster London EC1",
    "coffee roaster London E1",
    "coffee roaster London N1",
    "coffee roaster London SE1",
    "coffee roaster London SW9",
    "coffee roaster London W1",
    "coffee roaster London NW1",
    "coffee roaster Shoreditch London",
    "coffee roaster Hackney London",
    "coffee roaster Brixton London",
    "third wave coffee London E1",
    "third wave coffee London N1",
    "third wave coffee London SE1",
    "third wave coffee London W1",
    "third wave coffee London EC1",
    # Juice bar / smoothie bar x London
    "juice bar London E1",
    "juice bar London E8",
    "juice bar London N1",
    "juice bar London N16",
    "juice bar London SE1",
    "juice bar London SE15",
    "juice bar London SW4",
    "juice bar London SW9",
    "juice bar London SW11",
    "juice bar London W1",
    "juice bar London WC2",
    "juice bar London EC1",
    "juice bar London NW1",
    "juice bar London NW5",
    "juice bar London NW6",
    "smoothie bar London E1",
    "smoothie bar London N1",
    "smoothie bar London SE1",
    "smoothie bar London SW4",
    "smoothie bar London W1",
    "smoothie bar London WC2",
    "smoothie bar London EC1",
    "smoothie bar London NW1",
    "cold press juice London E1",
    "cold press juice London N1",
    "cold press juice London SE1",
    "cold press juice London W1",
    "cold press juice London NW1",
    # Dessert cafes x London
    "dessert cafe London E1",
    "dessert cafe London E8",
    "dessert cafe London N1",
    "dessert cafe London N16",
    "dessert cafe London SE1",
    "dessert cafe London SE15",
    "dessert cafe London SW9",
    "dessert cafe London SW11",
    "dessert cafe London W1",
    "dessert cafe London WC2",
    "dessert cafe London EC1",
    "dessert cafe London NW1",
    "dessert cafe London NW6",
    "dessert parlour London E1",
    "dessert parlour London N1",
    "dessert parlour London SE1",
    "dessert parlour London W1",
    "dessert parlour London NW1",
    "dessert restaurant London W1",
    "dessert restaurant London WC2",
    "dessert restaurant London EC1",
    "dessert restaurant London SE1",
    # Gelato / ice cream x London
    "gelato London E1",
    "gelato London E8",
    "gelato London N1",
    "gelato London N16",
    "gelato London SE1",
    "gelato London SE22",
    "gelato London SW4",
    "gelato London SW11",
    "gelato London W1",
    "gelato London W4",
    "gelato London WC2",
    "gelato London EC1",
    "gelato London NW1",
    "gelato London NW3",
    "artisan ice cream London E1",
    "artisan ice cream London N1",
    "artisan ice cream London SE1",
    "artisan ice cream London SW4",
    "artisan ice cream London W1",
    "artisan ice cream London WC2",
    "artisan ice cream London EC1",
    "artisan ice cream London NW1",
    "ice cream parlour Shoreditch London",
    "ice cream parlour Brixton London",
    "ice cream parlour Hackney London",
    "ice cream parlour Islington London",
    "ice cream parlour Notting Hill London",
]
