"""
Batch 71 - Pizza, burger, chicken, fish & chips, kebab fast casual x London postcodes/areas
Covers: pizza restaurants/delivery, burger joints, fried chicken, fish and chips,
kebab shops, fast casual dining across all London postcodes.
"""

SEARCH_QUERIES = [
    # Pizza restaurants x London postcodes
    "pizza restaurant E1 London",
    "pizza restaurant E2 London",
    "pizza restaurant E3 London",
    "pizza restaurant E5 London",
    "pizza restaurant E8 London",
    "pizza restaurant E9 London",
    "pizza restaurant E10 London",
    "pizza restaurant E11 London",
    "pizza restaurant E14 London",
    "pizza restaurant E15 London",
    "pizza restaurant E17 London",
    "pizza restaurant N1 London",
    "pizza restaurant N4 London",
    "pizza restaurant N5 London",
    "pizza restaurant N7 London",
    "pizza restaurant N8 London",
    "pizza restaurant N10 London",
    "pizza restaurant N16 London",
    "pizza restaurant N19 London",
    "pizza restaurant SE1 London",
    "pizza restaurant SE5 London",
    "pizza restaurant SE8 London",
    "pizza restaurant SE10 London",
    "pizza restaurant SE15 London",
    "pizza restaurant SE22 London",
    "pizza restaurant SE24 London",
    "pizza restaurant SW1 London",
    "pizza restaurant SW2 London",
    "pizza restaurant SW4 London",
    "pizza restaurant SW6 London",
    "pizza restaurant SW9 London",
    "pizza restaurant SW11 London",
    "pizza restaurant SW12 London",
    "pizza restaurant SW15 London",
    "pizza restaurant SW18 London",
    "pizza restaurant W1 London",
    "pizza restaurant W4 London",
    "pizza restaurant W6 London",
    "pizza restaurant W11 London",
    "pizza restaurant W12 London",
    "pizza restaurant WC1 London",
    "pizza restaurant WC2 London",
    "pizza restaurant EC1 London",
    "pizza restaurant EC2 London",
    "pizza restaurant NW1 London",
    "pizza restaurant NW3 London",
    "pizza restaurant NW5 London",
    "pizza restaurant NW6 London",
    "pizza restaurant NW10 London",
    # Neapolitan pizza x London
    "Neapolitan pizza London E1",
    "Neapolitan pizza London N1",
    "Neapolitan pizza London SE1",
    "Neapolitan pizza London SW4",
    "Neapolitan pizza London SW11",
    "Neapolitan pizza London W1",
    "Neapolitan pizza London WC2",
    "Neapolitan pizza London EC1",
    "Neapolitan pizza London NW1",
    "Neapolitan pizza Shoreditch London",
    "Neapolitan pizza Brixton London",
    "Neapolitan pizza Hackney London",
    "Neapolitan pizza Islington London",
    "Neapolitan pizza Clapham London",
    "Neapolitan pizza Camden London",
    "wood-fired pizza London E1",
    "wood-fired pizza London N1",
    "wood-fired pizza London SE1",
    "wood-fired pizza London SW11",
    "wood-fired pizza London W1",
    "wood-fired pizza London WC2",
    "wood-fired pizza London EC1",
    "wood-fired pizza London NW1",
    "wood-fired pizza Shoreditch London",
    "wood-fired pizza Hackney London",
    # Burger restaurants x London postcodes
    "burger restaurant E1 London",
    "burger restaurant E2 London",
    "burger restaurant E8 London",
    "burger restaurant E14 London",
    "burger restaurant E15 London",
    "burger restaurant N1 London",
    "burger restaurant N4 London",
    "burger restaurant N7 London",
    "burger restaurant N16 London",
    "burger restaurant SE1 London",
    "burger restaurant SE5 London",
    "burger restaurant SE15 London",
    "burger restaurant SW4 London",
    "burger restaurant SW9 London",
    "burger restaurant SW11 London",
    "burger restaurant W1 London",
    "burger restaurant W4 London",
    "burger restaurant W11 London",
    "burger restaurant WC2 London",
    "burger restaurant EC1 London",
    "burger restaurant NW1 London",
    "burger restaurant NW3 London",
    "burger restaurant NW6 London",
    # Smash burger x London
    "smash burger London E1",
    "smash burger London N1",
    "smash burger London SE1",
    "smash burger London SW4",
    "smash burger London W1",
    "smash burger London WC2",
    "smash burger London EC1",
    "smash burger London NW1",
    "smash burger Shoreditch London",
    "smash burger Hackney London",
    "smash burger Brixton London",
    "smash burger Dalston London",
    "smash burger Islington London",
    "gourmet burger London E1",
    "gourmet burger London N1",
    "gourmet burger London SE1",
    "gourmet burger London W1",
    "gourmet burger London WC2",
    "gourmet burger London EC1",
    "gourmet burger London NW1",
    "gourmet burger Soho London",
    "gourmet burger Shoreditch London",
    "gourmet burger Camden London",
    # Fried chicken x London
    "fried chicken London E1",
    "fried chicken London E6",
    "fried chicken London N1",
    "fried chicken London N4",
    "fried chicken London N15",
    "fried chicken London SE1",
    "fried chicken London SE15",
    "fried chicken London SE17",
    "fried chicken London SW9",
    "fried chicken London SW17",
    "fried chicken London W1",
    "fried chicken London W12",
    "fried chicken London WC2",
    "fried chicken London EC1",
    "fried chicken London NW1",
    "fried chicken London NW10",
    "fried chicken restaurant Brixton London",
    "fried chicken restaurant Hackney London",
    "fried chicken restaurant Peckham London",
    "fried chicken restaurant Dalston London",
    "fried chicken restaurant Tottenham London",
    "southern fried chicken London",
    "Nashville hot chicken London E1",
    "Nashville hot chicken London N1",
    "Nashville hot chicken London SE1",
    "Nashville hot chicken London W1",
    "Nashville hot chicken London WC2",
    "Nashville hot chicken London EC1",
    "Nashville hot chicken London NW1",
    "Nashville hot chicken Shoreditch London",
    "Nashville hot chicken Brixton London",
    "Nashville hot chicken Hackney London",
    # Fish and chips x London
    "fish and chips E1 London",
    "fish and chips E2 London",
    "fish and chips E5 London",
    "fish and chips E8 London",
    "fish and chips E14 London",
    "fish and chips E15 London",
    "fish and chips E17 London",
    "fish and chips N1 London",
    "fish and chips N4 London",
    "fish and chips N8 London",
    "fish and chips N10 London",
    "fish and chips N16 London",
    "fish and chips SE1 London",
    "fish and chips SE5 London",
    "fish and chips SE10 London",
    "fish and chips SE15 London",
    "fish and chips SE22 London",
    "fish and chips SW4 London",
    "fish and chips SW9 London",
    "fish and chips SW11 London",
    "fish and chips SW12 London",
    "fish and chips W1 London",
    "fish and chips W4 London",
    "fish and chips W6 London",
    "fish and chips W11 London",
    "fish and chips WC2 London",
    "fish and chips EC1 London",
    "fish and chips NW1 London",
    "fish and chips NW3 London",
    "fish and chips NW6 London",
    "fish and chips Soho London",
    "fish and chips Hackney London",
    "fish and chips Brixton London",
    "fish and chips Dalston London",
    "fish and chips Peckham London",
    "chippy London E1",
    "chippy London SE1",
    "chippy London N1",
    "chippy London SW9",
    "chippy London W1",
    "chippy London NW1",
    # Takeaway food x London postcodes
    "takeaway food E1 London",
    "takeaway food E8 London",
    "takeaway food N1 London",
    "takeaway food N16 London",
    "takeaway food SE1 London",
    "takeaway food SE15 London",
    "takeaway food SW9 London",
    "takeaway food SW11 London",
    "takeaway food W1 London",
    "takeaway food W11 London",
    "takeaway food WC2 London",
    "takeaway food EC1 London",
    "takeaway food NW1 London",
    "takeaway food NW6 London",
    "food delivery service E1 London",
    "food delivery service E8 London",
    "food delivery service N1 London",
    "food delivery service N16 London",
    "food delivery service SE1 London",
    "food delivery service SE15 London",
    "food delivery service SW9 London",
    "food delivery service SW11 London",
    "food delivery service W1 London",
    "food delivery service WC2 London",
    "food delivery service EC1 London",
    "food delivery service NW1 London",
    # Sandwich shops and delis x London
    "sandwich shop E1 London",
    "sandwich shop E8 London",
    "sandwich shop N1 London",
    "sandwich shop SE1 London",
    "sandwich shop SW4 London",
    "sandwich shop W1 London",
    "sandwich shop WC2 London",
    "sandwich shop EC1 London",
    "sandwich shop EC2 London",
    "sandwich shop NW1 London",
    "deli London E1",
    "deli London E8",
    "deli London N1",
    "deli London N4",
    "deli London N16",
    "deli London SE1",
    "deli London SE22",
    "deli London SW4",
    "deli London SW11",
    "deli London W1",
    "deli London W4",
    "deli London W11",
    "deli London WC2",
    "deli London EC1",
    "deli London NW1",
    "deli London NW3",
    "deli London NW6",
    "deli Shoreditch London",
    "deli Hackney London",
    "deli Brixton London",
    "deli Islington London",
    "deli Camden London",
    "deli Notting Hill London",
]
