"""
Batch 70 - Brunch, vegan, vegetarian, plant-based, gluten-free, kosher, organic x London
Covers: brunch spots, vegan restaurants/cafes, vegetarian restaurants, plant-based dining,
gluten-free cafes, kosher restaurants, organic cafes across London postcodes and areas.
"""

SEARCH_QUERIES = [
    # Brunch x London postcodes
    "brunch restaurant E1 London",
    "brunch restaurant E2 London",
    "brunch restaurant E3 London",
    "brunch restaurant E5 London",
    "brunch restaurant E8 London",
    "brunch restaurant E9 London",
    "brunch restaurant E14 London",
    "brunch restaurant E15 London",
    "brunch restaurant E17 London",
    "brunch restaurant N1 London",
    "brunch restaurant N4 London",
    "brunch restaurant N5 London",
    "brunch restaurant N6 London",
    "brunch restaurant N7 London",
    "brunch restaurant N8 London",
    "brunch restaurant N10 London",
    "brunch restaurant N16 London",
    "brunch restaurant N19 London",
    "brunch restaurant SE1 London",
    "brunch restaurant SE5 London",
    "brunch restaurant SE8 London",
    "brunch restaurant SE10 London",
    "brunch restaurant SE15 London",
    "brunch restaurant SE22 London",
    "brunch restaurant SE24 London",
    "brunch restaurant SW1 London",
    "brunch restaurant SW2 London",
    "brunch restaurant SW4 London",
    "brunch restaurant SW6 London",
    "brunch restaurant SW9 London",
    "brunch restaurant SW11 London",
    "brunch restaurant SW12 London",
    "brunch restaurant SW15 London",
    "brunch restaurant SW18 London",
    "brunch restaurant W1 London",
    "brunch restaurant W4 London",
    "brunch restaurant W6 London",
    "brunch restaurant W8 London",
    "brunch restaurant W11 London",
    "brunch restaurant W12 London",
    "brunch restaurant WC1 London",
    "brunch restaurant WC2 London",
    "brunch restaurant EC1 London",
    "brunch restaurant EC2 London",
    "brunch restaurant NW1 London",
    "brunch restaurant NW3 London",
    "brunch restaurant NW5 London",
    "brunch restaurant NW6 London",
    # Brunch x areas
    "brunch Shoreditch London",
    "brunch Hackney London",
    "brunch Dalston London",
    "brunch Brixton London",
    "brunch Peckham London",
    "brunch Bermondsey London",
    "brunch Islington London",
    "brunch Camden London",
    "brunch Clapham London",
    "brunch Battersea London",
    "brunch Notting Hill London",
    "brunch Chelsea London",
    "brunch Fulham London",
    "brunch Chiswick London",
    "brunch Wimbledon London",
    "brunch Richmond London",
    "brunch Greenwich London",
    "brunch Dulwich London",
    "brunch Stoke Newington London",
    "brunch Muswell Hill London",
    "brunch Crouch End London",
    "brunch Primrose Hill London",
    "brunch Fitzrovia London",
    "brunch Soho London",
    "brunch Covent Garden London",
    "brunch Clerkenwell London",
    "brunch Wapping London",
    "brunch Putney London",
    "brunch Tooting London",
    "brunch Streatham London",
    # Vegan restaurants x London postcodes
    "vegan restaurants E1 London",
    "vegan restaurants E2 London",
    "vegan restaurants E5 London",
    "vegan restaurants E8 London",
    "vegan restaurants E9 London",
    "vegan restaurants E14 London",
    "vegan restaurants E15 London",
    "vegan restaurants E17 London",
    "vegan restaurants N1 London",
    "vegan restaurants N4 London",
    "vegan restaurants N5 London",
    "vegan restaurants N6 London",
    "vegan restaurants N7 London",
    "vegan restaurants N8 London",
    "vegan restaurants N10 London",
    "vegan restaurants N16 London",
    "vegan restaurants SE1 London",
    "vegan restaurants SE5 London",
    "vegan restaurants SE15 London",
    "vegan restaurants SE22 London",
    "vegan restaurants SE24 London",
    "vegan restaurants SW1 London",
    "vegan restaurants SW4 London",
    "vegan restaurants SW9 London",
    "vegan restaurants SW11 London",
    "vegan restaurants W1 London",
    "vegan restaurants W4 London",
    "vegan restaurants W11 London",
    "vegan restaurants WC2 London",
    "vegan restaurants EC1 London",
    "vegan restaurants NW1 London",
    "vegan restaurants NW3 London",
    "vegan restaurants NW5 London",
    "vegan restaurants NW6 London",
    "vegan restaurants NW10 London",
    # Vegan cafes x London postcodes
    "vegan cafe E1 London",
    "vegan cafe E2 London",
    "vegan cafe E8 London",
    "vegan cafe N1 London",
    "vegan cafe N16 London",
    "vegan cafe SE1 London",
    "vegan cafe SE5 London",
    "vegan cafe SE15 London",
    "vegan cafe SW4 London",
    "vegan cafe SW9 London",
    "vegan cafe SW11 London",
    "vegan cafe W1 London",
    "vegan cafe W4 London",
    "vegan cafe WC2 London",
    "vegan cafe EC1 London",
    "vegan cafe NW1 London",
    "vegan cafe NW5 London",
    "vegan cafe NW6 London",
    # Vegan x areas
    "vegan restaurant Shoreditch London",
    "vegan restaurant Hackney London",
    "vegan restaurant Dalston London",
    "vegan restaurant Brixton London",
    "vegan restaurant Peckham London",
    "vegan restaurant Islington London",
    "vegan restaurant Camden London",
    "vegan restaurant Clapham London",
    "vegan restaurant Notting Hill London",
    "vegan restaurant Stoke Newington London",
    "vegan restaurant Muswell Hill London",
    "vegan restaurant Crouch End London",
    "vegan restaurant Walthamstow London",
    "vegan restaurant Bethnal Green London",
    "vegan restaurant Bow London",
    "vegan restaurant Bermondsey London",
    "vegan cafe Hackney London",
    "vegan cafe Brixton London",
    "vegan cafe Dalston London",
    "vegan cafe Stoke Newington London",
    "vegan cafe Peckham London",
    "vegan cafe Camden London",
    "plant-based restaurant London E1",
    "plant-based restaurant London N1",
    "plant-based restaurant London SE1",
    "plant-based restaurant London SW9",
    "plant-based restaurant London W1",
    "plant-based restaurant London EC1",
    "plant-based restaurant London NW1",
    "plant-based restaurant Shoreditch London",
    "plant-based restaurant Brixton London",
    "plant-based restaurant Hackney London",
    "plant-based restaurant Camden London",
    "plant-based cafe London E1",
    "plant-based cafe London N1",
    "plant-based cafe London SE1",
    "plant-based cafe London W1",
    "plant-based cafe London NW1",
    # Vegetarian restaurants x London
    "vegetarian restaurants E1 London",
    "vegetarian restaurants E2 London",
    "vegetarian restaurants E8 London",
    "vegetarian restaurants N1 London",
    "vegetarian restaurants N4 London",
    "vegetarian restaurants N16 London",
    "vegetarian restaurants SE1 London",
    "vegetarian restaurants SE5 London",
    "vegetarian restaurants SE15 London",
    "vegetarian restaurants SW4 London",
    "vegetarian restaurants SW9 London",
    "vegetarian restaurants SW11 London",
    "vegetarian restaurants W1 London",
    "vegetarian restaurants W4 London",
    "vegetarian restaurants WC2 London",
    "vegetarian restaurants EC1 London",
    "vegetarian restaurants NW1 London",
    "vegetarian restaurants NW3 London",
    "vegetarian restaurants NW6 London",
    "vegetarian restaurants NW10 London",
    "vegetarian restaurant Shoreditch London",
    "vegetarian restaurant Brixton London",
    "vegetarian restaurant Hackney London",
    "vegetarian restaurant Islington London",
    "vegetarian restaurant Camden London",
    "vegetarian restaurant Clapham London",
    "vegetarian restaurant Stoke Newington London",
    "vegetarian restaurant Wembley London",
    "vegetarian restaurant Southall London",
    "vegetarian restaurant Tooting London",
    # Gluten-free cafes and restaurants x London
    "gluten-free restaurant London E1",
    "gluten-free restaurant London N1",
    "gluten-free restaurant London SE1",
    "gluten-free restaurant London SW4",
    "gluten-free restaurant London SW11",
    "gluten-free restaurant London W1",
    "gluten-free restaurant London WC2",
    "gluten-free restaurant London EC1",
    "gluten-free restaurant London NW1",
    "gluten-free cafe London E1",
    "gluten-free cafe London N1",
    "gluten-free cafe London SE1",
    "gluten-free cafe London SW4",
    "gluten-free cafe London W1",
    "gluten-free cafe London EC1",
    "gluten-free cafe London NW1",
    "gluten-free bakery London E1",
    "gluten-free bakery London N1",
    "gluten-free bakery London SE1",
    "gluten-free bakery London W1",
    "gluten-free bakery London WC2",
    "gluten-free bakery London NW1",
    "allergen-friendly restaurant London",
    "allergen-friendly cafe London",
    "free-from cafe London",
    # Kosher restaurants x London
    "kosher restaurant London N1",
    "kosher restaurant London N3",
    "kosher restaurant London N12",
    "kosher restaurant London NW4",
    "kosher restaurant London NW11",
    "kosher restaurant London NW3",
    "kosher restaurant London W1",
    "kosher restaurant Golders Green London",
    "kosher restaurant Hendon London",
    "kosher restaurant Stamford Hill London",
    "kosher restaurant Edgware London",
    "kosher restaurant Finchley London",
    "kosher cafe London NW11",
    "kosher cafe London NW3",
    "kosher cafe London N3",
    "kosher cafe Golders Green London",
    "kosher cafe Hendon London",
    "kosher bakery London NW11",
    "kosher bakery London NW3",
    "kosher bakery Golders Green London",
    "kosher deli London NW11",
    "kosher deli London NW3",
    "kosher deli Golders Green London",
    # Organic cafes and restaurants x London
    "organic cafe London E1",
    "organic cafe London N1",
    "organic cafe London N16",
    "organic cafe London SE1",
    "organic cafe London SE22",
    "organic cafe London SW4",
    "organic cafe London SW11",
    "organic cafe London W1",
    "organic cafe London WC2",
    "organic cafe London EC1",
    "organic cafe London NW1",
    "organic cafe London NW3",
    "organic cafe Hackney London",
    "organic cafe Brixton London",
    "organic cafe Islington London",
    "organic cafe Stoke Newington London",
    "organic cafe Notting Hill London",
    "organic restaurant London E1",
    "organic restaurant London N1",
    "organic restaurant London SE1",
    "organic restaurant London SW4",
    "organic restaurant London W1",
    "organic restaurant London NW1",
    "organic restaurant Shoreditch London",
    "organic restaurant Brixton London",
    "wholefood cafe London E1",
    "wholefood cafe London N1",
    "wholefood cafe London SE1",
    "wholefood cafe London W1",
    "wholefood cafe London NW1",
    "wholefood restaurant London",
    "health food cafe London E1",
    "health food cafe London N1",
    "health food cafe London SE1",
    "health food cafe London W1",
    "health food cafe London NW1",
]
