"""
Batch 74 - West and Southwest London neighborhoods: Hammersmith, Shepherd's Bush,
Fulham, Putney, Wandsworth, Clapham, Battersea, Tooting, Barnes, Ealing, Acton,
Chiswick, Brentford, Hounslow, Southall, Hanwell, Greenford, Northolt.
"""

SEARCH_QUERIES = [
    # Hammersmith / Ravenscourt Park
    "restaurants Hammersmith London W6",
    "cafes Hammersmith London W6",
    "restaurants Hammersmith Broadway London W6",
    "cafes Hammersmith Broadway London W6",
    "restaurants King Street Hammersmith London W6",
    "cafes King Street Hammersmith London W6",
    "restaurants Ravenscourt Park London W4",
    "brunch Hammersmith London",
    "pizza restaurant Hammersmith London W6",
    "vegan restaurant Hammersmith London",
    "gastropub Hammersmith London",
    "Persian restaurant Hammersmith London",
    "Italian restaurant Hammersmith London",
    # Shepherd's Bush / White City
    "restaurants Shepherd's Bush London W12",
    "cafes Shepherd's Bush London W12",
    "restaurants Shepherd's Bush Green London W12",
    "cafes Shepherd's Bush Green London W12",
    "restaurants Goldhawk Road London W12",
    "cafes Goldhawk Road London W12",
    "restaurants Uxbridge Road Shepherd's Bush London W12",
    "restaurants White City London W12",
    "cafes White City London W12",
    "restaurants Westfield London W12",
    "cafes Westfield London W12",
    "brunch Shepherd's Bush London",
    "pizza restaurant Shepherd's Bush London W12",
    "vegan restaurant Shepherd's Bush London",
    "gastropub Shepherd's Bush London",
    "Lebanese restaurant Shepherd's Bush London",
    "Turkish restaurant Shepherd's Bush London",
    "Indian restaurant Shepherd's Bush London",
    # Fulham / Parsons Green / Munster Village
    "restaurants Fulham London SW6",
    "cafes Fulham London SW6",
    "restaurants Fulham Road London SW6",
    "cafes Fulham Road London SW6",
    "restaurants Parsons Green London SW6",
    "cafes Parsons Green London SW6",
    "restaurants Munster Road London SW6",
    "cafes Munster Road London SW6",
    "restaurants Fulham Palace Road London W6",
    "restaurants North End Road London SW6",
    "cafes North End Road London SW6",
    "brunch Fulham London",
    "pizza restaurant Fulham London SW6",
    "vegan restaurant Fulham London",
    "gastropub Fulham London",
    "Italian restaurant Fulham London",
    "wine bar Fulham London",
    # Putney / East Putney
    "restaurants Putney London SW15",
    "cafes Putney London SW15",
    "restaurants Putney High Street London SW15",
    "cafes Putney High Street London SW15",
    "restaurants Upper Richmond Road Putney London SW15",
    "restaurants Lower Richmond Road Putney London SW15",
    "restaurants Putney Bridge London SW15",
    "brunch Putney London",
    "pizza restaurant Putney London SW15",
    "vegan restaurant Putney London",
    "gastropub Putney London",
    "Italian restaurant Putney London",
    # Wandsworth / Earlsfield
    "restaurants Wandsworth London SW18",
    "cafes Wandsworth London SW18",
    "restaurants Wandsworth Town London SW18",
    "cafes Wandsworth Town London SW18",
    "restaurants Garratt Lane London SW18",
    "cafes Garratt Lane London SW18",
    "restaurants Earlsfield London SW18",
    "cafes Earlsfield London SW18",
    "brunch Wandsworth London",
    "pizza restaurant Wandsworth London SW18",
    "gastropub Wandsworth London",
    "gastropub Earlsfield London",
    "Italian restaurant Wandsworth London",
    # Battersea / Nine Elms
    "restaurants Battersea London SW11",
    "cafes Battersea London SW11",
    "restaurants Battersea Park Road London SW11",
    "cafes Battersea Park Road London SW11",
    "restaurants Northcote Road London SW11",
    "cafes Northcote Road London SW11",
    "restaurants Battersea Power Station London SW11",
    "cafes Battersea Power Station London SW11",
    "restaurants Nine Elms London SW8",
    "cafes Nine Elms London SW8",
    "restaurants Lavender Hill London SW11",
    "cafes Lavender Hill London SW11",
    "brunch Battersea London",
    "pizza restaurant Battersea London SW11",
    "vegan restaurant Battersea London",
    "gastropub Battersea London",
    "Italian restaurant Battersea London",
    "wine bar Battersea London",
    # Barnes / Mortlake / East Sheen
    "restaurants Barnes London SW13",
    "cafes Barnes London SW13",
    "restaurants Barnes High Street London SW13",
    "cafes Barnes High Street London SW13",
    "restaurants Church Road Barnes London SW13",
    "restaurants Mortlake London SW14",
    "cafes Mortlake London SW14",
    "restaurants East Sheen London SW14",
    "cafes East Sheen London SW14",
    "brunch Barnes London",
    "gastropub Barnes London",
    "pizza restaurant Barnes London SW13",
    "Italian restaurant Barnes London",
    # Ealing / Ealing Broadway
    "restaurants Ealing London W5",
    "cafes Ealing London W5",
    "restaurants Ealing Broadway London W5",
    "cafes Ealing Broadway London W5",
    "restaurants The Mall Ealing London W5",
    "restaurants Bond Street Ealing London W5",
    "restaurants South Ealing London W5",
    "cafes South Ealing London W5",
    "Indian restaurants Ealing London",
    "brunch Ealing London",
    "pizza restaurant Ealing London W5",
    "vegan restaurant Ealing London",
    "gastropub Ealing London",
    # Acton / Acton Central
    "restaurants Acton London W3",
    "cafes Acton London W3",
    "restaurants Acton High Street London W3",
    "cafes Acton High Street London W3",
    "restaurants South Acton London W3",
    "cafes South Acton London W3",
    "restaurants West Acton London W3",
    "Indian restaurants Acton London",
    "brunch Acton London",
    "pizza restaurant Acton London W3",
    "gastropub Acton London",
    # Chiswick (additional areas)
    "restaurants Chiswick London W4",
    "cafes Chiswick London W4",
    "restaurants Chiswick High Road London W4",
    "cafes Chiswick High Road London W4",
    "restaurants Turnham Green London W4",
    "cafes Turnham Green London W4",
    "restaurants Gunnersbury Lane London W3",
    "restaurants Strand on the Green London W4",
    "cafes Strand on the Green London W4",
    "brunch Chiswick London",
    "pizza restaurant Chiswick London W4",
    "vegan restaurant Chiswick London",
    "gastropub Chiswick London",
    "wine bar Chiswick London",
    "Italian restaurant Chiswick London",
    # Brentford / Kew Bridge
    "restaurants Brentford London TW8",
    "cafes Brentford London TW8",
    "restaurants Kew Bridge London TW8",
    "cafes Kew Bridge London TW8",
    "restaurants High Street Brentford London TW8",
    "brunch Brentford London",
    "gastropub Brentford London",
    "pizza restaurant Brentford London TW8",
    # Hounslow / Heston
    "restaurants Hounslow London TW3",
    "cafes Hounslow London TW3",
    "restaurants Hounslow High Street London TW3",
    "cafes Hounslow High Street London TW3",
    "Indian restaurants Hounslow London",
    "halal restaurants Hounslow London",
    "restaurants Heston London TW5",
    "cafes Heston London TW5",
    "brunch Hounslow London",
    "pizza restaurant Hounslow London TW3",
    # Southall / Norwood Green
    "restaurants Southall London UB1",
    "cafes Southall London UB1",
    "restaurants Southall Broadway London UB1",
    "cafes Southall Broadway London UB1",
    "restaurants The Broadway Southall London UB1",
    "Indian restaurants Southall London UB1",
    "Pakistani restaurants Southall London UB1",
    "Punjabi restaurants Southall London",
    "halal restaurants Southall London UB1",
    "vegetarian Indian Southall London",
    "street food Southall London",
    "sweets Southall London",
    # Hanwell / West Ealing
    "restaurants Hanwell London W7",
    "cafes Hanwell London W7",
    "restaurants West Ealing London W13",
    "cafes West Ealing London W13",
    "restaurants Drayton Green London W13",
    "brunch West Ealing London",
    "pizza restaurant West Ealing London W13",
    # Greenford / Northolt / Perivale
    "restaurants Greenford London UB6",
    "cafes Greenford London UB6",
    "restaurants Northolt London UB5",
    "cafes Northolt London UB5",
    "restaurants Perivale London UB6",
    "Indian restaurants Greenford London",
    "halal restaurants Northolt London",
    # Southfields / Wimbledon Park
    "restaurants Southfields London SW18",
    "cafes Southfields London SW18",
    "restaurants Wimbledon Park London SW19",
    "cafes Wimbledon Park London SW19",
    "brunch Southfields London",
    "pizza restaurant Southfields London SW18",
    "gastropub Southfields London",
    # Roehampton / Putney Vale
    "restaurants Roehampton London SW15",
    "cafes Roehampton London SW15",
    "restaurants Putney Vale London SW15",
    "gastropub Roehampton London",
    # Hampton / Hampton Court
    "restaurants Hampton London TW12",
    "cafes Hampton London TW12",
    "restaurants Hampton Court London KT8",
    "cafes Hampton Court London KT8",
    "gastropub Hampton Court London",
    "brunch Hampton London",
]
