"""
Batch 63 – Search modifiers × London area names:
Modifiers: good, popular, local, independent, family run, small, cosy, romantic, hidden, secret,
authentic, traditional, modern, trendy paired with London areas:
Hackney, Peckham, Brixton, Dalston, Shoreditch, Islington, Camden, Clapham, Battersea,
Bermondsey, Greenwich, Dulwich, Hampstead, Notting Hill, Chiswick, Richmond, Wimbledon,
Kingston, Tooting, Streatham, Forest Hill, New Cross, Lewisham, Catford, Walthamstow,
Leyton, Stratford, Bow, Bethnal Green, Mile End, Whitechapel, Stepney
"""

SEARCH_QUERIES = [
    # "good restaurant" × areas
    ("good restaurant Hackney London", "Restaurant", 45),
    ("good restaurant Peckham London", "Restaurant", 45),
    ("good restaurant Brixton London", "Restaurant", 45),
    ("good restaurant Dalston London", "Restaurant", 45),
    ("good restaurant Shoreditch London", "Restaurant", 45),
    ("good restaurant Islington London", "Restaurant", 45),
    ("good restaurant Camden London", "Restaurant", 45),
    ("good restaurant Clapham London", "Restaurant", 45),
    ("good restaurant Battersea London", "Restaurant", 45),
    ("good restaurant Bermondsey London", "Restaurant", 45),
    ("good restaurant Greenwich London", "Restaurant", 45),
    ("good restaurant Dulwich London", "Restaurant", 40),
    ("good restaurant Hampstead London", "Restaurant", 40),
    ("good restaurant Notting Hill London", "Restaurant", 45),
    ("good restaurant Chiswick London", "Restaurant", 40),
    ("good restaurant Richmond London", "Restaurant", 40),
    ("good restaurant Wimbledon London", "Restaurant", 40),
    ("good restaurant Tooting London", "Restaurant", 40),
    ("good restaurant Walthamstow London", "Restaurant", 40),
    ("good restaurant Stratford London", "Restaurant", 40),

    # "popular restaurant" × areas
    ("popular restaurant Hackney London", "Restaurant", 45),
    ("popular restaurant Peckham London", "Restaurant", 45),
    ("popular restaurant Brixton London", "Restaurant", 45),
    ("popular restaurant Dalston London", "Restaurant", 45),
    ("popular restaurant Shoreditch London", "Restaurant", 45),
    ("popular restaurant Islington London", "Restaurant", 45),
    ("popular restaurant Camden London", "Restaurant", 45),
    ("popular restaurant Clapham London", "Restaurant", 45),
    ("popular restaurant Battersea London", "Restaurant", 40),
    ("popular restaurant Bermondsey London", "Restaurant", 40),
    ("popular restaurant Greenwich London", "Restaurant", 40),
    ("popular restaurant Notting Hill London", "Restaurant", 45),
    ("popular restaurant Chiswick London", "Restaurant", 40),
    ("popular restaurant Richmond London", "Restaurant", 40),
    ("popular restaurant Wimbledon London", "Restaurant", 40),

    # "local restaurant" × areas
    ("local restaurant Hackney London", "Restaurant", 40),
    ("local restaurant Peckham London", "Restaurant", 40),
    ("local restaurant Brixton London", "Restaurant", 40),
    ("local restaurant Dalston London", "Restaurant", 40),
    ("local restaurant Shoreditch London", "Restaurant", 40),
    ("local restaurant Islington London", "Restaurant", 40),
    ("local restaurant Clapham London", "Restaurant", 40),
    ("local restaurant Battersea London", "Restaurant", 40),
    ("local restaurant Bermondsey London", "Restaurant", 40),
    ("local restaurant Greenwich London", "Restaurant", 40),
    ("local restaurant Lewisham London", "Restaurant", 40),
    ("local restaurant Catford London", "Restaurant", 35),
    ("local restaurant Walthamstow London", "Restaurant", 40),
    ("local restaurant Leyton London", "Restaurant", 35),
    ("local restaurant Bow London", "Restaurant", 35),

    # "independent restaurant" × areas
    ("independent restaurant Hackney London", "Restaurant", 45),
    ("independent restaurant Peckham London", "Restaurant", 45),
    ("independent restaurant Brixton London", "Restaurant", 45),
    ("independent restaurant Dalston London", "Restaurant", 45),
    ("independent restaurant Shoreditch London", "Restaurant", 45),
    ("independent restaurant Islington London", "Restaurant", 45),
    ("independent restaurant Camden London", "Restaurant", 45),
    ("independent restaurant Clapham London", "Restaurant", 45),
    ("independent restaurant Bermondsey London", "Restaurant", 45),
    ("independent restaurant Greenwich London", "Restaurant", 40),
    ("independent restaurant Dulwich London", "Restaurant", 40),
    ("independent restaurant Notting Hill London", "Restaurant", 45),
    ("independent restaurant Chiswick London", "Restaurant", 40),
    ("independent restaurant Hampstead London", "Restaurant", 40),
    ("independent restaurant Forest Hill London", "Restaurant", 35),
    ("independent restaurant New Cross London", "Restaurant", 40),

    # "family run restaurant" × areas
    ("family run restaurant Hackney London", "Restaurant", 40),
    ("family run restaurant Peckham London", "Restaurant", 40),
    ("family run restaurant Brixton London", "Restaurant", 40),
    ("family run restaurant Islington London", "Restaurant", 40),
    ("family run restaurant Bethnal Green London", "Restaurant", 40),
    ("family run restaurant Whitechapel London", "Restaurant", 40),
    ("family run restaurant Stepney London", "Restaurant", 35),
    ("family run restaurant Tooting London", "Restaurant", 40),
    ("family run restaurant Streatham London", "Restaurant", 35),
    ("family run restaurant Catford London", "Restaurant", 35),

    # "small restaurant" × areas
    ("small restaurant Hackney London", "Restaurant", 40),
    ("small restaurant Peckham London", "Restaurant", 40),
    ("small restaurant Brixton London", "Restaurant", 40),
    ("small restaurant Dalston London", "Restaurant", 40),
    ("small restaurant Shoreditch London", "Restaurant", 40),
    ("small restaurant Islington London", "Restaurant", 40),
    ("small restaurant Camden London", "Restaurant", 40),
    ("small restaurant Bermondsey London", "Restaurant", 40),
    ("small restaurant Bethnal Green London", "Restaurant", 40),
    ("small restaurant Mile End London", "Restaurant", 35),

    # "cosy restaurant" × areas
    ("cosy restaurant Hackney London", "Restaurant", 40),
    ("cosy restaurant Peckham London", "Restaurant", 40),
    ("cosy restaurant Brixton London", "Restaurant", 40),
    ("cosy restaurant Islington London", "Restaurant", 40),
    ("cosy restaurant Camden London", "Restaurant", 40),
    ("cosy restaurant Clapham London", "Restaurant", 40),
    ("cosy restaurant Dulwich London", "Restaurant", 40),
    ("cosy restaurant Hampstead London", "Restaurant", 40),
    ("cosy restaurant Notting Hill London", "Restaurant", 40),
    ("cosy restaurant Chiswick London", "Restaurant", 40),
    ("cosy restaurant Richmond London", "Restaurant", 40),
    ("cosy restaurant Greenwich London", "Restaurant", 40),
    ("cosy restaurant Forest Hill London", "Restaurant", 35),

    # "romantic restaurant" × areas
    ("romantic restaurant Hackney London", "Restaurant", 40),
    ("romantic restaurant Peckham London", "Restaurant", 40),
    ("romantic restaurant Brixton London", "Restaurant", 40),
    ("romantic restaurant Islington London", "Restaurant", 45),
    ("romantic restaurant Camden London", "Restaurant", 40),
    ("romantic restaurant Clapham London", "Restaurant", 40),
    ("romantic restaurant Battersea London", "Restaurant", 40),
    ("romantic restaurant Bermondsey London", "Restaurant", 40),
    ("romantic restaurant Greenwich London", "Restaurant", 45),
    ("romantic restaurant Dulwich London", "Restaurant", 40),
    ("romantic restaurant Hampstead London", "Restaurant", 45),
    ("romantic restaurant Notting Hill London", "Restaurant", 45),
    ("romantic restaurant Chiswick London", "Restaurant", 40),
    ("romantic restaurant Richmond London", "Restaurant", 45),
    ("romantic restaurant Wimbledon London", "Restaurant", 40),

    # "hidden restaurant" × areas
    ("hidden restaurant Hackney London", "Restaurant", 35),
    ("hidden restaurant Shoreditch London", "Restaurant", 35),
    ("hidden restaurant Peckham London", "Restaurant", 35),
    ("hidden restaurant Brixton London", "Restaurant", 35),
    ("hidden restaurant Islington London", "Restaurant", 35),
    ("hidden restaurant Camden London", "Restaurant", 35),
    ("hidden restaurant Bermondsey London", "Restaurant", 35),
    ("hidden restaurant Notting Hill London", "Restaurant", 35),
    ("hidden restaurant Soho London", "Restaurant", 40),

    # "authentic restaurant" × areas
    ("authentic restaurant Hackney London", "Restaurant", 40),
    ("authentic restaurant Dalston London", "Restaurant", 40),
    ("authentic restaurant Brixton London", "Restaurant", 40),
    ("authentic restaurant Shoreditch London", "Restaurant", 40),
    ("authentic restaurant Whitechapel London", "Restaurant", 40),
    ("authentic restaurant Tooting London", "Restaurant", 40),
    ("authentic restaurant Streatham London", "Restaurant", 35),
    ("authentic restaurant Walthamstow London", "Restaurant", 35),
    ("authentic restaurant Bethnal Green London", "Restaurant", 40),
    ("authentic restaurant Stepney London", "Restaurant", 35),

    # "traditional restaurant" × areas
    ("traditional restaurant Hackney London", "Restaurant", 40),
    ("traditional restaurant Greenwich London", "Restaurant", 40),
    ("traditional restaurant Islington London", "Restaurant", 40),
    ("traditional restaurant Clapham London", "Restaurant", 40),
    ("traditional restaurant Dulwich London", "Restaurant", 40),
    ("traditional restaurant Chiswick London", "Restaurant", 40),
    ("traditional restaurant Richmond London", "Restaurant", 40),
    ("traditional restaurant Hampstead London", "Restaurant", 40),
    ("traditional restaurant Wimbledon London", "Restaurant", 35),

    # "modern restaurant" × areas
    ("modern restaurant Hackney London", "Restaurant", 45),
    ("modern restaurant Peckham London", "Restaurant", 45),
    ("modern restaurant Shoreditch London", "Restaurant", 45),
    ("modern restaurant Brixton London", "Restaurant", 40),
    ("modern restaurant Dalston London", "Restaurant", 40),
    ("modern restaurant Islington London", "Restaurant", 40),
    ("modern restaurant Clapham London", "Restaurant", 40),
    ("modern restaurant Bermondsey London", "Restaurant", 40),
    ("modern restaurant Battersea London", "Restaurant", 40),
    ("modern restaurant Canary Wharf London", "Restaurant", 45),
    ("modern restaurant Stratford London", "Restaurant", 40),

    # "trendy restaurant" × areas
    ("trendy restaurant Hackney London", "Restaurant", 45),
    ("trendy restaurant Peckham London", "Restaurant", 45),
    ("trendy restaurant Brixton London", "Restaurant", 45),
    ("trendy restaurant Dalston London", "Restaurant", 45),
    ("trendy restaurant Shoreditch London", "Restaurant", 45),
    ("trendy restaurant Islington London", "Restaurant", 45),
    ("trendy restaurant Camden London", "Restaurant", 45),
    ("trendy restaurant Clapham London", "Restaurant", 40),
    ("trendy restaurant Battersea London", "Restaurant", 40),
    ("trendy restaurant Bermondsey London", "Restaurant", 45),
    ("trendy restaurant New Cross London", "Restaurant", 40),
    ("trendy restaurant Forest Hill London", "Restaurant", 35),
    ("trendy restaurant Walthamstow London", "Restaurant", 40),
    ("trendy restaurant Leyton London", "Restaurant", 35),
    ("trendy restaurant Bow London", "Restaurant", 35),

    # "neighbourhood restaurant" × areas
    ("neighbourhood restaurant Hackney London", "Restaurant", 40),
    ("neighbourhood restaurant Peckham London", "Restaurant", 40),
    ("neighbourhood restaurant Brixton London", "Restaurant", 40),
    ("neighbourhood restaurant Dalston London", "Restaurant", 40),
    ("neighbourhood restaurant Islington London", "Restaurant", 40),
    ("neighbourhood restaurant Clapham London", "Restaurant", 40),
    ("neighbourhood restaurant Dulwich London", "Restaurant", 35),
    ("neighbourhood restaurant Chiswick London", "Restaurant", 35),
    ("neighbourhood restaurant Richmond London", "Restaurant", 35),
    ("neighbourhood restaurant Wimbledon London", "Restaurant", 35),

    # "new restaurant" × areas
    ("new restaurant Hackney London", "Restaurant", 45),
    ("new restaurant Peckham London", "Restaurant", 45),
    ("new restaurant Shoreditch London", "Restaurant", 45),
    ("new restaurant Brixton London", "Restaurant", 45),
    ("new restaurant Islington London", "Restaurant", 45),
    ("new restaurant Clapham London", "Restaurant", 40),
    ("new restaurant Bermondsey London", "Restaurant", 40),
    ("new restaurant Canary Wharf London", "Restaurant", 40),

    # "award winning restaurant" × areas
    ("award winning restaurant Hackney London", "Restaurant", 40),
    ("award winning restaurant Peckham London", "Restaurant", 40),
    ("award winning restaurant Brixton London", "Restaurant", 40),
    ("award winning restaurant Islington London", "Restaurant", 40),
    ("award winning restaurant Greenwich London", "Restaurant", 40),
    ("award winning restaurant Dulwich London", "Restaurant", 35),

    # Restaurant + "booking" / "reservation" modifiers
    ("restaurant booking Hackney London", "Restaurant", 40),
    ("restaurant reservation Shoreditch London", "Restaurant", 40),
    ("restaurant reservation Islington London", "Restaurant", 40),
    ("restaurant booking Brixton London", "Restaurant", 40),
    ("restaurant reservation Peckham London", "Restaurant", 40),
    ("restaurant booking Camden London", "Restaurant", 40),
    ("restaurant reservation Clapham London", "Restaurant", 40),
    ("restaurant booking Greenwich London", "Restaurant", 40),

    # Cafe modifiers
    ("independent cafe Hackney London", "Cafe", 40),
    ("independent cafe Peckham London", "Cafe", 40),
    ("independent cafe Brixton London", "Cafe", 40),
    ("independent cafe Islington London", "Cafe", 40),
    ("independent cafe Shoreditch London", "Cafe", 40),
    ("independent cafe Walthamstow London", "Cafe", 35),
    ("independent cafe Dalston London", "Cafe", 40),
    ("cosy cafe Hackney London", "Cafe", 35),
    ("cosy cafe Peckham London", "Cafe", 35),
    ("cosy cafe Islington London", "Cafe", 35),
    ("cosy cafe Greenwich London", "Cafe", 35),
    ("cosy cafe Hampstead London", "Cafe", 35),
    ("specialty coffee Hackney London", "Cafe", 40),
    ("specialty coffee Shoreditch London", "Cafe", 40),
    ("specialty coffee Peckham London", "Cafe", 35),
    ("specialty coffee Brixton London", "Cafe", 35),
    ("specialty coffee Islington London", "Cafe", 40),
    ("specialty coffee Camden London", "Cafe", 40),
    ("specialty coffee Dalston London", "Cafe", 35),
    ("third wave coffee London Bethnal Green", "Cafe", 35),
    ("third wave coffee London Bow", "Cafe", 30),

    # "best restaurant" × areas
    ("best restaurant Hackney London", "Restaurant", 45),
    ("best restaurant Peckham London", "Restaurant", 45),
    ("best restaurant Brixton London", "Restaurant", 45),
    ("best restaurant Dalston London", "Restaurant", 45),
    ("best restaurant Shoreditch London", "Restaurant", 45),
    ("best restaurant Islington London", "Restaurant", 45),
    ("best restaurant Camden London", "Restaurant", 45),
    ("best restaurant Clapham London", "Restaurant", 45),
    ("best restaurant Greenwich London", "Restaurant", 45),
    ("best restaurant Wimbledon London", "Restaurant", 40),
    ("best restaurant Chiswick London", "Restaurant", 40),
    ("best restaurant Richmond London", "Restaurant", 40),
    ("best restaurant Tooting London", "Restaurant", 40),
    ("best restaurant Streatham London", "Restaurant", 35),
    ("best restaurant Forest Hill London", "Restaurant", 35),

    # "cheap restaurant" × areas
    ("cheap restaurant Hackney London", "Restaurant", 40),
    ("cheap restaurant Peckham London", "Restaurant", 40),
    ("cheap restaurant Brixton London", "Restaurant", 40),
    ("cheap restaurant Dalston London", "Restaurant", 40),
    ("cheap restaurant Shoreditch London", "Restaurant", 40),
    ("cheap restaurant Whitechapel London", "Restaurant", 40),
    ("cheap restaurant Camden London", "Restaurant", 40),
    ("cheap restaurant Bethnal Green London", "Restaurant", 40),
    ("cheap restaurant Walthamstow London", "Restaurant", 35),
    ("cheap restaurant Tottenham London", "Restaurant", 35),

    # "lunch restaurant" × areas
    ("lunch restaurant Hackney London", "Restaurant", 40),
    ("lunch restaurant Shoreditch London", "Restaurant", 40),
    ("lunch restaurant Islington London", "Restaurant", 40),
    ("lunch restaurant Peckham London", "Restaurant", 40),
    ("lunch restaurant Brixton London", "Restaurant", 40),
    ("lunch restaurant Clapham London", "Restaurant", 40),
    ("lunch restaurant Bermondsey London", "Restaurant", 40),
    ("lunch restaurant Greenwich London", "Restaurant", 40),

    # "dinner restaurant" × areas
    ("dinner restaurant Hackney London", "Restaurant", 40),
    ("dinner restaurant Shoreditch London", "Restaurant", 40),
    ("dinner restaurant Islington London", "Restaurant", 40),
    ("dinner restaurant Peckham London", "Restaurant", 40),
    ("dinner restaurant Brixton London", "Restaurant", 40),
    ("dinner restaurant Clapham London", "Restaurant", 40),
    ("dinner restaurant Bermondsey London", "Restaurant", 40),
    ("dinner restaurant Greenwich London", "Restaurant", 40),
    ("dinner restaurant Dulwich London", "Restaurant", 35),
    ("dinner restaurant Hampstead London", "Restaurant", 40),
    ("dinner restaurant Notting Hill London", "Restaurant", 40),
    ("dinner restaurant Chiswick London", "Restaurant", 35),
    ("dinner restaurant Richmond London", "Restaurant", 35),
    ("dinner restaurant Wimbledon London", "Restaurant", 35),

    # "outdoor seating restaurant" / "terrace" × areas
    ("restaurant outdoor seating Hackney London", "Restaurant", 40),
    ("restaurant terrace Shoreditch London", "Restaurant", 40),
    ("restaurant garden Islington London", "Restaurant", 40),
    ("restaurant terrace Peckham London", "Restaurant", 35),
    ("restaurant outdoor Brixton London", "Restaurant", 35),
    ("restaurant beer garden Clapham London", "Restaurant", 40),
    ("restaurant terrace Bermondsey London", "Restaurant", 40),
    ("restaurant with garden London", "Restaurant", 50),
    ("rooftop restaurant London", "Restaurant", 55),
    ("rooftop bar restaurant London", "Restaurant", 50),
]
