"""
Batch 56 – Systematic SE postcode streets: SE2 Abbey Wood, SE3 Blackheath, SE4 Brockley,
SE5 Camberwell, SE6 Catford, SE8 Deptford, SE9 Eltham, SE10 Greenwich, SE13 Lewisham,
SE14 New Cross, SE16 Rotherhithe/Canada Water, SE17 Walworth, SE18 Woolwich,
SE19 Crystal Palace, SE21 Dulwich, SE23 Forest Hill, SE25 South Norwood, SE26 Sydenham
"""

SEARCH_QUERIES = [
    # SE2 – Abbey Wood
    ("restaurants Abbey Wood Road London SE2", "Restaurant", 40),
    ("cafes Abbey Wood Road London SE2", "Cafe", 20),
    ("restaurants Harrow Manorway London SE2", "Restaurant", 35),
    ("cafes Harrow Manorway London SE2", "Cafe", 20),
    ("restaurants McLeod Road London SE2", "Restaurant", 35),
    ("cafes McLeod Road London SE2", "Cafe", 20),
    ("restaurants Felixstowe Road London SE2", "Restaurant", 35),
    ("cafes Felixstowe Road London SE2", "Cafe", 20),
    ("restaurants Knee Hill London SE2", "Restaurant", 35),
    ("cafes Basildon Road London SE2", "Cafe", 20),

    # SE3 – Blackheath more streets
    ("restaurants Blackheath Village London SE3", "Restaurant", 55),
    ("cafes Blackheath Village London SE3", "Cafe", 35),
    ("restaurants Lee Road London SE3", "Restaurant", 50),
    ("cafes Lee Road London SE3", "Cafe", 30),
    ("restaurants Montpelier Row London SE3", "Restaurant", 45),
    ("cafes Montpelier Row London SE3", "Cafe", 25),
    ("restaurants Tranquil Vale London SE3", "Restaurant", 45),
    ("cafes Tranquil Vale London SE3", "Cafe", 25),
    ("restaurants Shooters Hill Road London SE3", "Restaurant", 45),
    ("cafes Shooters Hill Road London SE3", "Cafe", 25),
    ("restaurants Westcombe Hill London SE3", "Restaurant", 40),
    ("cafes Westcombe Hill London SE3", "Cafe", 20),
    ("restaurants Charlton Road London SE3", "Restaurant", 40),
    ("cafes Charlton Road London SE3", "Cafe", 20),

    # SE4 – Brockley more streets
    ("restaurants Brockley Road London SE4", "Restaurant", 50),
    ("cafes Brockley Road London SE4", "Cafe", 30),
    ("restaurants Lewisham Way London SE4", "Restaurant", 50),
    ("cafes Lewisham Way London SE4", "Cafe", 30),
    ("restaurants Brockley Rise London SE4", "Restaurant", 45),
    ("cafes Brockley Rise London SE4", "Cafe", 25),
    ("restaurants Coulgate Street London SE4", "Restaurant", 35),
    ("cafes Coulgate Street London SE4", "Cafe", 20),
    ("restaurants Endwell Road London SE4", "Restaurant", 35),
    ("cafes Endwell Road London SE4", "Cafe", 20),
    ("restaurants Tyrwhitt Road London SE4", "Restaurant", 35),
    ("cafes Tyrwhitt Road London SE4", "Cafe", 20),
    ("restaurants Breakspears Road London SE4", "Restaurant", 40),
    ("cafes Breakspears Road London SE4", "Cafe", 20),

    # SE5 – Camberwell more streets
    ("restaurants Camberwell Church Street London SE5", "Restaurant", 55),
    ("cafes Camberwell Church Street London SE5", "Cafe", 35),
    ("restaurants Camberwell Road London SE5", "Restaurant", 55),
    ("cafes Camberwell Road London SE5", "Cafe", 35),
    ("restaurants Denmark Hill London SE5", "Restaurant", 55),
    ("cafes Denmark Hill London SE5", "Cafe", 35),
    ("restaurants Camberwell Green London SE5", "Restaurant", 50),
    ("cafes Camberwell Green London SE5", "Cafe", 30),
    ("restaurants Southampton Way London SE5", "Restaurant", 40),
    ("cafes Southampton Way London SE5", "Cafe", 20),
    ("restaurants Peckham Road London SE5", "Restaurant", 50),
    ("cafes Peckham Road London SE5", "Cafe", 30),
    ("restaurants Wyndham Road London SE5", "Restaurant", 35),
    ("cafes Wyndham Road London SE5", "Cafe", 20),
    ("restaurants Grove Lane London SE5", "Restaurant", 40),
    ("cafes Grove Lane London SE5", "Cafe", 20),

    # SE6 – Catford more streets
    ("restaurants Catford Road London SE6", "Restaurant", 55),
    ("cafes Catford Road London SE6", "Cafe", 35),
    ("restaurants Rushey Green London SE6", "Restaurant", 55),
    ("cafes Rushey Green London SE6", "Cafe", 35),
    ("restaurants Brownhill Road London SE6", "Restaurant", 45),
    ("cafes Brownhill Road London SE6", "Cafe", 25),
    ("restaurants Sangley Road London SE6", "Restaurant", 40),
    ("cafes Sangley Road London SE6", "Cafe", 20),
    ("restaurants Torridon Road London SE6", "Restaurant", 40),
    ("cafes Torridon Road London SE6", "Cafe", 20),
    ("restaurants Bromley Road Catford London SE6", "Restaurant", 50),
    ("cafes Bromley Road Catford London SE6", "Cafe", 30),
    ("restaurants Stanstead Road London SE6", "Restaurant", 40),
    ("cafes Stanstead Road London SE6", "Cafe", 20),

    # SE8 – Deptford more streets
    ("restaurants Deptford High Street London SE8", "Restaurant", 55),
    ("cafes Deptford High Street London SE8", "Cafe", 35),
    ("restaurants Deptford Broadway London SE8", "Restaurant", 50),
    ("cafes Deptford Broadway London SE8", "Cafe", 30),
    ("restaurants New Cross Road London SE8", "Restaurant", 55),
    ("cafes New Cross Road London SE8", "Cafe", 35),
    ("restaurants Evelyn Street London SE8", "Restaurant", 50),
    ("cafes Evelyn Street London SE8", "Cafe", 30),
    ("restaurants Creek Road London SE8", "Restaurant", 45),
    ("cafes Creek Road London SE8", "Cafe", 25),
    ("restaurants Douglas Way London SE8", "Restaurant", 35),
    ("cafes Douglas Way London SE8", "Cafe", 20),
    ("restaurants Tanners Hill London SE8", "Restaurant", 35),
    ("cafes Tanners Hill London SE8", "Cafe", 20),

    # SE9 – Eltham more streets
    ("restaurants Eltham High Street London SE9", "Restaurant", 55),
    ("cafes Eltham High Street London SE9", "Cafe", 35),
    ("restaurants Well Hall Road London SE9", "Restaurant", 50),
    ("cafes Well Hall Road London SE9", "Cafe", 30),
    ("restaurants Westmount Road London SE9", "Restaurant", 40),
    ("cafes Westmount Road London SE9", "Cafe", 20),
    ("restaurants Mottingham Road London SE9", "Restaurant", 40),
    ("cafes Mottingham Road London SE9", "Cafe", 20),
    ("restaurants Eltham Road London SE9", "Restaurant", 45),
    ("cafes Eltham Road London SE9", "Cafe", 25),
    ("restaurants Passey Place London SE9", "Restaurant", 35),
    ("cafes Passey Place London SE9", "Cafe", 20),
    ("restaurants Blendon Road London SE9", "Restaurant", 35),
    ("cafes Blendon Road London SE9", "Cafe", 20),

    # SE10 – Greenwich more streets
    ("restaurants Greenwich Church Street London SE10", "Restaurant", 55),
    ("cafes Greenwich Church Street London SE10", "Cafe", 35),
    ("restaurants Nelson Road Greenwich London SE10", "Restaurant", 50),
    ("cafes Nelson Road Greenwich London SE10", "Cafe", 30),
    ("restaurants Greenwich Market London SE10", "Restaurant", 55),
    ("cafes Greenwich Market London SE10", "Cafe", 35),
    ("restaurants Trafalgar Road London SE10", "Restaurant", 50),
    ("cafes Trafalgar Road London SE10", "Cafe", 30),
    ("restaurants Woolwich Road London SE10", "Restaurant", 50),
    ("cafes Woolwich Road London SE10", "Cafe", 30),
    ("restaurants Straightsmouth London SE10", "Restaurant", 35),
    ("cafes Straightsmouth London SE10", "Cafe", 20),
    ("restaurants Royal Hill London SE10", "Restaurant", 45),
    ("cafes Royal Hill London SE10", "Cafe", 25),
    ("restaurants Stockwell Street London SE10", "Restaurant", 40),
    ("cafes Stockwell Street London SE10", "Cafe", 20),

    # SE13 – Lewisham more streets
    ("restaurants Lewisham High Street London SE13", "Restaurant", 55),
    ("cafes Lewisham High Street London SE13", "Cafe", 35),
    ("restaurants Loampit Hill London SE13", "Restaurant", 45),
    ("cafes Loampit Hill London SE13", "Cafe", 25),
    ("restaurants Ladywell Road London SE13", "Restaurant", 45),
    ("cafes Ladywell Road London SE13", "Cafe", 25),
    ("restaurants Hither Green Lane London SE13", "Restaurant", 45),
    ("cafes Hither Green Lane London SE13", "Cafe", 25),
    ("restaurants Lee High Road London SE13", "Restaurant", 50),
    ("cafes Lee High Road London SE13", "Cafe", 30),
    ("restaurants Molesworth Street London SE13", "Restaurant", 35),
    ("cafes Molesworth Street London SE13", "Cafe", 20),
    ("restaurants Rushey Green London SE13", "Restaurant", 45),
    ("cafes Manor Lane London SE13", "Cafe", 20),

    # SE14 – New Cross more streets
    ("restaurants New Cross Road London SE14", "Restaurant", 55),
    ("cafes New Cross Road London SE14", "Cafe", 35),
    ("restaurants Goldsmiths New Cross London SE14", "Restaurant", 50),
    ("cafes Goldsmiths New Cross London SE14", "Cafe", 30),
    ("restaurants Queens Road Peckham London SE14", "Restaurant", 50),
    ("cafes Queens Road Peckham London SE14", "Cafe", 30),
    ("restaurants Kender Street London SE14", "Restaurant", 35),
    ("cafes Kender Street London SE14", "Cafe", 20),
    ("restaurants Avonley Road London SE14", "Restaurant", 35),
    ("cafes Avonley Road London SE14", "Cafe", 20),
    ("restaurants Waller Road London SE14", "Restaurant", 35),
    ("cafes Waller Road London SE14", "Cafe", 20),

    # SE16 – Rotherhithe / Canada Water
    ("restaurants Rotherhithe Street London SE16", "Restaurant", 55),
    ("cafes Rotherhithe Street London SE16", "Cafe", 35),
    ("restaurants Lower Road Rotherhithe London SE16", "Restaurant", 50),
    ("cafes Lower Road Rotherhithe London SE16", "Cafe", 30),
    ("restaurants Surrey Quays Road London SE16", "Restaurant", 50),
    ("cafes Surrey Quays Road London SE16", "Cafe", 30),
    ("restaurants Canada Water London SE16", "Restaurant", 55),
    ("cafes Canada Water London SE16", "Cafe", 35),
    ("restaurants Jamaica Road London SE16", "Restaurant", 50),
    ("cafes Jamaica Road London SE16", "Cafe", 30),
    ("restaurants Redriff Road London SE16", "Restaurant", 40),
    ("cafes Redriff Road London SE16", "Cafe", 20),
    ("restaurants Salter Road London SE16", "Restaurant", 40),
    ("cafes Salter Road London SE16", "Cafe", 20),
    ("restaurants Bermondsey Wall West London SE16", "Restaurant", 45),
    ("cafes Bermondsey Wall West London SE16", "Cafe", 25),

    # SE17 – Walworth more streets
    ("restaurants Walworth Road London SE17", "Restaurant", 55),
    ("cafes Walworth Road London SE17", "Cafe", 35),
    ("restaurants East Street London SE17", "Restaurant", 50),
    ("cafes East Street London SE17", "Cafe", 30),
    ("restaurants Wansey Street London SE17", "Restaurant", 35),
    ("cafes Wansey Street London SE17", "Cafe", 20),
    ("restaurants Camberwell New Road London SE17", "Restaurant", 45),
    ("cafes Camberwell New Road London SE17", "Cafe", 25),
    ("restaurants Merrow Street London SE17", "Restaurant", 35),
    ("cafes Merrow Street London SE17", "Cafe", 20),
    ("restaurants Townsend Street London SE17", "Restaurant", 35),
    ("cafes Townsend Street London SE17", "Cafe", 20),

    # SE18 – Woolwich more streets
    ("restaurants Woolwich High Street London SE18", "Restaurant", 55),
    ("cafes Woolwich High Street London SE18", "Cafe", 35),
    ("restaurants Powis Street London SE18", "Restaurant", 50),
    ("cafes Powis Street London SE18", "Cafe", 30),
    ("restaurants Plumstead Road London SE18", "Restaurant", 50),
    ("cafes Plumstead Road London SE18", "Cafe", 30),
    ("restaurants Beresford Street London SE18", "Restaurant", 40),
    ("cafes Beresford Street London SE18", "Cafe", 20),
    ("restaurants General Gordon Square London SE18", "Restaurant", 45),
    ("cafes General Gordon Square London SE18", "Cafe", 25),
    ("restaurants Samuel Street London SE18", "Restaurant", 35),
    ("cafes Samuel Street London SE18", "Cafe", 20),
    ("restaurants Grand Depot Road London SE18", "Restaurant", 35),
    ("cafes Grand Depot Road London SE18", "Cafe", 20),

    # SE19 – Crystal Palace more streets
    ("restaurants Crystal Palace Parade London SE19", "Restaurant", 50),
    ("cafes Crystal Palace Parade London SE19", "Cafe", 30),
    ("restaurants Westow Hill London SE19", "Restaurant", 50),
    ("cafes Westow Hill London SE19", "Cafe", 30),
    ("restaurants Westow Street London SE19", "Restaurant", 45),
    ("cafes Westow Street London SE19", "Cafe", 25),
    ("restaurants Church Road Crystal Palace London SE19", "Restaurant", 45),
    ("cafes Church Road Crystal Palace London SE19", "Cafe", 25),
    ("restaurants Harold Road London SE19", "Restaurant", 35),
    ("cafes Harold Road London SE19", "Cafe", 20),
    ("restaurants Anerley Road London SE19", "Restaurant", 45),
    ("cafes Anerley Road London SE19", "Cafe", 25),

    # SE21 – Dulwich more streets
    ("restaurants Dulwich Village London SE21", "Restaurant", 55),
    ("cafes Dulwich Village London SE21", "Cafe", 35),
    ("restaurants Half Moon Lane London SE21", "Restaurant", 50),
    ("cafes Half Moon Lane London SE21", "Cafe", 30),
    ("restaurants Burbage Road London SE21", "Restaurant", 40),
    ("cafes Burbage Road London SE21", "Cafe", 20),
    ("restaurants Thurlow Park Road London SE21", "Restaurant", 40),
    ("cafes Thurlow Park Road London SE21", "Cafe", 20),
    ("restaurants College Road Dulwich London SE21", "Restaurant", 45),
    ("cafes College Road Dulwich London SE21", "Cafe", 25),

    # SE23 – Forest Hill more streets
    ("restaurants Dartmouth Road Forest Hill London SE23", "Restaurant", 50),
    ("cafes Dartmouth Road Forest Hill London SE23", "Cafe", 30),
    ("restaurants London Road Forest Hill London SE23", "Restaurant", 50),
    ("cafes London Road Forest Hill London SE23", "Cafe", 30),
    ("restaurants Devonshire Road London SE23", "Restaurant", 45),
    ("cafes Devonshire Road London SE23", "Cafe", 25),
    ("restaurants Perry Vale London SE23", "Restaurant", 40),
    ("cafes Perry Vale London SE23", "Cafe", 20),
    ("restaurants Stanstead Road London SE23", "Restaurant", 40),
    ("cafes Stanstead Road London SE23", "Cafe", 20),
    ("restaurants Waldram Park Road London SE23", "Restaurant", 35),
    ("cafes Waldram Park Road London SE23", "Cafe", 20),

    # SE25 – South Norwood more streets
    ("restaurants High Street South Norwood London SE25", "Restaurant", 50),
    ("cafes High Street South Norwood London SE25", "Cafe", 30),
    ("restaurants Portland Road London SE25", "Restaurant", 45),
    ("cafes Portland Road London SE25", "Cafe", 25),
    ("restaurants Whitehorse Lane London SE25", "Restaurant", 40),
    ("cafes Whitehorse Lane London SE25", "Cafe", 20),
    ("restaurants Selhurst Road London SE25", "Restaurant", 40),
    ("cafes Selhurst Road London SE25", "Cafe", 20),
    ("restaurants Oliver Grove London SE25", "Restaurant", 35),
    ("cafes Oliver Grove London SE25", "Cafe", 20),

    # SE26 – Sydenham more streets
    ("restaurants Sydenham Road London SE26", "Restaurant", 50),
    ("cafes Sydenham Road London SE26", "Cafe", 30),
    ("restaurants Kirkdale London SE26", "Restaurant", 50),
    ("cafes Kirkdale London SE26", "Cafe", 30),
    ("restaurants Dartmouth Road Sydenham London SE26", "Restaurant", 45),
    ("cafes Dartmouth Road Sydenham London SE26", "Cafe", 25),
    ("restaurants Bell Green London SE26", "Restaurant", 45),
    ("cafes Bell Green London SE26", "Cafe", 25),
    ("restaurants Queensthorpe Road London SE26", "Restaurant", 35),
    ("cafes Queensthorpe Road London SE26", "Cafe", 20),
    ("restaurants Silverdale London SE26", "Restaurant", 40),
    ("cafes Silverdale London SE26", "Cafe", 20),

    # SE1 – Southwark / Waterloo additional streets
    ("restaurants Borough Market London SE1", "Restaurant", 60),
    ("cafes Borough Market London SE1", "Cafe", 40),
    ("restaurants Bermondsey Street London SE1", "Restaurant", 55),
    ("cafes Bermondsey Street London SE1", "Cafe", 35),
    ("restaurants London Bridge Street London SE1", "Restaurant", 55),
    ("cafes London Bridge Street London SE1", "Cafe", 35),
    ("restaurants Union Street London SE1", "Restaurant", 50),
    ("cafes Union Street London SE1", "Cafe", 30),
    ("restaurants Waterloo Road London SE1", "Restaurant", 55),
    ("cafes Waterloo Road London SE1", "Cafe", 35),
    ("restaurants The Cut London SE1", "Restaurant", 55),
    ("cafes The Cut London SE1", "Cafe", 35),
    ("restaurants Tooley Street London SE1", "Restaurant", 50),
    ("cafes Tooley Street London SE1", "Cafe", 30),
    ("restaurants Southwark Street London SE1", "Restaurant", 55),
    ("cafes Southwark Street London SE1", "Cafe", 35),

    # SE11 – Kennington / Lambeth
    ("restaurants Kennington Road London SE11", "Restaurant", 50),
    ("cafes Kennington Road London SE11", "Cafe", 30),
    ("restaurants Kennington Lane London SE11", "Restaurant", 45),
    ("cafes Kennington Lane London SE11", "Cafe", 25),
    ("restaurants Kennington Park Road London SE11", "Restaurant", 50),
    ("cafes Kennington Park Road London SE11", "Cafe", 30),

    # SE15 – Peckham more streets
    ("restaurants Nunhead Lane London SE15", "Restaurant", 40),
    ("cafes Nunhead Lane London SE15", "Cafe", 20),
    ("restaurants Queens Road Peckham London SE15", "Restaurant", 50),
    ("cafes Queens Road Peckham London SE15", "Cafe", 30),
    ("restaurants Nunhead Green London SE15", "Restaurant", 35),
    ("cafes Nunhead Green London SE15", "Cafe", 20),
]
