"""
Batch 79 - Greek, Cypriot, Armenian, Georgian, Eastern European, Scandinavian,
American BBQ, Argentinian, Peruvian, Malaysian, Indonesian, Singaporean,
Burmese, Tibetan, Afghani, Yemeni niche cuisine x London.
"""

SEARCH_QUERIES = [
    # Greek / Cypriot restaurants x London
    "Greek restaurants London N1",
    "Greek restaurants London N4",
    "Greek restaurants London N8",
    "Greek restaurants London N22",
    "Greek restaurants London NW1",
    "Greek restaurants London NW3",
    "Greek restaurants London NW6",
    "Greek restaurants London W1",
    "Greek restaurants London WC2",
    "Greek restaurants London SE1",
    "Greek restaurants London SW1",
    "Greek restaurants London SW3",
    "Greek restaurants London EC1",
    "Greek restaurants London E1",
    "Greek restaurants Green Lanes London",
    "Greek restaurants Wood Green London",
    "Greek restaurants Haringey London",
    "Greek restaurants Camden London",
    "Greek restaurants Islington London",
    "Greek restaurants Hackney London",
    "Greek meze London N4",
    "Greek meze London NW1",
    "Greek meze London W1",
    "Greek meze London WC2",
    "Cypriot restaurant London N4",
    "Cypriot restaurant London N22",
    "Cypriot restaurant London NW1",
    "Cypriot restaurant London NW6",
    "Cypriot restaurant London W1",
    "Cypriot restaurant Green Lanes London",
    "Cypriot restaurant Wood Green London",
    "Cypriot restaurant Palmers Green London",
    "Cypriot meze London",
    "souvlaki London W1",
    "souvlaki London WC2",
    "souvlaki London E1",
    "souvlaki London N1",
    "souvlaki London SE1",
    "souvlaki London NW1",
    "souvlaki Shoreditch London",
    "souvlaki Hackney London",
    # Georgian restaurants x London
    "Georgian restaurant London W1",
    "Georgian restaurant London WC2",
    "Georgian restaurant London EC1",
    "Georgian restaurant London E1",
    "Georgian restaurant London N1",
    "Georgian restaurant London SE1",
    "Georgian restaurant London SW1",
    "Georgian restaurant London NW1",
    "Georgian restaurant Soho London",
    "Georgian restaurant Shoreditch London",
    "Georgian restaurant Islington London",
    "Georgian restaurant Chelsea London",
    "Georgian wine London",
    "khinkali London",
    # Armenian restaurants x London
    "Armenian restaurant London W1",
    "Armenian restaurant London NW1",
    "Armenian restaurant London WC2",
    "Armenian restaurant London EC1",
    "Armenian restaurant London N1",
    "Armenian restaurant London SE1",
    # Eastern European restaurants x London
    "Eastern European restaurant London E1",
    "Eastern European restaurant London N1",
    "Eastern European restaurant London SE1",
    "Eastern European restaurant London W1",
    "Eastern European restaurant London WC2",
    "Eastern European restaurant London EC1",
    "Eastern European restaurant London NW1",
    "Eastern European restaurant London NW6",
    "Polish restaurant London E1",
    "Polish restaurant London N1",
    "Polish restaurant London SE1",
    "Polish restaurant London SW4",
    "Polish restaurant London W1",
    "Polish restaurant London WC2",
    "Polish restaurant London EC1",
    "Polish restaurant London NW1",
    "Polish restaurant London NW6",
    "Polish restaurant Ealing London",
    "Polish restaurant Hammersmith London",
    "Polish deli London NW6",
    "Polish deli London W12",
    "Polish deli London EC1",
    "Polish deli London NW1",
    "Polish deli London E1",
    "Russian restaurant London W1",
    "Russian restaurant London WC2",
    "Russian restaurant London SW1",
    "Russian restaurant London SW3",
    "Russian restaurant London NW1",
    "Russian restaurant London EC1",
    "Ukrainian restaurant London N1",
    "Ukrainian restaurant London E1",
    "Ukrainian restaurant London SE1",
    "Ukrainian restaurant London NW1",
    "Romanian restaurant London E1",
    "Romanian restaurant London N1",
    "Romanian restaurant London SE1",
    "Romanian restaurant London W1",
    "Romanian restaurant London NW1",
    "Czech restaurant London W1",
    "Czech restaurant London EC1",
    "Hungarian restaurant London W1",
    "Hungarian restaurant London NW1",
    "Balkan restaurant London W1",
    "Balkan restaurant London N1",
    "Balkan restaurant London SE1",
    # Scandinavian restaurants x London
    "Scandinavian restaurant London W1",
    "Scandinavian restaurant London WC2",
    "Scandinavian restaurant London EC1",
    "Scandinavian restaurant London EC2",
    "Scandinavian restaurant London E1",
    "Scandinavian restaurant London N1",
    "Scandinavian restaurant London SE1",
    "Scandinavian restaurant London NW1",
    "Nordic restaurant London W1",
    "Nordic restaurant London EC1",
    "Nordic restaurant London SE1",
    "Nordic restaurant London NW1",
    "smorgasbord London",
    "Swedish restaurant London W1",
    "Swedish restaurant London WC2",
    "Swedish fika London",
    "Danish restaurant London W1",
    "Danish smørrebrød London",
    # American BBQ x London
    "American BBQ restaurant London E1",
    "American BBQ restaurant London N1",
    "American BBQ restaurant London SE1",
    "American BBQ restaurant London SW4",
    "American BBQ restaurant London SW9",
    "American BBQ restaurant London SW11",
    "American BBQ restaurant London W1",
    "American BBQ restaurant London WC2",
    "American BBQ restaurant London EC1",
    "American BBQ restaurant London NW1",
    "BBQ restaurant Shoreditch London",
    "BBQ restaurant Brixton London",
    "BBQ restaurant Hackney London",
    "BBQ restaurant Dalston London",
    "BBQ restaurant Camden London",
    "BBQ restaurant Islington London",
    "smokehouse London E1",
    "smokehouse London N1",
    "smokehouse London SE1",
    "smokehouse London SW4",
    "smokehouse London W1",
    "smokehouse London WC2",
    "smokehouse London EC1",
    "smokehouse London NW1",
    "smokehouse Shoreditch London",
    "smokehouse Brixton London",
    # Argentinian / Latin American restaurants x London
    "Argentinian restaurant London W1",
    "Argentinian restaurant London WC2",
    "Argentinian restaurant London EC1",
    "Argentinian restaurant London E1",
    "Argentinian restaurant London N1",
    "Argentinian restaurant London SE1",
    "Argentinian restaurant London SW4",
    "Argentinian restaurant London NW1",
    "Argentinian steakhouse London",
    "Argentinian grill London",
    "asado London",
    "Peruvian restaurant London W1",
    "Peruvian restaurant London WC2",
    "Peruvian restaurant London EC1",
    "Peruvian restaurant London E1",
    "Peruvian restaurant London N1",
    "Peruvian restaurant London SE1",
    "Peruvian restaurant London SW1",
    "Peruvian restaurant London NW1",
    "ceviche London W1",
    "ceviche London WC2",
    "ceviche London EC1",
    "ceviche London SE1",
    "Colombian restaurant London W1",
    "Colombian restaurant London N1",
    "Colombian restaurant London SE1",
    "Colombian restaurant London NW1",
    "Venezuelan restaurant London W1",
    "Venezuelan restaurant London SE1",
    # Malaysian / Indonesian / Singaporean x London
    "Malaysian restaurant London W1",
    "Malaysian restaurant London WC2",
    "Malaysian restaurant London EC1",
    "Malaysian restaurant London E1",
    "Malaysian restaurant London N1",
    "Malaysian restaurant London SE1",
    "Malaysian restaurant London NW1",
    "Malaysian restaurant London SW1",
    "Malaysian restaurant Chinatown London",
    "Malaysian restaurant Soho London",
    "Indonesian restaurant London W1",
    "Indonesian restaurant London WC2",
    "Indonesian restaurant London EC1",
    "Indonesian restaurant London E1",
    "Indonesian restaurant London SE1",
    "Indonesian restaurant London NW1",
    "Singaporean restaurant London W1",
    "Singaporean restaurant London WC2",
    "Singaporean restaurant London EC1",
    "Singaporean restaurant London SE1",
    "laksa London W1",
    "laksa London WC2",
    "laksa London EC1",
    "laksa London SE1",
    "nasi lemak London",
    "satay restaurant London W1",
    "satay restaurant London WC2",
    "satay restaurant London SE1",
    # Burmese / Tibetan / Afghani / Yemeni
    "Burmese restaurant London W1",
    "Burmese restaurant London WC2",
    "Burmese restaurant London EC1",
    "Burmese restaurant London N1",
    "Burmese restaurant London SE1",
    "Burmese restaurant London NW1",
    "Tibetan restaurant London W1",
    "Tibetan restaurant London NW1",
    "Tibetan restaurant London N1",
    "Afghani restaurant London W1",
    "Afghani restaurant London NW1",
    "Afghani restaurant London N1",
    "Afghani restaurant London SW1",
    "Afghani restaurant London WC2",
    "Afghan restaurant London Wembley",
    "Afghan restaurant London Southall",
    "Yemeni restaurant London E1",
    "Yemeni restaurant London N1",
    "Yemeni restaurant London SE1",
    "Yemeni restaurant London NW1",
    "Yemeni restaurant London W1",
    "Yemeni restaurant Whitechapel London",
    "Somali restaurant London N1",
    "Somali restaurant London NW1",
    "Somali restaurant London SW9",
    "Somali restaurant Brixton London",
    "Somali restaurant Tottenham London",
    # Israeli / Jewish deli / falafel
    "Israeli restaurant London N1",
    "Israeli restaurant London NW1",
    "Israeli restaurant London NW3",
    "Israeli restaurant London NW11",
    "Israeli restaurant London W1",
    "Israeli restaurant London WC2",
    "falafel London E1",
    "falafel London N1",
    "falafel London NW1",
    "falafel London W1",
    "falafel London WC2",
    "falafel London SE1",
    "falafel Shoreditch London",
    "falafel Hackney London",
    "falafel Camden London",
    "falafel Brixton London",
    "falafel Dalston London",
    "hummus restaurant London W1",
    "hummus restaurant London N1",
    "hummus restaurant London SE1",
    "hummus restaurant London NW1",
    "shawarma London E1",
    "shawarma London N1",
    "shawarma London SE1",
    "shawarma London W1",
    "shawarma London WC2",
    "shawarma London NW1",
    "shawarma London EC1",
]
