"""
Batch 58 – Systematic W/SW streets: W3 Acton, W5 Ealing, W6 Hammersmith, W7 Hanwell,
W8 Kensington, W12 Shepherd's Bush, W13 West Ealing, SW1 Victoria/Pimlico,
SW2 Brixton/Streatham, SW6 Fulham, SW8 Vauxhall/Nine Elms, SW12 Balham,
SW16 Streatham, SW17 Tooting, SW18 Wandsworth, SW19 Wimbledon, SW20 Raynes Park/Morden
"""

SEARCH_QUERIES = [
    # W3 – Acton more streets
    ("restaurants High Street Acton London W3", "Restaurant", 55),
    ("cafes High Street Acton London W3", "Cafe", 35),
    ("restaurants The Vale Acton London W3", "Restaurant", 50),
    ("cafes The Vale Acton London W3", "Cafe", 30),
    ("restaurants Churchfield Road London W3", "Restaurant", 45),
    ("cafes Churchfield Road London W3", "Cafe", 25),
    ("restaurants Horn Lane London W3", "Restaurant", 45),
    ("cafes Horn Lane London W3", "Cafe", 25),
    ("restaurants Old Oak Common Lane London W3", "Restaurant", 40),
    ("cafes Old Oak Common Lane London W3", "Cafe", 20),
    ("restaurants Acton Lane London W3", "Restaurant", 45),
    ("cafes Acton Lane London W3", "Cafe", 25),
    ("restaurants Steyne Road London W3", "Restaurant", 35),
    ("cafes Steyne Road London W3", "Cafe", 20),

    # W5 – Ealing more streets
    ("restaurants Ealing Broadway London W5", "Restaurant", 55),
    ("cafes Ealing Broadway London W5", "Cafe", 35),
    ("restaurants New Broadway Ealing London W5", "Restaurant", 55),
    ("cafes New Broadway Ealing London W5", "Cafe", 35),
    ("restaurants The Mall Ealing London W5", "Restaurant", 50),
    ("cafes The Mall Ealing London W5", "Cafe", 30),
    ("restaurants Northfield Avenue London W5", "Restaurant", 45),
    ("cafes Northfield Avenue London W5", "Cafe", 25),
    ("restaurants Bond Street Ealing London W5", "Restaurant", 50),
    ("cafes Bond Street Ealing London W5", "Cafe", 30),
    ("restaurants Uxbridge Road Ealing London W5", "Restaurant", 55),
    ("cafes Uxbridge Road Ealing London W5", "Cafe", 35),
    ("restaurants South Ealing Road London W5", "Restaurant", 45),
    ("cafes South Ealing Road London W5", "Cafe", 25),

    # W6 – Hammersmith more streets
    ("restaurants King Street Hammersmith London W6", "Restaurant", 55),
    ("cafes King Street Hammersmith London W6", "Cafe", 35),
    ("restaurants Beadon Road London W6", "Restaurant", 40),
    ("cafes Beadon Road London W6", "Cafe", 20),
    ("restaurants Fulham Palace Road London W6", "Restaurant", 55),
    ("cafes Fulham Palace Road London W6", "Cafe", 35),
    ("restaurants Shepherds Bush Road London W6", "Restaurant", 50),
    ("cafes Shepherds Bush Road London W6", "Cafe", 30),
    ("restaurants Chiswick High Road London W6", "Restaurant", 55),
    ("cafes Chiswick High Road London W6", "Cafe", 35),
    ("restaurants Goldhawk Road London W6", "Restaurant", 50),
    ("cafes Goldhawk Road London W6", "Cafe", 30),
    ("restaurants Hammersmith Grove London W6", "Restaurant", 45),
    ("cafes Hammersmith Grove London W6", "Cafe", 25),

    # W7 – Hanwell
    ("restaurants Uxbridge Road Hanwell London W7", "Restaurant", 50),
    ("cafes Uxbridge Road Hanwell London W7", "Cafe", 30),
    ("restaurants Green Man Lane London W7", "Restaurant", 40),
    ("cafes Green Man Lane London W7", "Cafe", 20),
    ("restaurants Boston Road Hanwell London W7", "Restaurant", 45),
    ("cafes Boston Road Hanwell London W7", "Cafe", 25),
    ("restaurants Church Road Hanwell London W7", "Restaurant", 40),
    ("cafes Church Road Hanwell London W7", "Cafe", 20),
    ("restaurants Lower Boston Road London W7", "Restaurant", 35),
    ("cafes Lower Boston Road London W7", "Cafe", 20),
    ("restaurants Broadway Hanwell London W7", "Restaurant", 45),
    ("cafes Broadway Hanwell London W7", "Cafe", 25),

    # W8 – Kensington more streets
    ("restaurants Kensington Church Street London W8", "Restaurant", 55),
    ("cafes Kensington Church Street London W8", "Cafe", 35),
    ("restaurants Kensington High Street London W8", "Restaurant", 55),
    ("cafes Kensington High Street London W8", "Cafe", 35),
    ("restaurants Hillgate Street London W8", "Restaurant", 40),
    ("cafes Hillgate Street London W8", "Cafe", 20),
    ("restaurants Campden Hill Road London W8", "Restaurant", 45),
    ("cafes Campden Hill Road London W8", "Cafe", 25),
    ("restaurants Allen Street London W8", "Restaurant", 40),
    ("cafes Allen Street London W8", "Cafe", 20),
    ("restaurants Kensington Court London W8", "Restaurant", 45),
    ("cafes Kensington Court London W8", "Cafe", 25),

    # W12 – Shepherd's Bush more streets
    ("restaurants Shepherd's Bush Road London W12", "Restaurant", 55),
    ("cafes Shepherd's Bush Road London W12", "Cafe", 35),
    ("restaurants Uxbridge Road Shepherd's Bush London W12", "Restaurant", 55),
    ("cafes Uxbridge Road Shepherd's Bush London W12", "Cafe", 35),
    ("restaurants Goldhawk Road London W12", "Restaurant", 50),
    ("cafes Goldhawk Road London W12", "Cafe", 30),
    ("restaurants Wood Lane London W12", "Restaurant", 50),
    ("cafes Wood Lane London W12", "Cafe", 30),
    ("restaurants Askew Road London W12", "Restaurant", 45),
    ("cafes Askew Road London W12", "Cafe", 25),
    ("restaurants Lime Grove London W12", "Restaurant", 40),
    ("cafes Lime Grove London W12", "Cafe", 20),

    # W13 – West Ealing more streets
    ("restaurants Broadway West Ealing London W13", "Restaurant", 55),
    ("cafes Broadway West Ealing London W13", "Cafe", 35),
    ("restaurants Northfield Avenue London W13", "Restaurant", 50),
    ("cafes Northfield Avenue London W13", "Cafe", 30),
    ("restaurants Uxbridge Road West Ealing London W13", "Restaurant", 55),
    ("cafes Uxbridge Road West Ealing London W13", "Cafe", 35),
    ("restaurants Gordon Road West Ealing London W13", "Restaurant", 40),
    ("cafes Gordon Road West Ealing London W13", "Cafe", 20),
    ("restaurants Drayton Green Road London W13", "Restaurant", 35),
    ("cafes Drayton Green Road London W13", "Cafe", 20),

    # SW1 – Victoria / Pimlico more streets
    ("restaurants Victoria Street London SW1", "Restaurant", 55),
    ("cafes Victoria Street London SW1", "Cafe", 35),
    ("restaurants Buckingham Palace Road London SW1", "Restaurant", 55),
    ("cafes Buckingham Palace Road London SW1", "Cafe", 35),
    ("restaurants Wilton Road London SW1", "Restaurant", 55),
    ("cafes Wilton Road London SW1", "Cafe", 35),
    ("restaurants Vauxhall Bridge Road London SW1", "Restaurant", 50),
    ("cafes Vauxhall Bridge Road London SW1", "Cafe", 30),
    ("restaurants Pimlico Road London SW1", "Restaurant", 55),
    ("cafes Pimlico Road London SW1", "Cafe", 35),
    ("restaurants Tachbrook Street London SW1", "Restaurant", 50),
    ("cafes Tachbrook Street London SW1", "Cafe", 30),
    ("restaurants Warwick Way London SW1", "Restaurant", 45),
    ("cafes Warwick Way London SW1", "Cafe", 25),

    # SW2 – Brixton / Streatham Hill more streets
    ("restaurants Brixton Hill London SW2", "Restaurant", 55),
    ("cafes Brixton Hill London SW2", "Cafe", 35),
    ("restaurants Streatham Hill London SW2", "Restaurant", 50),
    ("cafes Streatham Hill London SW2", "Cafe", 30),
    ("restaurants Tulse Hill London SW2", "Restaurant", 50),
    ("cafes Tulse Hill London SW2", "Cafe", 30),
    ("restaurants Acre Lane London SW2", "Restaurant", 50),
    ("cafes Acre Lane London SW2", "Cafe", 30),
    ("restaurants Effra Road London SW2", "Restaurant", 45),
    ("cafes Effra Road London SW2", "Cafe", 25),
    ("restaurants Coldharbour Lane London SW2", "Restaurant", 55),
    ("cafes Coldharbour Lane London SW2", "Cafe", 35),
    ("restaurants Water Lane London SW2", "Restaurant", 35),
    ("cafes Water Lane London SW2", "Cafe", 20),

    # SW6 – Fulham more streets
    ("restaurants Fulham Road London SW6", "Restaurant", 55),
    ("cafes Fulham Road London SW6", "Cafe", 35),
    ("restaurants New Kings Road London SW6", "Restaurant", 55),
    ("cafes New Kings Road London SW6", "Cafe", 35),
    ("restaurants North End Road Fulham London SW6", "Restaurant", 55),
    ("cafes North End Road Fulham London SW6", "Cafe", 35),
    ("restaurants Munster Road London SW6", "Restaurant", 45),
    ("cafes Munster Road London SW6", "Cafe", 25),
    ("restaurants Dawes Road London SW6", "Restaurant", 45),
    ("cafes Dawes Road London SW6", "Cafe", 25),
    ("restaurants Moore Park Road London SW6", "Restaurant", 40),
    ("cafes Moore Park Road London SW6", "Cafe", 20),

    # SW8 – Vauxhall / Nine Elms more streets
    ("restaurants Nine Elms Lane London SW8", "Restaurant", 55),
    ("cafes Nine Elms Lane London SW8", "Cafe", 35),
    ("restaurants Wandsworth Road London SW8", "Restaurant", 55),
    ("cafes Wandsworth Road London SW8", "Cafe", 35),
    ("restaurants Vauxhall Cross London SW8", "Restaurant", 50),
    ("cafes Vauxhall Cross London SW8", "Cafe", 30),
    ("restaurants South Lambeth Road London SW8", "Restaurant", 50),
    ("cafes South Lambeth Road London SW8", "Cafe", 30),
    ("restaurants Lansdowne Way London SW8", "Restaurant", 40),
    ("cafes Lansdowne Way London SW8", "Cafe", 20),
    ("restaurants Battersea Park Road London SW8", "Restaurant", 50),
    ("cafes Battersea Park Road London SW8", "Cafe", 30),

    # SW12 – Balham more streets
    ("restaurants Balham High Road London SW12", "Restaurant", 55),
    ("cafes Balham High Road London SW12", "Cafe", 35),
    ("restaurants Bedford Hill London SW12", "Restaurant", 50),
    ("cafes Bedford Hill London SW12", "Cafe", 30),
    ("restaurants Tooting Bec Road London SW12", "Restaurant", 50),
    ("cafes Tooting Bec Road London SW12", "Cafe", 30),
    ("restaurants Clapham South London SW12", "Restaurant", 50),
    ("cafes Clapham South London SW12", "Cafe", 30),
    ("restaurants Cavendish Road London SW12", "Restaurant", 40),
    ("cafes Cavendish Road London SW12", "Cafe", 20),
    ("restaurants Du Cane Court London SW12", "Restaurant", 35),
    ("cafes Chestnut Grove London SW12", "Cafe", 20),

    # SW16 – Streatham more streets
    ("restaurants Streatham High Road London SW16", "Restaurant", 55),
    ("cafes Streatham High Road London SW16", "Cafe", 35),
    ("restaurants Greyhound Lane London SW16", "Restaurant", 45),
    ("cafes Greyhound Lane London SW16", "Cafe", 25),
    ("restaurants Streatham Common North London SW16", "Restaurant", 45),
    ("cafes Streatham Common North London SW16", "Cafe", 25),
    ("restaurants Streatham Vale London SW16", "Restaurant", 45),
    ("cafes Streatham Vale London SW16", "Cafe", 25),
    ("restaurants Norbury Avenue London SW16", "Restaurant", 40),
    ("cafes Norbury Avenue London SW16", "Cafe", 20),

    # SW17 – Tooting more streets
    ("restaurants Tooting High Street London SW17", "Restaurant", 55),
    ("cafes Tooting High Street London SW17", "Cafe", 35),
    ("restaurants Upper Tooting Road London SW17", "Restaurant", 55),
    ("cafes Upper Tooting Road London SW17", "Cafe", 35),
    ("restaurants Mitcham Road Tooting London SW17", "Restaurant", 50),
    ("cafes Mitcham Road Tooting London SW17", "Cafe", 30),
    ("restaurants Garratt Lane London SW17", "Restaurant", 50),
    ("cafes Garratt Lane London SW17", "Cafe", 30),
    ("restaurants Longley Road London SW17", "Restaurant", 35),
    ("cafes Longley Road London SW17", "Cafe", 20),
    ("restaurants Trinity Road Tooting London SW17", "Restaurant", 40),
    ("cafes Trinity Road Tooting London SW17", "Cafe", 20),

    # SW18 – Wandsworth more streets
    ("restaurants Wandsworth High Street London SW18", "Restaurant", 55),
    ("cafes Wandsworth High Street London SW18", "Cafe", 35),
    ("restaurants East Hill Wandsworth London SW18", "Restaurant", 50),
    ("cafes East Hill Wandsworth London SW18", "Cafe", 30),
    ("restaurants Garratt Lane Wandsworth London SW18", "Restaurant", 50),
    ("cafes Garratt Lane Wandsworth London SW18", "Cafe", 30),
    ("restaurants Jew's Row London SW18", "Restaurant", 40),
    ("cafes Jew's Row London SW18", "Cafe", 20),
    ("restaurants Merton Road Wandsworth London SW18", "Restaurant", 45),
    ("cafes Merton Road Wandsworth London SW18", "Cafe", 25),

    # SW19 – Wimbledon more streets
    ("restaurants Wimbledon Village London SW19", "Restaurant", 55),
    ("cafes Wimbledon Village London SW19", "Cafe", 35),
    ("restaurants The Broadway Wimbledon London SW19", "Restaurant", 55),
    ("cafes The Broadway Wimbledon London SW19", "Cafe", 35),
    ("restaurants Wimbledon Hill Road London SW19", "Restaurant", 50),
    ("cafes Wimbledon Hill Road London SW19", "Cafe", 30),
    ("restaurants Hartfield Road London SW19", "Restaurant", 45),
    ("cafes Hartfield Road London SW19", "Cafe", 25),
    ("restaurants Merton Road Wimbledon London SW19", "Restaurant", 45),
    ("cafes Merton Road Wimbledon London SW19", "Cafe", 25),
    ("restaurants Wimbledon Road London SW19", "Restaurant", 45),
    ("cafes South Wimbledon London SW19", "Cafe", 25),

    # SW20 – Raynes Park / Morden area
    ("restaurants Raynes Park London SW20", "Restaurant", 50),
    ("cafes Raynes Park London SW20", "Cafe", 30),
    ("restaurants Wimbledon Chase London SW20", "Restaurant", 45),
    ("cafes Wimbledon Chase London SW20", "Cafe", 25),
    ("restaurants West Barnes Lane London SW20", "Restaurant", 40),
    ("cafes West Barnes Lane London SW20", "Cafe", 20),
    ("restaurants Durham Road London SW20", "Restaurant", 35),
    ("cafes Durham Road London SW20", "Cafe", 20),
    ("restaurants Bushey Road London SW20", "Restaurant", 40),
    ("cafes Bushey Road London SW20", "Cafe", 20),
    ("restaurants Grand Drive London SW20", "Restaurant", 35),
    ("cafes Grand Drive London SW20", "Cafe", 20),

    # W1 – Marylebone / Fitzrovia / Oxford Street extra streets
    ("restaurants Marylebone High Street London W1", "Restaurant", 60),
    ("cafes Marylebone High Street London W1", "Cafe", 40),
    ("restaurants Wigmore Street London W1", "Restaurant", 55),
    ("cafes Wigmore Street London W1", "Cafe", 35),
    ("restaurants Welbeck Street London W1", "Restaurant", 50),
    ("cafes Welbeck Street London W1", "Cafe", 30),
    ("restaurants Goodge Street London W1", "Restaurant", 55),
    ("cafes Goodge Street London W1", "Cafe", 35),
    ("restaurants Charlotte Street London W1", "Restaurant", 60),
    ("cafes Charlotte Street London W1", "Cafe", 40),
    ("restaurants Fitzrovia London W1T", "Restaurant", 55),
    ("cafes Fitzrovia London W1T", "Cafe", 35),

    # W2 – Paddington / Bayswater extra streets
    ("restaurants Westbourne Grove London W2", "Restaurant", 55),
    ("cafes Westbourne Grove London W2", "Cafe", 35),
    ("restaurants Queensway London W2", "Restaurant", 55),
    ("cafes Queensway London W2", "Cafe", 35),
    ("restaurants Praed Street London W2", "Restaurant", 50),
    ("cafes Praed Street London W2", "Cafe", 30),

    # W4 – Chiswick extra streets
    ("restaurants Chiswick High Road London W4", "Restaurant", 55),
    ("cafes Chiswick High Road London W4", "Cafe", 35),
    ("restaurants Turnham Green Terrace London W4", "Restaurant", 55),
    ("cafes Turnham Green Terrace London W4", "Cafe", 35),
    ("restaurants Devonshire Road Chiswick London W4", "Restaurant", 50),
    ("cafes Devonshire Road Chiswick London W4", "Cafe", 30),
    ("restaurants High Road Chiswick London W4", "Restaurant", 50),
    ("cafes High Road Chiswick London W4", "Cafe", 30),

    # SW3 – Chelsea / SW10 extra streets
    ("restaurants Kings Road London SW3", "Restaurant", 60),
    ("cafes Kings Road London SW3", "Cafe", 40),
    ("restaurants Sloane Square London SW1W", "Restaurant", 55),
    ("cafes Sloane Square London SW1W", "Cafe", 35),
    ("restaurants Fulham Road Chelsea London SW3", "Restaurant", 55),
    ("cafes Fulham Road Chelsea London SW3", "Cafe", 35),
    ("restaurants World's End London SW10", "Restaurant", 50),
    ("cafes World's End London SW10", "Cafe", 30),

    # SW4 – Clapham extra streets
    ("restaurants Clapham High Street London SW4", "Restaurant", 60),
    ("cafes Clapham High Street London SW4", "Cafe", 40),
    ("restaurants Clapham Old Town London SW4", "Restaurant", 55),
    ("cafes Clapham Old Town London SW4", "Cafe", 35),
    ("restaurants Venn Street London SW4", "Restaurant", 50),
    ("cafes Venn Street London SW4", "Cafe", 30),
    ("restaurants Abbeville Road London SW4", "Restaurant", 50),
    ("cafes Abbeville Road London SW4", "Cafe", 30),
]
