"""
Batch 80 - Venue types, dining experiences, and remaining niche London areas:
Steakhouse, seafood, oyster bar, sushi train, teppanyaki, fondue, shabu shabu,
hot pot, omakase, chef's table, fine dining, Michelin restaurants, food trucks,
plus remaining outer London: Croydon extended, Harrow extended, Hillingdon extended,
Greenwich extended, Lewisham extended, Sutton extended.
"""

SEARCH_QUERIES = [
    # Steakhouse x London postcodes
    "steakhouse London E1",
    "steakhouse London E2",
    "steakhouse London E14",
    "steakhouse London N1",
    "steakhouse London SE1",
    "steakhouse London SW1",
    "steakhouse London SW3",
    "steakhouse London SW7",
    "steakhouse London W1",
    "steakhouse London W4",
    "steakhouse London W6",
    "steakhouse London W8",
    "steakhouse London WC2",
    "steakhouse London EC1",
    "steakhouse London EC2",
    "steakhouse London NW1",
    "steakhouse London NW3",
    "steakhouse Mayfair London",
    "steakhouse Soho London",
    "steakhouse Chelsea London",
    "steakhouse Shoreditch London",
    "steakhouse Canary Wharf London",
    "steakhouse City of London",
    "steakhouse Brixton London",
    "steakhouse Hackney London",
    "steakhouse Clapham London",
    "steakhouse Islington London",
    # Seafood restaurant x London
    "seafood restaurant London E1",
    "seafood restaurant London E14",
    "seafood restaurant London N1",
    "seafood restaurant London SE1",
    "seafood restaurant London SW1",
    "seafood restaurant London SW3",
    "seafood restaurant London SW6",
    "seafood restaurant London SW7",
    "seafood restaurant London W1",
    "seafood restaurant London W2",
    "seafood restaurant London W4",
    "seafood restaurant London W8",
    "seafood restaurant London WC2",
    "seafood restaurant London EC1",
    "seafood restaurant London EC2",
    "seafood restaurant London NW1",
    "seafood restaurant London NW3",
    "seafood restaurant Mayfair London",
    "seafood restaurant Chelsea London",
    "seafood restaurant Kensington London",
    "seafood restaurant Canary Wharf London",
    "seafood restaurant Borough London",
    "seafood restaurant Shoreditch London",
    "seafood restaurant Bermondsey London",
    # Oyster bar x London
    "oyster bar London E1",
    "oyster bar London SE1",
    "oyster bar London SW1",
    "oyster bar London SW3",
    "oyster bar London W1",
    "oyster bar London W4",
    "oyster bar London WC2",
    "oyster bar London EC1",
    "oyster bar London EC2",
    "oyster bar London NW1",
    "oyster bar Mayfair London",
    "oyster bar Chelsea London",
    "oyster bar Soho London",
    "oyster bar Borough London",
    "oyster bar Canary Wharf London",
    "oyster bar Shoreditch London",
    "oyster bar Brixton London",
    "oyster bar Hackney London",
    # Hot pot / shabu shabu / teppanyaki x London
    "hot pot restaurant London W1",
    "hot pot restaurant London WC2",
    "hot pot restaurant London EC1",
    "hot pot restaurant London E1",
    "hot pot restaurant London N1",
    "hot pot restaurant London SE1",
    "hot pot restaurant London NW1",
    "hot pot restaurant Chinatown London",
    "hot pot restaurant Soho London",
    "shabu shabu London W1",
    "shabu shabu London WC2",
    "shabu shabu London EC1",
    "shabu shabu London SE1",
    "shabu shabu London NW1",
    "teppanyaki London W1",
    "teppanyaki London WC2",
    "teppanyaki London EC1",
    "teppanyaki London SW1",
    "teppanyaki London SE1",
    "teppanyaki London NW1",
    "teppanyaki Mayfair London",
    "teppanyaki Chelsea London",
    # Omakase / chef's table / fine dining x London
    "omakase London W1",
    "omakase London WC2",
    "omakase London EC1",
    "omakase London EC2",
    "omakase London SW1",
    "omakase London SW3",
    "omakase London SE1",
    "omakase London NW1",
    "omakase Mayfair London",
    "omakase Chelsea London",
    "omakase Soho London",
    "omakase Shoreditch London",
    "chef's table London W1",
    "chef's table London SW1",
    "chef's table London EC1",
    "chef's table London SE1",
    "chef's table London WC2",
    "chef's table London NW1",
    "fine dining London E1",
    "fine dining London E14",
    "fine dining London N1",
    "fine dining London SE1",
    "fine dining London SW1",
    "fine dining London SW3",
    "fine dining London SW7",
    "fine dining London W1",
    "fine dining London W4",
    "fine dining London W8",
    "fine dining London WC2",
    "fine dining London EC1",
    "fine dining London EC2",
    "fine dining London NW1",
    "fine dining London NW3",
    "fine dining Mayfair London",
    "fine dining Chelsea London",
    "fine dining Kensington London",
    "fine dining Shoreditch London",
    "fine dining Brixton London",
    "Michelin restaurant London W1",
    "Michelin restaurant London SW1",
    "Michelin restaurant London SW3",
    "Michelin restaurant London WC2",
    "Michelin restaurant London EC1",
    "Michelin restaurant London SE1",
    "Michelin restaurant London NW1",
    "Michelin star restaurant Mayfair London",
    "Michelin star restaurant Chelsea London",
    "Michelin star restaurant Shoreditch London",
    # Tasting menu restaurants x London
    "tasting menu restaurant London W1",
    "tasting menu restaurant London SW1",
    "tasting menu restaurant London EC1",
    "tasting menu restaurant London SE1",
    "tasting menu restaurant London WC2",
    "tasting menu restaurant London NW1",
    "tasting menu Mayfair London",
    "tasting menu Chelsea London",
    "set menu restaurant London W1",
    "set menu restaurant London WC2",
    "set menu restaurant London EC1",
    "set menu restaurant London SE1",
    # Fondue / raclette x London
    "fondue restaurant London W1",
    "fondue restaurant London WC2",
    "fondue restaurant London EC1",
    "fondue restaurant London SE1",
    "fondue restaurant London NW1",
    "fondue restaurant London N1",
    "raclette London W1",
    "raclette London WC2",
    "raclette London EC1",
    "Swiss restaurant London W1",
    "Swiss restaurant London WC2",
    "Swiss restaurant London SE1",
    # Extended outer London - remaining areas
    # Harrow additional
    "restaurants Harrow on the Hill London HA1",
    "cafes Harrow on the Hill London HA1",
    "restaurants Pinner London HA5",
    "cafes Pinner London HA5",
    "restaurants Stanmore London HA7",
    "cafes Stanmore London HA7",
    "restaurants Kenton London HA3",
    "cafes Kenton London HA3",
    "restaurants Wealdstone London HA3",
    "cafes Wealdstone London HA3",
    "Indian restaurant Pinner London HA5",
    "brunch Pinner London HA5",
    "gastropub Pinner London HA5",
    "gastropub Stanmore London HA7",
    # Hillingdon extended
    "restaurants Hayes London UB3",
    "cafes Hayes London UB3",
    "restaurants West Drayton London UB7",
    "cafes West Drayton London UB7",
    "restaurants Yiewsley London UB7",
    "restaurants Uxbridge London UB8",
    "cafes Uxbridge London UB8",
    "restaurants Uxbridge High Street London UB8",
    "Indian restaurants Uxbridge London",
    "brunch Uxbridge London",
    "pizza restaurant Uxbridge London UB8",
    "gastropub Uxbridge London",
    # Greenwich extended
    "restaurants Blackheath London SE3",
    "cafes Blackheath London SE3",
    "restaurants Blackheath Village London SE3",
    "cafes Blackheath Village London SE3",
    "restaurants Lee London SE12",
    "cafes Lee London SE12",
    "restaurants Grove Park London SE12",
    "brunch Blackheath London",
    "gastropub Blackheath London",
    "pizza restaurant Blackheath London SE3",
    "wine bar Blackheath London",
    "vegan restaurant Blackheath London",
    # Lewisham extended
    "restaurants Brockley London SE4",
    "cafes Brockley London SE4",
    "restaurants Crofton Park London SE4",
    "cafes Crofton Park London SE4",
    "restaurants Ladywell London SE13",
    "cafes Ladywell London SE13",
    "restaurants Bellingham London SE6",
    "brunch Brockley London",
    "pizza restaurant Brockley London SE4",
    "wine bar Brockley London",
    "gastropub Brockley London",
    # Sutton extended
    "restaurants Cheam London SM3",
    "cafes Cheam London SM3",
    "restaurants Belmont London SM2",
    "cafes Belmont London SM2",
    "restaurants Banstead London SM7",
    "cafes Banstead London SM7",
    "gastropub Cheam London",
    "pizza restaurant Cheam London SM3",
    # Food trucks and van
    "food truck London E1",
    "food truck London EC1",
    "food truck London WC1",
    "food truck London N1",
    "food truck London SE1",
    "food truck London SW9",
    "food truck London W1",
    "food truck London NW1",
    "food truck Shoreditch London",
    "food truck Brixton London",
    "food truck Hackney London",
    "food truck Dalston London",
    "food truck Peckham London",
    "food truck Bermondsey London",
    "food truck Camden London",
    "food truck Stratford London",
    "food truck Canary Wharf London",
    "street food van London",
    "street food trader London",
    # Taproom and brewery restaurant
    "taproom restaurant London E1",
    "taproom restaurant London N1",
    "taproom restaurant London SE1",
    "taproom restaurant London SW9",
    "taproom restaurant London SW11",
    "taproom restaurant London W1",
    "taproom restaurant London EC1",
    "taproom restaurant London NW1",
    "taproom restaurant Brixton London",
    "taproom restaurant Hackney London",
    "taproom restaurant Bermondsey London",
    "taproom restaurant Dalston London",
    "taproom restaurant Peckham London",
    "taproom restaurant Walthamstow London",
    "taproom restaurant Tottenham London",
    # Ramen / noodle shops x outer London
    "ramen restaurant Croydon London CR0",
    "ramen restaurant Wimbledon London SW19",
    "ramen restaurant Kingston London KT1",
    "ramen restaurant Barnet London EN5",
    "ramen restaurant Ealing London W5",
    "ramen restaurant Wembley London HA9",
    "ramen restaurant Ilford London IG1",
    "noodle bar Croydon London",
    "noodle bar Kingston London",
    "noodle bar Ealing London",
    "noodle bar Ilford London",
    # Sushi x outer London
    "sushi restaurant Croydon London CR0",
    "sushi restaurant Wimbledon London SW19",
    "sushi restaurant Kingston London KT1",
    "sushi restaurant Ealing London W5",
    "sushi restaurant Wembley London HA9",
    "sushi restaurant Ilford London IG1",
    "sushi restaurant Barnet London EN5",
    # Bubble tea / boba x outer London
    "bubble tea Croydon London",
    "bubble tea Ilford London",
    "bubble tea Wembley London",
    "bubble tea Ealing London",
    "bubble tea Romford London",
    "bubble tea Barking London",
    "bubble tea Stratford London E15",
    "bubble tea Hounslow London",
    "boba London Croydon",
    "boba London Wembley",
    "boba London Ilford",
]
