"""
Batch 59 – Cuisine × outer London postcodes (systematic):
Cuisines: Indian, Chinese, Thai, Italian, Turkish, Caribbean, African, Japanese, Korean,
Vietnamese, Pizza, Burger paired with outer London postcodes:
IG1-8, RM1-14, DA1-17, BR1-8, CR0-8, SM1-7, KT1-22, TW1-20, HA0-9, UB1-10, EN1-8, N9/N18/N21
"""

SEARCH_QUERIES = [
    # Indian × outer East (IG/RM)
    ("Indian restaurants Ilford London IG1", "Restaurant", 55),
    ("Indian restaurants Seven Kings London IG3", "Restaurant", 45),
    ("Indian restaurants Goodmayes London IG3", "Restaurant", 45),
    ("Indian restaurants Gants Hill London IG2", "Restaurant", 50),
    ("Indian restaurants Redbridge London IG4", "Restaurant", 45),
    ("Indian restaurants Barkingside London IG6", "Restaurant", 45),
    ("Indian restaurants Newbury Park London IG2", "Restaurant", 45),
    ("Indian restaurants Romford London RM1", "Restaurant", 55),
    ("Indian restaurants Harold Wood London RM3", "Restaurant", 40),
    ("Indian restaurants Hornchurch London RM11", "Restaurant", 45),
    ("Indian restaurants Upminster London RM14", "Restaurant", 40),
    ("Indian restaurants Rainham London RM13", "Restaurant", 40),
    ("Indian restaurants Dagenham London RM10", "Restaurant", 45),
    ("Indian restaurants Barking London RM8", "Restaurant", 50),

    # Chinese × outer South (DA/BR/CR)
    ("Chinese restaurants Dartford London DA1", "Restaurant", 45),
    ("Chinese restaurants Erith London DA8", "Restaurant", 40),
    ("Chinese restaurants Bexleyheath London DA6", "Restaurant", 45),
    ("Chinese restaurants Sidcup London DA14", "Restaurant", 45),
    ("Chinese restaurants Bromley London BR1", "Restaurant", 55),
    ("Chinese restaurants Beckenham London BR3", "Restaurant", 50),
    ("Chinese restaurants Orpington London BR6", "Restaurant", 45),
    ("Chinese restaurants Petts Wood London BR5", "Restaurant", 40),
    ("Chinese restaurants Croydon London CR0", "Restaurant", 55),
    ("Chinese restaurants South Croydon London CR2", "Restaurant", 45),
    ("Chinese restaurants Thornton Heath London CR7", "Restaurant", 45),
    ("Chinese restaurants Purley London CR8", "Restaurant", 45),
    ("Chinese restaurants Norbury London CR7", "Restaurant", 45),
    ("Chinese restaurants Addiscombe London CR0", "Restaurant", 40),

    # Thai × outer South/West (SM/KT/TW)
    ("Thai restaurants Sutton London SM1", "Restaurant", 50),
    ("Thai restaurants Cheam London SM3", "Restaurant", 40),
    ("Thai restaurants Morden London SM4", "Restaurant", 45),
    ("Thai restaurants Carshalton London SM5", "Restaurant", 40),
    ("Thai restaurants Wallington London SM6", "Restaurant", 40),
    ("Thai restaurants Kingston London KT1", "Restaurant", 55),
    ("Thai restaurants New Malden London KT3", "Restaurant", 55),
    ("Thai restaurants Surbiton London KT6", "Restaurant", 50),
    ("Thai restaurants Tolworth London KT5", "Restaurant", 40),
    ("Thai restaurants Twickenham London TW1", "Restaurant", 55),
    ("Thai restaurants Teddington London TW11", "Restaurant", 50),
    ("Thai restaurants Feltham London TW13", "Restaurant", 45),
    ("Thai restaurants Hounslow London TW3", "Restaurant", 50),
    ("Thai restaurants Isleworth London TW7", "Restaurant", 45),

    # Italian × outer West (UB/HA)
    ("Italian restaurants Southall London UB1", "Restaurant", 55),
    ("Italian restaurants Greenford London UB6", "Restaurant", 45),
    ("Italian restaurants Northolt London UB5", "Restaurant", 45),
    ("Italian restaurants Hayes London UB3", "Restaurant", 45),
    ("Italian restaurants West Drayton London UB7", "Restaurant", 40),
    ("Italian restaurants Uxbridge London UB8", "Restaurant", 50),
    ("Italian restaurants Ruislip London HA4", "Restaurant", 45),
    ("Italian restaurants Harrow London HA1", "Restaurant", 55),
    ("Italian restaurants Wealdstone London HA3", "Restaurant", 45),
    ("Italian restaurants North Harrow London HA2", "Restaurant", 45),
    ("Italian restaurants Rayners Lane London HA2", "Restaurant", 45),
    ("Italian restaurants Pinner London HA5", "Restaurant", 45),
    ("Italian restaurants Wembley London HA9", "Restaurant", 55),
    ("Italian restaurants Kenton London HA3", "Restaurant", 40),

    # Turkish × outer North (EN/N9/N18/N21)
    ("Turkish restaurants Enfield London EN1", "Restaurant", 55),
    ("Turkish restaurants Edmonton London N9", "Restaurant", 55),
    ("Turkish restaurants Upper Edmonton London N18", "Restaurant", 50),
    ("Turkish restaurants Winchmore Hill London N21", "Restaurant", 45),
    ("Turkish restaurants Palmers Green London N13", "Restaurant", 50),
    ("Turkish restaurants Southgate London N14", "Restaurant", 45),
    ("Turkish restaurants Enfield Town London EN2", "Restaurant", 50),
    ("Turkish restaurants Enfield Highway London EN3", "Restaurant", 45),
    ("Turkish restaurants Enfield Lock London EN3", "Restaurant", 35),
    ("Turkish restaurants Ponders End London EN3", "Restaurant", 40),
    ("Turkish restaurants Cheshunt London EN8", "Restaurant", 35),
    ("Turkish restaurants Waltham Cross London EN8", "Restaurant", 35),

    # Caribbean × outer East (IG/RM/E20)
    ("Caribbean restaurants Ilford London IG1", "Restaurant", 45),
    ("Caribbean restaurants Forest Gate London E7", "Restaurant", 45),
    ("Caribbean restaurants Plaistow London E13", "Restaurant", 45),
    ("Caribbean restaurants Romford London RM1", "Restaurant", 40),
    ("Caribbean restaurants Barking London IG11", "Restaurant", 45),
    ("Caribbean restaurants Dagenham London RM9", "Restaurant", 40),
    ("Caribbean restaurants Stratford London E20", "Restaurant", 45),
    ("Caribbean restaurants Leyton London E10", "Restaurant", 40),
    ("Caribbean restaurants Walthamstow London E17", "Restaurant", 45),
    ("Caribbean restaurants Tottenham London N17", "Restaurant", 45),
    ("Caribbean restaurants Wood Green London N22", "Restaurant", 40),

    # African × outer areas
    ("African restaurants Peckham London SE15", "Restaurant", 50),
    ("African restaurants Woolwich London SE18", "Restaurant", 40),
    ("African restaurants Lewisham London SE13", "Restaurant", 40),
    ("African restaurants Tottenham London N17", "Restaurant", 45),
    ("African restaurants Walthamstow London E17", "Restaurant", 40),
    ("African restaurants Hackney London E8", "Restaurant", 40),
    ("African restaurants Harlesden London NW10", "Restaurant", 45),
    ("African restaurants Brixton London SW9", "Restaurant", 50),
    ("African restaurants Croydon London CR0", "Restaurant", 45),
    ("African restaurants Southall London UB1", "Restaurant", 40),
    ("African restaurants Ilford London IG1", "Restaurant", 40),

    # Japanese × outer South/West
    ("Japanese restaurants Wimbledon London SW19", "Restaurant", 50),
    ("Japanese restaurants Kingston London KT1", "Restaurant", 50),
    ("Japanese restaurants Richmond London TW9", "Restaurant", 50),
    ("Japanese restaurants Twickenham London TW1", "Restaurant", 45),
    ("Japanese restaurants New Malden London KT3", "Restaurant", 55),
    ("Japanese restaurants Sutton London SM1", "Restaurant", 40),
    ("Japanese restaurants Croydon London CR0", "Restaurant", 45),
    ("Japanese restaurants Bromley London BR1", "Restaurant", 40),
    ("Japanese restaurants Chiswick London W4", "Restaurant", 50),
    ("Japanese restaurants Ealing London W5", "Restaurant", 45),

    # Korean × outer areas
    ("Korean restaurants New Malden London KT3", "Restaurant", 60),
    ("Korean restaurants Kingston London KT1", "Restaurant", 50),
    ("Korean restaurants Wimbledon London SW19", "Restaurant", 45),
    ("Korean restaurants Croydon London CR0", "Restaurant", 40),
    ("Korean restaurants Ealing London W5", "Restaurant", 40),
    ("Korean restaurants Ilford London IG1", "Restaurant", 40),
    ("Korean restaurants Wembley London HA9", "Restaurant", 45),
    ("Korean restaurants Harrow London HA1", "Restaurant", 40),
    ("Korean restaurants Finchley London N12", "Restaurant", 40),
    ("Korean restaurants Edgware London HA8", "Restaurant", 35),

    # Vietnamese × outer areas
    ("Vietnamese restaurants Croydon London CR0", "Restaurant", 45),
    ("Vietnamese restaurants Sutton London SM1", "Restaurant", 40),
    ("Vietnamese restaurants Bromley London BR1", "Restaurant", 40),
    ("Vietnamese restaurants Ilford London IG1", "Restaurant", 40),
    ("Vietnamese restaurants Romford London RM1", "Restaurant", 35),
    ("Vietnamese restaurants Enfield London EN1", "Restaurant", 40),
    ("Vietnamese restaurants Wembley London HA9", "Restaurant", 40),
    ("Vietnamese restaurants Harrow London HA1", "Restaurant", 40),
    ("Vietnamese restaurants Twickenham London TW1", "Restaurant", 40),
    ("Vietnamese restaurants Kingston London KT1", "Restaurant", 40),
    ("Vietnamese restaurants Ealing London W5", "Restaurant", 40),

    # Pizza × outer areas (varied)
    ("pizza restaurants Ilford London IG1", "Restaurant", 45),
    ("pizza restaurants Romford London RM1", "Restaurant", 45),
    ("pizza restaurants Hornchurch London RM12", "Restaurant", 40),
    ("pizza restaurants Dagenham London RM10", "Restaurant", 40),
    ("pizza restaurants Barking London IG11", "Restaurant", 45),
    ("pizza restaurants Croydon London CR0", "Restaurant", 50),
    ("pizza restaurants Bromley London BR1", "Restaurant", 50),
    ("pizza restaurants Sutton London SM1", "Restaurant", 45),
    ("pizza restaurants Kingston London KT1", "Restaurant", 50),
    ("pizza restaurants Twickenham London TW1", "Restaurant", 45),
    ("pizza restaurants Hounslow London TW3", "Restaurant", 45),
    ("pizza restaurants Southall London UB1", "Restaurant", 40),
    ("pizza restaurants Harrow London HA1", "Restaurant", 50),
    ("pizza restaurants Enfield London EN1", "Restaurant", 45),
    ("pizza restaurants Edmonton London N9", "Restaurant", 40),

    # Burger × outer areas (varied)
    ("burger restaurants Croydon London CR0", "Restaurant", 50),
    ("burger restaurants Bromley London BR1", "Restaurant", 45),
    ("burger restaurants Romford London RM1", "Restaurant", 45),
    ("burger restaurants Ilford London IG1", "Restaurant", 45),
    ("burger restaurants Kingston London KT1", "Restaurant", 50),
    ("burger restaurants Twickenham London TW1", "Restaurant", 40),
    ("burger restaurants Harrow London HA1", "Restaurant", 45),
    ("burger restaurants Wembley London HA9", "Restaurant", 45),
    ("burger restaurants Hounslow London TW3", "Restaurant", 40),
    ("burger restaurants Enfield London EN1", "Restaurant", 45),
    ("burger restaurants Edmonton London N9", "Restaurant", 40),
    ("burger restaurants Sutton London SM1", "Restaurant", 40),
    ("burger restaurants Uxbridge London UB8", "Restaurant", 40),
    ("burger restaurants Bexleyheath London DA6", "Restaurant", 40),
    ("burger restaurants Sidcup London DA14", "Restaurant", 35),

    # More Indian × outer South/West/North
    ("Indian restaurants Wembley London HA9", "Restaurant", 55),
    ("Indian restaurants Southall London UB1", "Restaurant", 60),
    ("Indian restaurants Hounslow London TW3", "Restaurant", 55),
    ("Indian restaurants Harrow London HA1", "Restaurant", 55),
    ("Indian restaurants Ealing London W5", "Restaurant", 50),
    ("Indian restaurants Tooting London SW17", "Restaurant", 55),
    ("Indian restaurants Walthamstow London E17", "Restaurant", 50),
    ("Indian restaurants Tottenham London N17", "Restaurant", 50),
    ("Indian restaurants Enfield London EN1", "Restaurant", 50),
    ("Indian restaurants Croydon London CR0", "Restaurant", 55),
    ("Indian restaurants Sutton London SM1", "Restaurant", 45),
    ("Indian restaurants Bromley London BR1", "Restaurant", 45),
    ("Indian restaurants Kingston London KT1", "Restaurant", 50),
    ("Indian restaurants Twickenham London TW1", "Restaurant", 50),
    ("Indian restaurants Bexleyheath London DA6", "Restaurant", 40),

    # More Chinese × outer North/West
    ("Chinese restaurants Wembley London HA9", "Restaurant", 50),
    ("Chinese restaurants Ealing London W5", "Restaurant", 50),
    ("Chinese restaurants Enfield London EN1", "Restaurant", 40),
    ("Chinese restaurants Tottenham London N17", "Restaurant", 45),
    ("Chinese restaurants Wood Green London N22", "Restaurant", 45),
    ("Chinese restaurants Finchley London N12", "Restaurant", 45),
    ("Chinese restaurants Harrow London HA1", "Restaurant", 50),
    ("Chinese restaurants Hounslow London TW3", "Restaurant", 45),
    ("Chinese restaurants Kingston London KT1", "Restaurant", 50),
    ("Chinese restaurants Twickenham London TW1", "Restaurant", 45),
    ("Chinese restaurants Richmond London TW9", "Restaurant", 45),
    ("Chinese restaurants Wimbledon London SW19", "Restaurant", 45),

    # More Thai × outer East
    ("Thai restaurants Ilford London IG1", "Restaurant", 45),
    ("Thai restaurants Romford London RM1", "Restaurant", 40),
    ("Thai restaurants Barking London IG11", "Restaurant", 40),
    ("Thai restaurants Stratford London E15", "Restaurant", 45),
    ("Thai restaurants Walthamstow London E17", "Restaurant", 45),
    ("Thai restaurants Hackney London E8", "Restaurant", 45),
    ("Thai restaurants Wood Green London N22", "Restaurant", 40),
    ("Thai restaurants Tottenham London N17", "Restaurant", 40),
    ("Thai restaurants Enfield London EN1", "Restaurant", 40),

    # More Turkish × outer West/South
    ("Turkish restaurants Wembley London HA9", "Restaurant", 45),
    ("Turkish restaurants Harrow London HA1", "Restaurant", 45),
    ("Turkish restaurants Wood Green London N22", "Restaurant", 55),
    ("Turkish restaurants Seven Sisters London N15", "Restaurant", 55),
    ("Turkish restaurants Stoke Newington London N16", "Restaurant", 55),
    ("Turkish restaurants Dalston London E8", "Restaurant", 55),
    ("Turkish restaurants Hackney London E8", "Restaurant", 50),
    ("Turkish restaurants Leyton London E10", "Restaurant", 40),
    ("Turkish restaurants Walthamstow London E17", "Restaurant", 45),

    # More Caribbean × South/West
    ("Caribbean restaurants Brixton London SW9", "Restaurant", 55),
    ("Caribbean restaurants Lewisham London SE13", "Restaurant", 40),
    ("Caribbean restaurants Deptford London SE8", "Restaurant", 40),
    ("Caribbean restaurants Peckham London SE15", "Restaurant", 50),
    ("Caribbean restaurants Harlesden London NW10", "Restaurant", 55),
    ("Caribbean restaurants Hackney London E8", "Restaurant", 45),
    ("Caribbean restaurants Croydon London CR0", "Restaurant", 45),
    ("Caribbean restaurants Wembley London HA9", "Restaurant", 40),

    # More Vietnamese × inner areas
    ("Vietnamese restaurants Hackney London E8", "Restaurant", 45),
    ("Vietnamese restaurants Dalston London E8", "Restaurant", 45),
    ("Vietnamese restaurants Shoreditch London E1", "Restaurant", 50),
    ("Vietnamese restaurants Peckham London SE15", "Restaurant", 45),
    ("Vietnamese restaurants Brixton London SW9", "Restaurant", 40),
    ("Vietnamese restaurants Islington London N1", "Restaurant", 45),
    ("Vietnamese restaurants Camden London NW1", "Restaurant", 45),

    # More Korean × varied
    ("Korean restaurants Finchley Road London NW3", "Restaurant", 45),
    ("Korean restaurants Golders Green London NW11", "Restaurant", 45),
    ("Korean restaurants Edgware Road London W2", "Restaurant", 40),
    ("Korean restaurants Soho London W1", "Restaurant", 50),
    ("Korean restaurants Covent Garden London WC2", "Restaurant", 45),
    ("Korean restaurants Canary Wharf London E14", "Restaurant", 40),
    ("Korean restaurants Stratford London E15", "Restaurant", 40),

    # Italian × outer East/North
    ("Italian restaurants Walthamstow London E17", "Restaurant", 45),
    ("Italian restaurants Leyton London E10", "Restaurant", 40),
    ("Italian restaurants Ilford London IG1", "Restaurant", 45),
    ("Italian restaurants Romford London RM1", "Restaurant", 45),
    ("Italian restaurants Enfield London EN1", "Restaurant", 45),
    ("Italian restaurants Tottenham London N17", "Restaurant", 45),
    ("Italian restaurants Wood Green London N22", "Restaurant", 45),
    ("Italian restaurants Finchley London N12", "Restaurant", 45),
    ("Italian restaurants Barnet London EN5", "Restaurant", 40),
    ("Italian restaurants Edgware London HA8", "Restaurant", 40),

    # Japanese × outer North
    ("Japanese restaurants Finchley London N12", "Restaurant", 45),
    ("Japanese restaurants Golders Green London NW11", "Restaurant", 45),
    ("Japanese restaurants Edgware London HA8", "Restaurant", 35),
    ("Japanese restaurants Enfield London EN1", "Restaurant", 35),
    ("Japanese restaurants Wood Green London N22", "Restaurant", 40),
    ("Japanese restaurants Tottenham London N17", "Restaurant", 35),

    # More Pizza × inner areas (varied)
    ("pizza restaurants Hackney London E8", "Restaurant", 50),
    ("pizza restaurants Dalston London E8", "Restaurant", 50),
    ("pizza restaurants Shoreditch London E1", "Restaurant", 55),
    ("pizza restaurants Islington London N1", "Restaurant", 55),
    ("pizza restaurants Brixton London SW9", "Restaurant", 50),
    ("pizza restaurants Peckham London SE15", "Restaurant", 50),
    ("pizza restaurants Bermondsey London SE1", "Restaurant", 50),
    ("pizza restaurants Clapham London SW4", "Restaurant", 50),
    ("pizza restaurants Battersea London SW11", "Restaurant", 50),
    ("pizza restaurants Hammersmith London W6", "Restaurant", 50),
    ("pizza restaurants Chiswick London W4", "Restaurant", 45),
    ("pizza restaurants Notting Hill London W11", "Restaurant", 50),
    ("pizza restaurants Camden London NW1", "Restaurant", 55),
    ("pizza restaurants Walthamstow London E17", "Restaurant", 45),

    # More Burger × inner areas
    ("burger restaurants Hackney London E8", "Restaurant", 50),
    ("burger restaurants Shoreditch London E1", "Restaurant", 55),
    ("burger restaurants Brixton London SW9", "Restaurant", 50),
    ("burger restaurants Peckham London SE15", "Restaurant", 45),
    ("burger restaurants Islington London N1", "Restaurant", 55),
    ("burger restaurants Camden London NW1", "Restaurant", 55),
    ("burger restaurants Clapham London SW4", "Restaurant", 50),
    ("burger restaurants Hammersmith London W6", "Restaurant", 50),
    ("burger restaurants Stratford London E15", "Restaurant", 45),
    ("burger restaurants Canary Wharf London E14", "Restaurant", 50),

    # More African × varied
    ("African restaurants Southall London UB1", "Restaurant", 40),
    ("African restaurants Newham London E6", "Restaurant", 40),
    ("African restaurants Barking London IG11", "Restaurant", 40),
    ("African restaurants Enfield London EN1", "Restaurant", 35),
    ("West African restaurant London", "Restaurant", 50),
    ("East African restaurant London", "Restaurant", 45),
    ("Ethiopian restaurant London", "Restaurant", 50),
    ("Ghanaian restaurant London", "Restaurant", 45),
    ("Nigerian restaurant London", "Restaurant", 50),
    ("Somali restaurant London", "Restaurant", 40),
    ("Eritrean restaurant London", "Restaurant", 40),
]
